// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models.v1.customers

import com.metronome.api.core.JsonValue
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomerSetBillingConfigurationsParamsTest {

    @Test
    fun create() {
        CustomerSetBillingConfigurationsParams.builder()
            .data(
                listOf(
                    CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            CustomerSetBillingConfigurationsParams.Data.BillingProvider.STRIPE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("stripe_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty(
                                    "stripe_collection_method",
                                    JsonValue.from("bar"),
                                )
                                .putAdditionalProperty(
                                    "leave_stripe_invoices_in_draft",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                        .build(),
                    CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_product_code", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                .build()
                        )
                        .deliveryMethod(
                            CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                        .build(),
                    CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AZURE_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty(
                                    "azure_subscription_id",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("5b9e3072-415b-4842-94f0-0b6700c8b6be")
                        .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                        .build(),
                    CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_product_code", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                .putAdditionalProperty(
                                    "aws_is_subscription_product",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                        .build(),
                    CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .GCP_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("gcp_entitlement_id", JsonValue.from("bar"))
                                .putAdditionalProperty("gcp_service_name", JsonValue.from("bar"))
                                .build()
                        )
                        .deliveryMethod(
                            CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                        .build(),
                    CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            CustomerSetBillingConfigurationsParams.Data.BillingProvider.NETSUITE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty(
                                    "netsuite_customer_id",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                        .build(),
                )
            )
            .build()
    }

    @Test
    fun body() {
        val params =
            CustomerSetBillingConfigurationsParams.builder()
                .data(
                    listOf(
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider.STRIPE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                    .putAdditionalProperty(
                                        "stripe_customer_id",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty(
                                        "stripe_collection_method",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty(
                                        "leave_stripe_invoices_in_draft",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                    .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                    .putAdditionalProperty(
                                        "aws_product_code",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                    .build()
                            )
                            .deliveryMethod(
                                CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AZURE_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                    .putAdditionalProperty(
                                        "azure_subscription_id",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("5b9e3072-415b-4842-94f0-0b6700c8b6be")
                            .taxProvider(
                                CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                    .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                    .putAdditionalProperty(
                                        "aws_product_code",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                    .putAdditionalProperty(
                                        "aws_is_subscription_product",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .GCP_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                    .putAdditionalProperty(
                                        "gcp_entitlement_id",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty(
                                        "gcp_service_name",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider.NETSUITE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                    .putAdditionalProperty(
                                        "netsuite_customer_id",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                    )
                )
                .build()

        val body = params._body()

        assertThat(body.data())
            .containsExactly(
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.STRIPE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .configuration(
                        CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                            .putAdditionalProperty("stripe_customer_id", JsonValue.from("bar"))
                            .putAdditionalProperty(
                                "stripe_collection_method",
                                JsonValue.from("bar"),
                            )
                            .putAdditionalProperty(
                                "leave_stripe_invoices_in_draft",
                                JsonValue.from("bar"),
                            )
                            .build()
                    )
                    .deliveryMethod(
                        CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                            .DIRECT_TO_BILLING_PROVIDER
                    )
                    .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.AWS_MARKETPLACE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .configuration(
                        CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                            .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                            .putAdditionalProperty("aws_product_code", JsonValue.from("bar"))
                            .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                            .build()
                    )
                    .deliveryMethod(
                        CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                            .DIRECT_TO_BILLING_PROVIDER
                    )
                    .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider
                            .AZURE_MARKETPLACE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .configuration(
                        CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                            .putAdditionalProperty("azure_subscription_id", JsonValue.from("bar"))
                            .build()
                    )
                    .deliveryMethod(
                        CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                            .DIRECT_TO_BILLING_PROVIDER
                    )
                    .deliveryMethodId("5b9e3072-415b-4842-94f0-0b6700c8b6be")
                    .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.AWS_MARKETPLACE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .configuration(
                        CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                            .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                            .putAdditionalProperty("aws_product_code", JsonValue.from("bar"))
                            .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                            .putAdditionalProperty(
                                "aws_is_subscription_product",
                                JsonValue.from("bar"),
                            )
                            .build()
                    )
                    .deliveryMethod(
                        CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                            .DIRECT_TO_BILLING_PROVIDER
                    )
                    .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.GCP_MARKETPLACE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .configuration(
                        CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                            .putAdditionalProperty("gcp_entitlement_id", JsonValue.from("bar"))
                            .putAdditionalProperty("gcp_service_name", JsonValue.from("bar"))
                            .build()
                    )
                    .deliveryMethod(
                        CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                            .DIRECT_TO_BILLING_PROVIDER
                    )
                    .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.NETSUITE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .configuration(
                        CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                            .putAdditionalProperty("netsuite_customer_id", JsonValue.from("bar"))
                            .build()
                    )
                    .deliveryMethod(
                        CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                            .DIRECT_TO_BILLING_PROVIDER
                    )
                    .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .taxProvider(CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK)
                    .build(),
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            CustomerSetBillingConfigurationsParams.builder()
                .data(
                    listOf(
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider.STRIPE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AZURE_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .GCP_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                CustomerSetBillingConfigurationsParams.Data.BillingProvider.NETSUITE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                    )
                )
                .build()

        val body = params._body()

        assertThat(body.data())
            .containsExactly(
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.STRIPE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.AWS_MARKETPLACE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider
                            .AZURE_MARKETPLACE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.AWS_MARKETPLACE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.GCP_MARKETPLACE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .build(),
                CustomerSetBillingConfigurationsParams.Data.builder()
                    .billingProvider(
                        CustomerSetBillingConfigurationsParams.Data.BillingProvider.NETSUITE
                    )
                    .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                    .build(),
            )
    }
}
