// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.proguard

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.metronome.api.client.okhttp.MetronomeOkHttpClient
import com.metronome.api.core.JsonValue
import com.metronome.api.core.jsonMapper
import com.metronome.api.models.BaseThresholdCommit
import com.metronome.api.models.Commit
import com.metronome.api.models.CommitHierarchyConfiguration
import com.metronome.api.models.CommitSpecifier
import com.metronome.api.models.CommitSpecifierInput
import com.metronome.api.models.Credit
import com.metronome.api.models.CreditTypeData
import com.metronome.api.models.HierarchyConfiguration
import com.metronome.api.models.Override
import com.metronome.api.models.OverrideTier
import com.metronome.api.models.OverwriteRate
import com.metronome.api.models.PaymentGateConfig
import com.metronome.api.models.PrepaidBalanceThresholdConfiguration
import com.metronome.api.models.RecurringCommitSubscriptionConfig
import com.metronome.api.models.ScheduleDuration
import com.metronome.api.models.SchedulePointInTime
import com.metronome.api.models.ScheduledCharge
import com.metronome.api.models.SpendThresholdConfiguration
import com.metronome.api.models.Subscription
import com.metronome.api.models.v1.contracts.ContractCreateResponse
import com.metronome.api.models.v1.contracts.ContractListBalancesResponse
import java.time.OffsetDateTime
import kotlin.reflect.full.memberFunctions
import kotlin.reflect.jvm.javaMethod
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProGuardCompatibilityTest {

    companion object {

        @JvmStatic
        fun main(args: Array<String>) {
            // To debug that we're using the right JAR.
            val jarPath = this::class.java.getProtectionDomain().codeSource.location
            println("JAR being used: $jarPath")

            // We have to manually run the test methods instead of using the JUnit runner because it
            // seems impossible to get working with R8.
            val test = ProGuardCompatibilityTest()
            test::class
                .memberFunctions
                .asSequence()
                .filter { function ->
                    function.javaMethod?.isAnnotationPresent(Test::class.java) == true
                }
                .forEach { it.call(test) }
        }
    }

    @Test
    fun proguardRules() {
        val rulesFile =
            javaClass.classLoader.getResourceAsStream("META-INF/proguard/metronome-java-core.pro")

        assertThat(rulesFile).isNotNull()
    }

    @Test
    fun client() {
        val client = MetronomeOkHttpClient.builder().bearerToken("My Bearer Token").build()

        assertThat(client).isNotNull()
        assertThat(client.webhooks()).isNotNull()
        assertThat(client.v2()).isNotNull()
        assertThat(client.v1()).isNotNull()
    }

    @Test
    fun contractCreateResponseRoundtrip() {
        val jsonMapper = jsonMapper()
        val contractCreateResponse =
            ContractCreateResponse.builder()
                .data(
                    ContractCreateResponse.Data.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .contract(
                            ContractCreateResponse.Data.Contract.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addCommit(
                                    Commit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .product(
                                            Commit.Product.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .type(Commit.Type.PREPAID)
                                        .accessSchedule(
                                            ScheduleDuration.builder()
                                                .addScheduleItem(
                                                    ScheduleDuration.ScheduleItem.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .amount(0.0)
                                                        .endingBefore(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .startingAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .creditType(
                                                    CreditTypeData.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .name("name")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .amount(0.0)
                                        .addApplicableContractId(
                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                        )
                                        .addApplicableProductId(
                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                        )
                                        .addApplicableProductTag("string")
                                        .archivedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .balance(0.0)
                                        .contract(
                                            Commit.Contract.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .costBasis(0.0)
                                        .createdBy("created_by")
                                        .customFields(
                                            Commit.CustomFields.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .description("description")
                                        .hierarchyConfiguration(
                                            CommitHierarchyConfiguration.builder()
                                                .childAccess(
                                                    CommitHierarchyConfiguration.ChildAccess
                                                        .CommitHierarchyChildAccessAll
                                                        .builder()
                                                        .type(
                                                            CommitHierarchyConfiguration.ChildAccess
                                                                .CommitHierarchyChildAccessAll
                                                                .Type
                                                                .ALL
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .invoiceContract(
                                            Commit.InvoiceContract.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .invoiceSchedule(
                                            SchedulePointInTime.builder()
                                                .creditType(
                                                    CreditTypeData.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .name("name")
                                                        .build()
                                                )
                                                .doNotInvoice(true)
                                                .addScheduleItem(
                                                    SchedulePointInTime.ScheduleItem.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .amount(0.0)
                                                        .quantity(0.0)
                                                        .timestamp(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .unitPrice(0.0)
                                                        .invoiceId(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addLedger(
                                            Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry
                                                .builder()
                                                .amount(0.0)
                                                .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .type(
                                                    Commit.Ledger
                                                        .PrepaidCommitSegmentStartLedgerEntry
                                                        .Type
                                                        .PREPAID_COMMIT_SEGMENT_START
                                                )
                                                .build()
                                        )
                                        .name("name")
                                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                                        .priority(0.0)
                                        .rateType(Commit.RateType.COMMIT_RATE)
                                        .recurringCommitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .rolledOverFrom(
                                            Commit.RolledOverFrom.builder()
                                                .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .rolloverFraction(0.0)
                                        .salesforceOpportunityId("salesforce_opportunity_id")
                                        .addSpecifier(
                                            CommitSpecifier.builder()
                                                .presentationGroupValues(
                                                    CommitSpecifier.PresentationGroupValues
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .pricingGroupValues(
                                                    CommitSpecifier.PricingGroupValues.builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .addProductTag("string")
                                                .build()
                                        )
                                        .spendTrackerAttributes(
                                            Commit.SpendTrackerAttributes.builder()
                                                .countsAsDiscounted(true)
                                                .build()
                                        )
                                        .subscriptionConfig(
                                            Commit.SubscriptionConfig.builder()
                                                .allocation(
                                                    Commit.SubscriptionConfig.Allocation.INDIVIDUAL
                                                )
                                                .applySeatIncreaseConfig(
                                                    Commit.SubscriptionConfig
                                                        .ApplySeatIncreaseConfig
                                                        .builder()
                                                        .isProrated(true)
                                                        .build()
                                                )
                                                .subscriptionId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .build()
                                        )
                                        .uniquenessKey("x")
                                        .build()
                                )
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdBy("created_by")
                                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addOverride(
                                    Override.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .addApplicableProductTag("string")
                                        .creditType(
                                            CreditTypeData.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .entitled(true)
                                        .isCommitSpecific(true)
                                        .isProrated(true)
                                        .multiplier(0.0)
                                        .addOverrideSpecifier(
                                            Override.OverrideSpecifier.builder()
                                                .addAnyCommitOrCreditId("string")
                                                .billingFrequency(
                                                    Override.OverrideSpecifier.BillingFrequency
                                                        .MONTHLY
                                                )
                                                .addCommitId("string")
                                                .presentationGroupValues(
                                                    Override.OverrideSpecifier
                                                        .PresentationGroupValues
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .pricingGroupValues(
                                                    Override.OverrideSpecifier.PricingGroupValues
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .addProductTag("string")
                                                .addRecurringCommitId("string")
                                                .build()
                                        )
                                        .addOverrideTier(
                                            OverrideTier.builder().multiplier(0.0).size(0.0).build()
                                        )
                                        .overwriteRate(
                                            OverwriteRate.builder()
                                                .rateType(OverwriteRate.RateType.FLAT)
                                                .creditType(
                                                    CreditTypeData.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .name("name")
                                                        .build()
                                                )
                                                .customRate(
                                                    OverwriteRate.CustomRate.builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .isProrated(true)
                                                .price(0.0)
                                                .quantity(0.0)
                                                .addTier(
                                                    OverwriteRate.Tier.builder()
                                                        .price(0.0)
                                                        .size(0.0)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .price(0.0)
                                        .priority(0.0)
                                        .product(
                                            Override.Product.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .quantity(0.0)
                                        .rateType(Override.RateType.FLAT)
                                        .target(Override.Target.COMMIT_RATE)
                                        .addTier(
                                            Override.Tier.builder().price(0.0).size(0.0).build()
                                        )
                                        .type(Override.Type.OVERWRITE)
                                        .value(
                                            Override.Value.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .build()
                                )
                                .addScheduledCharge(
                                    ScheduledCharge.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .product(
                                            ScheduledCharge.Product.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .schedule(
                                            SchedulePointInTime.builder()
                                                .creditType(
                                                    CreditTypeData.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .name("name")
                                                        .build()
                                                )
                                                .doNotInvoice(true)
                                                .addScheduleItem(
                                                    SchedulePointInTime.ScheduleItem.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .amount(0.0)
                                                        .quantity(0.0)
                                                        .timestamp(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .unitPrice(0.0)
                                                        .invoiceId(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .archivedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .customFields(
                                            ScheduledCharge.CustomFields.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .name("x")
                                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                                        .build()
                                )
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addTransition(
                                    ContractCreateResponse.Data.Contract.Transition.builder()
                                        .fromContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .toContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .type(
                                            ContractCreateResponse.Data.Contract.Transition.Type
                                                .RENEWAL
                                        )
                                        .build()
                                )
                                .addUsageFilter(
                                    ContractCreateResponse.Data.Contract.UsageFilter.builder()
                                        .groupKey("group_key")
                                        .addGroupValue("string")
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .usageStatementSchedule(
                                    ContractCreateResponse.Data.Contract.UsageStatementSchedule
                                        .builder()
                                        .billingAnchorDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractCreateResponse.Data.Contract
                                                .UsageStatementSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .build()
                                )
                                .addCredit(
                                    Credit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .product(
                                            Credit.Product.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .type(Credit.Type.CREDIT)
                                        .accessSchedule(
                                            ScheduleDuration.builder()
                                                .addScheduleItem(
                                                    ScheduleDuration.ScheduleItem.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .amount(0.0)
                                                        .endingBefore(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .startingAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .creditType(
                                                    CreditTypeData.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .name("name")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addApplicableContractId(
                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                        )
                                        .addApplicableProductId(
                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                        )
                                        .addApplicableProductTag("string")
                                        .balance(0.0)
                                        .contract(
                                            Credit.Contract.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .createdBy("created_by")
                                        .customFields(
                                            Credit.CustomFields.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .description("description")
                                        .hierarchyConfiguration(
                                            CommitHierarchyConfiguration.builder()
                                                .childAccess(
                                                    CommitHierarchyConfiguration.ChildAccess
                                                        .CommitHierarchyChildAccessAll
                                                        .builder()
                                                        .type(
                                                            CommitHierarchyConfiguration.ChildAccess
                                                                .CommitHierarchyChildAccessAll
                                                                .Type
                                                                .ALL
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addLedger(
                                            Credit.Ledger.CreditSegmentStartLedgerEntry.builder()
                                                .amount(0.0)
                                                .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .type(
                                                    Credit.Ledger.CreditSegmentStartLedgerEntry.Type
                                                        .CREDIT_SEGMENT_START
                                                )
                                                .build()
                                        )
                                        .name("name")
                                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                                        .priority(0.0)
                                        .rateType(Credit.RateType.COMMIT_RATE)
                                        .recurringCreditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .rolledOverFrom(
                                            Credit.RolledOverFrom.builder()
                                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .creditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .salesforceOpportunityId("salesforce_opportunity_id")
                                        .addSpecifier(
                                            CommitSpecifier.builder()
                                                .presentationGroupValues(
                                                    CommitSpecifier.PresentationGroupValues
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .pricingGroupValues(
                                                    CommitSpecifier.PricingGroupValues.builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .addProductTag("string")
                                                .build()
                                        )
                                        .subscriptionConfig(
                                            Credit.SubscriptionConfig.builder()
                                                .allocation(
                                                    Credit.SubscriptionConfig.Allocation.INDIVIDUAL
                                                )
                                                .applySeatIncreaseConfig(
                                                    Credit.SubscriptionConfig
                                                        .ApplySeatIncreaseConfig
                                                        .builder()
                                                        .isProrated(true)
                                                        .build()
                                                )
                                                .subscriptionId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .build()
                                        )
                                        .uniquenessKey("x")
                                        .build()
                                )
                                .customFields(
                                    ContractCreateResponse.Data.Contract.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .customerBillingProviderConfiguration(
                                    ContractCreateResponse.Data.Contract
                                        .CustomerBillingProviderConfiguration
                                        .builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .archivedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .billingProvider(
                                            ContractCreateResponse.Data.Contract
                                                .CustomerBillingProviderConfiguration
                                                .BillingProvider
                                                .AWS_MARKETPLACE
                                        )
                                        .configuration(
                                            ContractCreateResponse.Data.Contract
                                                .CustomerBillingProviderConfiguration
                                                .Configuration
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .deliveryMethod(
                                            ContractCreateResponse.Data.Contract
                                                .CustomerBillingProviderConfiguration
                                                .DeliveryMethod
                                                .DIRECT_TO_BILLING_PROVIDER
                                        )
                                        .deliveryMethodConfiguration(
                                            ContractCreateResponse.Data.Contract
                                                .CustomerBillingProviderConfiguration
                                                .DeliveryMethodConfiguration
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .hasMore(
                                    ContractCreateResponse.Data.Contract.HasMore.builder()
                                        .commits(true)
                                        .credits(true)
                                        .build()
                                )
                                .hierarchyConfiguration(
                                    HierarchyConfiguration.ParentHierarchyConfiguration.builder()
                                        .addChild(
                                            HierarchyConfiguration.ParentHierarchyConfiguration
                                                .Child
                                                .builder()
                                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .parentBehavior(
                                            HierarchyConfiguration.ParentHierarchyConfiguration
                                                .ParentBehavior
                                                .builder()
                                                .invoiceConsolidationType(
                                                    HierarchyConfiguration
                                                        .ParentHierarchyConfiguration
                                                        .ParentBehavior
                                                        .InvoiceConsolidationType
                                                        .CONCATENATE
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .multiplierOverridePrioritization(
                                    ContractCreateResponse.Data.Contract
                                        .MultiplierOverridePrioritization
                                        .LOWEST_MULTIPLIER
                                )
                                .name("name")
                                .netPaymentTermsDays(0.0)
                                .packageId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .prepaidBalanceThresholdConfiguration(
                                    PrepaidBalanceThresholdConfiguration.builder()
                                        .commit(
                                            PrepaidBalanceThresholdConfiguration.Commit.builder()
                                                .productId("product_id")
                                                .description("description")
                                                .name("name")
                                                .priority(0.0)
                                                .addApplicableProductId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .addApplicableProductTag("string")
                                                .addSpecifier(
                                                    CommitSpecifierInput.builder()
                                                        .presentationGroupValues(
                                                            CommitSpecifierInput
                                                                .PresentationGroupValues
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "foo",
                                                                    JsonValue.from("string"),
                                                                )
                                                                .build()
                                                        )
                                                        .pricingGroupValues(
                                                            CommitSpecifierInput.PricingGroupValues
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "foo",
                                                                    JsonValue.from("string"),
                                                                )
                                                                .build()
                                                        )
                                                        .productId(
                                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                        )
                                                        .addProductTag("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .isEnabled(true)
                                        .paymentGateConfig(
                                            PaymentGateConfig.builder()
                                                .paymentGateType(
                                                    PaymentGateConfig.PaymentGateType.NONE
                                                )
                                                .precalculatedTaxConfig(
                                                    PaymentGateConfig.PrecalculatedTaxConfig
                                                        .builder()
                                                        .taxAmount(0.0)
                                                        .taxName("tax_name")
                                                        .build()
                                                )
                                                .stripeConfig(
                                                    PaymentGateConfig.StripeConfig.builder()
                                                        .paymentType(
                                                            PaymentGateConfig.StripeConfig
                                                                .PaymentType
                                                                .INVOICE
                                                        )
                                                        .invoiceMetadata(
                                                            PaymentGateConfig.StripeConfig
                                                                .InvoiceMetadata
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "foo",
                                                                    JsonValue.from("string"),
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .taxType(PaymentGateConfig.TaxType.NONE)
                                                .build()
                                        )
                                        .rechargeToAmount(0.0)
                                        .thresholdAmount(0.0)
                                        .customCreditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .discountConfiguration(
                                            PrepaidBalanceThresholdConfiguration
                                                .DiscountConfiguration
                                                .builder()
                                                .paymentFraction(0.0)
                                                .cap(
                                                    PrepaidBalanceThresholdConfiguration
                                                        .DiscountConfiguration
                                                        .Cap
                                                        .builder()
                                                        .amount(0.0)
                                                        .spendTrackerAlias("spend_tracker_alias")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addThresholdBalanceSpecifier(
                                            PrepaidBalanceThresholdConfiguration
                                                .ThresholdBalanceSpecifier
                                                .builder()
                                                .addExclude(
                                                    PrepaidBalanceThresholdConfiguration
                                                        .ThresholdBalanceSpecifier
                                                        .Exclude
                                                        .builder()
                                                        .addCustomFieldFilter(
                                                            PrepaidBalanceThresholdConfiguration
                                                                .ThresholdBalanceSpecifier
                                                                .Exclude
                                                                .CustomFieldFilter
                                                                .builder()
                                                                .entity(
                                                                    PrepaidBalanceThresholdConfiguration
                                                                        .ThresholdBalanceSpecifier
                                                                        .Exclude
                                                                        .CustomFieldFilter
                                                                        .Entity
                                                                        .COMMIT
                                                                )
                                                                .key("key")
                                                                .value("value")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .rateCardId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addRecurringCommit(
                                    ContractCreateResponse.Data.Contract.RecurringCommit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .accessAmount(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .AccessAmount
                                                .builder()
                                                .creditTypeId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .unitPrice(0.0)
                                                .quantity(0.0)
                                                .build()
                                        )
                                        .commitDuration(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .CommitDuration
                                                .builder()
                                                .value(0.0)
                                                .unit(
                                                    ContractCreateResponse.Data.Contract
                                                        .RecurringCommit
                                                        .CommitDuration
                                                        .Unit
                                                        .PERIODS
                                                )
                                                .build()
                                        )
                                        .priority(0.0)
                                        .product(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .Product
                                                .builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .rateType(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .RateType
                                                .COMMIT_RATE
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .addApplicableProductId(
                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                        )
                                        .addApplicableProductTag("string")
                                        .contract(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .InnerContract
                                                .builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .description("description")
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .hierarchyConfiguration(
                                            CommitHierarchyConfiguration.builder()
                                                .childAccess(
                                                    CommitHierarchyConfiguration.ChildAccess
                                                        .CommitHierarchyChildAccessAll
                                                        .builder()
                                                        .type(
                                                            CommitHierarchyConfiguration.ChildAccess
                                                                .CommitHierarchyChildAccessAll
                                                                .Type
                                                                .ALL
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .invoiceAmount(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .InvoiceAmount
                                                .builder()
                                                .creditTypeId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                        .name("name")
                                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                                        .proration(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .Proration
                                                .NONE
                                        )
                                        .prorationRounding(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .ProrationRounding
                                                .builder()
                                                .access(
                                                    ContractCreateResponse.Data.Contract
                                                        .RecurringCommit
                                                        .ProrationRounding
                                                        .Access
                                                        .builder()
                                                        .decimalPlaces(-5.0)
                                                        .roundingMethod(
                                                            ContractCreateResponse.Data.Contract
                                                                .RecurringCommit
                                                                .ProrationRounding
                                                                .Access
                                                                .RoundingMethod
                                                                .HALF_UP
                                                        )
                                                        .build()
                                                )
                                                .invoice(
                                                    ContractCreateResponse.Data.Contract
                                                        .RecurringCommit
                                                        .ProrationRounding
                                                        .Invoice
                                                        .builder()
                                                        .decimalPlaces(-5.0)
                                                        .roundingMethod(
                                                            ContractCreateResponse.Data.Contract
                                                                .RecurringCommit
                                                                .ProrationRounding
                                                                .Invoice
                                                                .RoundingMethod
                                                                .HALF_UP
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .recurrenceFrequency(
                                            ContractCreateResponse.Data.Contract.RecurringCommit
                                                .RecurrenceFrequency
                                                .MONTHLY
                                        )
                                        .rolloverFraction(0.0)
                                        .addSpecifier(
                                            CommitSpecifier.builder()
                                                .presentationGroupValues(
                                                    CommitSpecifier.PresentationGroupValues
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .pricingGroupValues(
                                                    CommitSpecifier.PricingGroupValues.builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .addProductTag("string")
                                                .build()
                                        )
                                        .subscriptionConfig(
                                            RecurringCommitSubscriptionConfig.builder()
                                                .allocation(
                                                    RecurringCommitSubscriptionConfig.Allocation
                                                        .INDIVIDUAL
                                                )
                                                .applySeatIncreaseConfig(
                                                    RecurringCommitSubscriptionConfig
                                                        .ApplySeatIncreaseConfig
                                                        .builder()
                                                        .isProrated(true)
                                                        .build()
                                                )
                                                .subscriptionId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .addRecurringCredit(
                                    ContractCreateResponse.Data.Contract.RecurringCredit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .accessAmount(
                                            ContractCreateResponse.Data.Contract.RecurringCredit
                                                .AccessAmount
                                                .builder()
                                                .creditTypeId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .unitPrice(0.0)
                                                .quantity(0.0)
                                                .build()
                                        )
                                        .commitDuration(
                                            ContractCreateResponse.Data.Contract.RecurringCredit
                                                .CommitDuration
                                                .builder()
                                                .value(0.0)
                                                .unit(
                                                    ContractCreateResponse.Data.Contract
                                                        .RecurringCredit
                                                        .CommitDuration
                                                        .Unit
                                                        .PERIODS
                                                )
                                                .build()
                                        )
                                        .priority(0.0)
                                        .product(
                                            ContractCreateResponse.Data.Contract.RecurringCredit
                                                .Product
                                                .builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .rateType(
                                            ContractCreateResponse.Data.Contract.RecurringCredit
                                                .RateType
                                                .COMMIT_RATE
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .addApplicableProductId(
                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                        )
                                        .addApplicableProductTag("string")
                                        .contract(
                                            ContractCreateResponse.Data.Contract.RecurringCredit
                                                .InnerContract
                                                .builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .description("description")
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .hierarchyConfiguration(
                                            CommitHierarchyConfiguration.builder()
                                                .childAccess(
                                                    CommitHierarchyConfiguration.ChildAccess
                                                        .CommitHierarchyChildAccessAll
                                                        .builder()
                                                        .type(
                                                            CommitHierarchyConfiguration.ChildAccess
                                                                .CommitHierarchyChildAccessAll
                                                                .Type
                                                                .ALL
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .name("name")
                                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                                        .proration(
                                            ContractCreateResponse.Data.Contract.RecurringCredit
                                                .Proration
                                                .NONE
                                        )
                                        .prorationRounding(
                                            ContractCreateResponse.Data.Contract.RecurringCredit
                                                .ProrationRounding
                                                .builder()
                                                .access(
                                                    ContractCreateResponse.Data.Contract
                                                        .RecurringCredit
                                                        .ProrationRounding
                                                        .Access
                                                        .builder()
                                                        .decimalPlaces(-5.0)
                                                        .roundingMethod(
                                                            ContractCreateResponse.Data.Contract
                                                                .RecurringCredit
                                                                .ProrationRounding
                                                                .Access
                                                                .RoundingMethod
                                                                .HALF_UP
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .recurrenceFrequency(
                                            ContractCreateResponse.Data.Contract.RecurringCredit
                                                .RecurrenceFrequency
                                                .MONTHLY
                                        )
                                        .rolloverFraction(0.0)
                                        .addSpecifier(
                                            CommitSpecifier.builder()
                                                .presentationGroupValues(
                                                    CommitSpecifier.PresentationGroupValues
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .pricingGroupValues(
                                                    CommitSpecifier.PricingGroupValues.builder()
                                                        .putAdditionalProperty(
                                                            "foo",
                                                            JsonValue.from("string"),
                                                        )
                                                        .build()
                                                )
                                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .addProductTag("string")
                                                .build()
                                        )
                                        .subscriptionConfig(
                                            RecurringCommitSubscriptionConfig.builder()
                                                .allocation(
                                                    RecurringCommitSubscriptionConfig.Allocation
                                                        .INDIVIDUAL
                                                )
                                                .applySeatIncreaseConfig(
                                                    RecurringCommitSubscriptionConfig
                                                        .ApplySeatIncreaseConfig
                                                        .builder()
                                                        .isProrated(true)
                                                        .build()
                                                )
                                                .subscriptionId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .scheduledChargesOnUsageInvoices(
                                    ContractCreateResponse.Data.Contract
                                        .ScheduledChargesOnUsageInvoices
                                        .ALL
                                )
                                .spendThresholdConfiguration(
                                    SpendThresholdConfiguration.builder()
                                        .commit(
                                            BaseThresholdCommit.builder()
                                                .productId("product_id")
                                                .description("description")
                                                .name("name")
                                                .priority(0.0)
                                                .build()
                                        )
                                        .isEnabled(true)
                                        .paymentGateConfig(
                                            PaymentGateConfig.builder()
                                                .paymentGateType(
                                                    PaymentGateConfig.PaymentGateType.NONE
                                                )
                                                .precalculatedTaxConfig(
                                                    PaymentGateConfig.PrecalculatedTaxConfig
                                                        .builder()
                                                        .taxAmount(0.0)
                                                        .taxName("tax_name")
                                                        .build()
                                                )
                                                .stripeConfig(
                                                    PaymentGateConfig.StripeConfig.builder()
                                                        .paymentType(
                                                            PaymentGateConfig.StripeConfig
                                                                .PaymentType
                                                                .INVOICE
                                                        )
                                                        .invoiceMetadata(
                                                            PaymentGateConfig.StripeConfig
                                                                .InvoiceMetadata
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "foo",
                                                                    JsonValue.from("string"),
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .taxType(PaymentGateConfig.TaxType.NONE)
                                                .build()
                                        )
                                        .thresholdAmount(0.0)
                                        .discountConfiguration(
                                            SpendThresholdConfiguration.DiscountConfiguration
                                                .builder()
                                                .paymentFraction(0.0)
                                                .cap(
                                                    SpendThresholdConfiguration
                                                        .DiscountConfiguration
                                                        .Cap
                                                        .builder()
                                                        .amount(0.0)
                                                        .spendTrackerAlias("spend_tracker_alias")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .addSubscription(
                                    Subscription.builder()
                                        .billingPeriods(
                                            Subscription.BillingPeriods.builder()
                                                .current(
                                                    Subscription.BillingPeriods.Current.builder()
                                                        .endingBefore(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .startingAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .next(
                                                    Subscription.BillingPeriods.Next.builder()
                                                        .endingBefore(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .startingAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .previous(
                                                    Subscription.BillingPeriods.Previous.builder()
                                                        .endingBefore(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .startingAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .collectionSchedule(Subscription.CollectionSchedule.ADVANCE)
                                        .proration(
                                            Subscription.Proration.builder()
                                                .invoiceBehavior(
                                                    Subscription.Proration.InvoiceBehavior
                                                        .BILL_IMMEDIATELY
                                                )
                                                .isProrated(true)
                                                .rounding(
                                                    Subscription.Proration.Rounding.builder()
                                                        .decimalPlaces(-5.0)
                                                        .roundingMethod(
                                                            Subscription.Proration.Rounding
                                                                .RoundingMethod
                                                                .HALF_UP
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .quantityManagementMode(
                                            Subscription.QuantityManagementMode.SEAT_BASED
                                        )
                                        .addQuantitySchedule(
                                            Subscription.QuantitySchedule.builder()
                                                .quantity(0.0)
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .subscriptionRate(
                                            Subscription.SubscriptionRate.builder()
                                                .billingFrequency(
                                                    Subscription.SubscriptionRate.BillingFrequency
                                                        .MONTHLY
                                                )
                                                .product(
                                                    Subscription.SubscriptionRate.Product.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .name("name")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .billingCycleConfig(
                                            Subscription.BillingCycleConfig.builder()
                                                .anchorDate(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .invoicePlacement(
                                                    Subscription.BillingCycleConfig.InvoicePlacement
                                                        .ON_SCHEDULED_INVOICE
                                                )
                                                .build()
                                        )
                                        .customFields(
                                            Subscription.CustomFields.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .description("description")
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .fiatCreditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .seatConfig(
                                            Subscription.SeatConfig.builder()
                                                .seatGroupKey("seat_group_key")
                                                .build()
                                        )
                                        .build()
                                )
                                .uniquenessKey("x")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedContractCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(contractCreateResponse),
                jacksonTypeRef<ContractCreateResponse>(),
            )

        assertThat(roundtrippedContractCreateResponse).isEqualTo(contractCreateResponse)
    }

    @Test
    fun contractListBalancesResponseRoundtrip() {
        val jsonMapper = jsonMapper()
        val contractListBalancesResponse =
            ContractListBalancesResponse.ofCommit(
                Commit.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .product(
                        Commit.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .type(Commit.Type.PREPAID)
                    .accessSchedule(
                        ScheduleDuration.builder()
                            .addScheduleItem(
                                ScheduleDuration.ScheduleItem.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .build()
                    )
                    .amount(0.0)
                    .addApplicableContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductTag("string")
                    .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .balance(0.0)
                    .contract(
                        Commit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
                    )
                    .costBasis(0.0)
                    .createdBy("created_by")
                    .customFields(
                        Commit.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .description("description")
                    .hierarchyConfiguration(
                        CommitHierarchyConfiguration.builder()
                            .childAccess(
                                CommitHierarchyConfiguration.ChildAccess
                                    .CommitHierarchyChildAccessAll
                                    .builder()
                                    .type(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .Type
                                            .ALL
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .invoiceContract(
                        Commit.InvoiceContract.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .invoiceSchedule(
                        SchedulePointInTime.builder()
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .doNotInvoice(true)
                            .addScheduleItem(
                                SchedulePointInTime.ScheduleItem.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .unitPrice(0.0)
                                    .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .build()
                    )
                    .addLedger(
                        Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                            .amount(0.0)
                            .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .type(
                                Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.Type
                                    .PREPAID_COMMIT_SEGMENT_START
                            )
                            .build()
                    )
                    .name("name")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .priority(0.0)
                    .rateType(Commit.RateType.COMMIT_RATE)
                    .recurringCommitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .rolledOverFrom(
                        Commit.RolledOverFrom.builder()
                            .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .rolloverFraction(0.0)
                    .salesforceOpportunityId("salesforce_opportunity_id")
                    .addSpecifier(
                        CommitSpecifier.builder()
                            .presentationGroupValues(
                                CommitSpecifier.PresentationGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .pricingGroupValues(
                                CommitSpecifier.PricingGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addProductTag("string")
                            .build()
                    )
                    .spendTrackerAttributes(
                        Commit.SpendTrackerAttributes.builder().countsAsDiscounted(true).build()
                    )
                    .subscriptionConfig(
                        Commit.SubscriptionConfig.builder()
                            .allocation(Commit.SubscriptionConfig.Allocation.INDIVIDUAL)
                            .applySeatIncreaseConfig(
                                Commit.SubscriptionConfig.ApplySeatIncreaseConfig.builder()
                                    .isProrated(true)
                                    .build()
                            )
                            .subscriptionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .uniquenessKey("x")
                    .build()
            )

        val roundtrippedContractListBalancesResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(contractListBalancesResponse),
                jacksonTypeRef<ContractListBalancesResponse>(),
            )

        assertThat(roundtrippedContractListBalancesResponse).isEqualTo(contractListBalancesResponse)
    }
}
