// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import com.metronome.api.core.JsonValue
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CommitTest {

    @Test
    fun createCommit() {
        val commit =
            Commit.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .product(
                    Commit.Product.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .name("name")
                        .build()
                )
                .type(Commit.Type.PREPAID)
                .accessSchedule(
                    ScheduleDuration.builder()
                        .scheduleItems(
                            listOf(
                                ScheduleDuration.ScheduleItem.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                        )
                        .creditType(
                            CreditTypeData.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .build()
                        )
                        .build()
                )
                .amount(0.0)
                .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .applicableProductTags(listOf("string"))
                .contract(
                    Commit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
                )
                .customFields(
                    Commit.CustomFields.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .description("description")
                .invoiceContract(
                    Commit.InvoiceContract.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .invoiceSchedule(
                    SchedulePointInTime.builder()
                        .creditType(
                            CreditTypeData.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .build()
                        )
                        .scheduleItems(
                            listOf(
                                SchedulePointInTime.ScheduleItem.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .amount(0.0)
                                    .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .quantity(0.0)
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .unitPrice(0.0)
                                    .build()
                            )
                        )
                        .build()
                )
                .ledger(
                    listOf(
                        Commit.Ledger.ofPrepaidCommitSegmentStartLedgerEntry(
                            Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                                .amount(0.0)
                                .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .type(
                                    Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.Type
                                        .PREPAID_COMMIT_SEGMENT_START
                                )
                                .build()
                        )
                    )
                )
                .name("name")
                .netsuiteSalesOrderId("netsuite_sales_order_id")
                .priority(0.0)
                .rateType(Commit.RateType.COMMIT_RATE)
                .rolledOverFrom(
                    Commit.RolledOverFrom.builder()
                        .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .rolloverFraction(0.0)
                .salesforceOpportunityId("salesforce_opportunity_id")
                .build()
        assertThat(commit).isNotNull
        assertThat(commit.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(commit.product())
            .isEqualTo(
                Commit.Product.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .name("name")
                    .build()
            )
        assertThat(commit.type()).isEqualTo(Commit.Type.PREPAID)
        assertThat(commit.accessSchedule())
            .contains(
                ScheduleDuration.builder()
                    .scheduleItems(
                        listOf(
                            ScheduleDuration.ScheduleItem.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .amount(0.0)
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                    )
                    .creditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .build()
            )
        assertThat(commit.amount()).contains(0.0)
        assertThat(commit.applicableContractIds().get())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(commit.applicableProductIds().get())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(commit.applicableProductTags().get()).containsExactly("string")
        assertThat(commit.contract())
            .contains(Commit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build())
        assertThat(commit.customFields())
            .contains(
                Commit.CustomFields.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(commit.description()).contains("description")
        assertThat(commit.invoiceContract())
            .contains(
                Commit.InvoiceContract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
            )
        assertThat(commit.invoiceSchedule())
            .contains(
                SchedulePointInTime.builder()
                    .creditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .scheduleItems(
                        listOf(
                            SchedulePointInTime.ScheduleItem.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .amount(0.0)
                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(0.0)
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .unitPrice(0.0)
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(commit.ledger().get())
            .containsExactly(
                Commit.Ledger.ofPrepaidCommitSegmentStartLedgerEntry(
                    Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                        .amount(0.0)
                        .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .type(
                            Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.Type
                                .PREPAID_COMMIT_SEGMENT_START
                        )
                        .build()
                )
            )
        assertThat(commit.name()).contains("name")
        assertThat(commit.netsuiteSalesOrderId()).contains("netsuite_sales_order_id")
        assertThat(commit.priority()).contains(0.0)
        assertThat(commit.rateType()).contains(Commit.RateType.COMMIT_RATE)
        assertThat(commit.rolledOverFrom())
            .contains(
                Commit.RolledOverFrom.builder()
                    .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
        assertThat(commit.rolloverFraction()).contains(0.0)
        assertThat(commit.salesforceOpportunityId()).contains("salesforce_opportunity_id")
    }
}
