// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CommitTest {

    @Test
    fun createCommit() {
        val commit =
            Commit.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .product(
                    Commit.Product.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .name("string")
                        .build()
                )
                .type(Commit.Type.PREPAID)
                .accessSchedule(
                    Commit.AccessSchedule.builder()
                        .scheduleItems(
                            listOf(
                                Commit.AccessSchedule.ScheduleItem.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .amount(42.23)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                        )
                        .creditType(
                            Commit.AccessSchedule.CreditType.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("string")
                                .build()
                        )
                        .build()
                )
                .amount(42.23)
                .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .applicableProductTags(listOf("string"))
                .contract(
                    Commit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
                )
                .customFields(Commit.CustomFields.builder().build())
                .description("string")
                .invoiceContract(
                    Commit.InvoiceContract.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .invoiceSchedule(
                    SchedulePointInTime.builder()
                        .scheduleItems(
                            listOf(
                                SchedulePointInTime.ScheduleItem.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .amount(42.23)
                                    .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .quantity(42.23)
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .unitPrice(42.23)
                                    .build()
                            )
                        )
                        .build()
                )
                .ledger(
                    listOf(
                        Commit.Ledger.ofPrepaidCommitSegmentStartLedgerEntry(
                            Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                                .amount(42.23)
                                .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .type(
                                    Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.Type
                                        .PREPAID_COMMIT_SEGMENT_START
                                )
                                .build()
                        )
                    )
                )
                .name("string")
                .netsuiteSalesOrderId("string")
                .priority(42.23)
                .rolledOverFrom(
                    Commit.RolledOverFrom.builder()
                        .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .rolloverFraction(42.23)
                .salesforceOpportunityId("string")
                .build()
        assertThat(commit).isNotNull
        assertThat(commit.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(commit.product())
            .isEqualTo(
                Commit.Product.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .name("string")
                    .build()
            )
        assertThat(commit.type()).isEqualTo(Commit.Type.PREPAID)
        assertThat(commit.accessSchedule())
            .contains(
                Commit.AccessSchedule.builder()
                    .scheduleItems(
                        listOf(
                            Commit.AccessSchedule.ScheduleItem.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .amount(42.23)
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                    )
                    .creditType(
                        Commit.AccessSchedule.CreditType.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .build()
            )
        assertThat(commit.amount()).contains(42.23)
        assertThat(commit.applicableContractIds().get())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(commit.applicableProductIds().get())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(commit.applicableProductTags().get()).containsExactly("string")
        assertThat(commit.contract())
            .contains(Commit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build())
        assertThat(commit.customFields()).contains(Commit.CustomFields.builder().build())
        assertThat(commit.description()).contains("string")
        assertThat(commit.invoiceContract())
            .contains(
                Commit.InvoiceContract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
            )
        assertThat(commit.invoiceSchedule())
            .contains(
                SchedulePointInTime.builder()
                    .scheduleItems(
                        listOf(
                            SchedulePointInTime.ScheduleItem.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .amount(42.23)
                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(42.23)
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .unitPrice(42.23)
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(commit.ledger().get())
            .containsExactly(
                Commit.Ledger.ofPrepaidCommitSegmentStartLedgerEntry(
                    Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                        .amount(42.23)
                        .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .type(
                            Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.Type
                                .PREPAID_COMMIT_SEGMENT_START
                        )
                        .build()
                )
            )
        assertThat(commit.name()).contains("string")
        assertThat(commit.netsuiteSalesOrderId()).contains("string")
        assertThat(commit.priority()).contains(42.23)
        assertThat(commit.rolledOverFrom())
            .contains(
                Commit.RolledOverFrom.builder()
                    .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
        assertThat(commit.rolloverFraction()).contains(42.23)
        assertThat(commit.salesforceOpportunityId()).contains("string")
    }
}
