// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import com.metronome.api.core.JsonValue
import java.time.OffsetDateTime
import kotlin.test.assertNotNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ContractAmendParamsTest {

    @Test
    fun create() {
        ContractAmendParams.builder()
            .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
            .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
            .startingAt(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
            .addCommit(
                ContractAmendParams.Commit.builder()
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .type(ContractAmendParams.Commit.Type.PREPAID)
                    .accessSchedule(
                        ContractAmendParams.Commit.AccessSchedule.builder()
                            .addScheduleItem(
                                ContractAmendParams.Commit.AccessSchedule.ScheduleItem.builder()
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .amount(0.0)
                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductTag("string")
                    .customFields(
                        ContractAmendParams.Commit.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .description("description")
                    .invoiceSchedule(
                        ContractAmendParams.Commit.InvoiceSchedule.builder()
                            .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .recurringSchedule(
                                ContractAmendParams.Commit.InvoiceSchedule.RecurringSchedule
                                    .builder()
                                    .amountDistribution(
                                        ContractAmendParams.Commit.InvoiceSchedule.RecurringSchedule
                                            .AmountDistribution
                                            .DIVIDED
                                    )
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .frequency(
                                        ContractAmendParams.Commit.InvoiceSchedule.RecurringSchedule
                                            .Frequency
                                            .MONTHLY
                                    )
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .addScheduleItem(
                                ContractAmendParams.Commit.InvoiceSchedule.ScheduleItem.builder()
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .name("x")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .priority(0.0)
                    .rateType(ContractAmendParams.Commit.RateType.COMMIT_RATE)
                    .rolloverFraction(0.0)
                    .temporaryId("temporary_id")
                    .build()
            )
            .addCredit(
                ContractAmendParams.Credit.builder()
                    .accessSchedule(
                        ContractAmendParams.Credit.AccessSchedule.builder()
                            .addScheduleItem(
                                ContractAmendParams.Credit.AccessSchedule.ScheduleItem.builder()
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductTag("string")
                    .customFields(
                        ContractAmendParams.Credit.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .description("description")
                    .name("x")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .priority(0.0)
                    .rateType(ContractAmendParams.Credit.RateType.COMMIT_RATE)
                    .build()
            )
            .customFields(
                ContractAmendParams.CustomFields.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
            .addDiscount(
                ContractAmendParams.Discount.builder()
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .schedule(
                        ContractAmendParams.Discount.Schedule.builder()
                            .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .recurringSchedule(
                                ContractAmendParams.Discount.Schedule.RecurringSchedule.builder()
                                    .amountDistribution(
                                        ContractAmendParams.Discount.Schedule.RecurringSchedule
                                            .AmountDistribution
                                            .DIVIDED
                                    )
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .frequency(
                                        ContractAmendParams.Discount.Schedule.RecurringSchedule
                                            .Frequency
                                            .MONTHLY
                                    )
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .addScheduleItem(
                                ContractAmendParams.Discount.Schedule.ScheduleItem.builder()
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .customFields(
                        ContractAmendParams.Discount.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .name("x")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .build()
            )
            .netsuiteSalesOrderId("netsuite_sales_order_id")
            .addOverride(
                ContractAmendParams.Override.builder()
                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addApplicableProductTag("string")
                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .entitled(true)
                    .isCommitSpecific(true)
                    .multiplier(0.0)
                    .addOverrideSpecifier(
                        ContractAmendParams.Override.OverrideSpecifier.builder()
                            .addCommitId("string")
                            .presentationGroupValues(
                                ContractAmendParams.Override.OverrideSpecifier
                                    .PresentationGroupValues
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .pricingGroupValues(
                                ContractAmendParams.Override.OverrideSpecifier.PricingGroupValues
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addProductTag("string")
                            .addRecurringCommitId("string")
                            .addRecurringCreditId("string")
                            .build()
                    )
                    .overwriteRate(
                        ContractAmendParams.Override.OverwriteRate.builder()
                            .rateType(ContractAmendParams.Override.OverwriteRate.RateType.FLAT)
                            .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .customRate(
                                ContractAmendParams.Override.OverwriteRate.CustomRate.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .isProrated(true)
                            .price(0.0)
                            .quantity(0.0)
                            .addTier(Tier.builder().price(0.0).size(0.0).build())
                            .build()
                    )
                    .priority(0.0)
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .target(ContractAmendParams.Override.Target.COMMIT_RATE)
                    .addTier(
                        ContractAmendParams.Override.Tier.builder()
                            .multiplier(0.0)
                            .size(0.0)
                            .build()
                    )
                    .type(ContractAmendParams.Override.Type.OVERWRITE)
                    .build()
            )
            .addProfessionalService(
                ContractAmendParams.ProfessionalService.builder()
                    .maxAmount(0.0)
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .quantity(0.0)
                    .unitPrice(0.0)
                    .customFields(
                        ContractAmendParams.ProfessionalService.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .description("description")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .build()
            )
            .addResellerRoyalty(
                ContractAmendParams.ResellerRoyalty.builder()
                    .resellerType(ContractAmendParams.ResellerRoyalty.ResellerType.AWS)
                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductTag("string")
                    .awsOptions(
                        ContractAmendParams.ResellerRoyalty.AwsOptions.builder()
                            .awsAccountNumber("aws_account_number")
                            .awsOfferId("aws_offer_id")
                            .awsPayerReferenceId("aws_payer_reference_id")
                            .build()
                    )
                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .fraction(0.0)
                    .gcpOptions(
                        ContractAmendParams.ResellerRoyalty.GcpOptions.builder()
                            .gcpAccountId("gcp_account_id")
                            .gcpOfferId("gcp_offer_id")
                            .build()
                    )
                    .netsuiteResellerId("netsuite_reseller_id")
                    .resellerContractValue(0.0)
                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
            .salesforceOpportunityId("salesforce_opportunity_id")
            .addScheduledCharge(
                ContractAmendParams.ScheduledCharge.builder()
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .schedule(
                        ContractAmendParams.ScheduledCharge.Schedule.builder()
                            .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .recurringSchedule(
                                ContractAmendParams.ScheduledCharge.Schedule.RecurringSchedule
                                    .builder()
                                    .amountDistribution(
                                        ContractAmendParams.ScheduledCharge.Schedule
                                            .RecurringSchedule
                                            .AmountDistribution
                                            .DIVIDED
                                    )
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .frequency(
                                        ContractAmendParams.ScheduledCharge.Schedule
                                            .RecurringSchedule
                                            .Frequency
                                            .MONTHLY
                                    )
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .addScheduleItem(
                                ContractAmendParams.ScheduledCharge.Schedule.ScheduleItem.builder()
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .name("x")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .build()
            )
            .totalContractValue(0.0)
            .build()
    }

    @Test
    fun body() {
        val params =
            ContractAmendParams.builder()
                .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                .startingAt(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                .addCommit(
                    ContractAmendParams.Commit.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .type(ContractAmendParams.Commit.Type.PREPAID)
                        .accessSchedule(
                            ContractAmendParams.Commit.AccessSchedule.builder()
                                .addScheduleItem(
                                    ContractAmendParams.Commit.AccessSchedule.ScheduleItem.builder()
                                        .amount(0.0)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .amount(0.0)
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .customFields(
                            ContractAmendParams.Commit.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .invoiceSchedule(
                            ContractAmendParams.Commit.InvoiceSchedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.Commit.InvoiceSchedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractAmendParams.Commit.InvoiceSchedule.ScheduleItem
                                        .builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractAmendParams.Commit.RateType.COMMIT_RATE)
                        .rolloverFraction(0.0)
                        .temporaryId("temporary_id")
                        .build()
                )
                .addCredit(
                    ContractAmendParams.Credit.builder()
                        .accessSchedule(
                            ContractAmendParams.Credit.AccessSchedule.builder()
                                .addScheduleItem(
                                    ContractAmendParams.Credit.AccessSchedule.ScheduleItem.builder()
                                        .amount(0.0)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .customFields(
                            ContractAmendParams.Credit.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractAmendParams.Credit.RateType.COMMIT_RATE)
                        .build()
                )
                .customFields(
                    ContractAmendParams.CustomFields.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .addDiscount(
                    ContractAmendParams.Discount.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractAmendParams.Discount.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.Discount.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractAmendParams.Discount.Schedule.ScheduleItem.builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .customFields(
                            ContractAmendParams.Discount.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
                .netsuiteSalesOrderId("netsuite_sales_order_id")
                .addOverride(
                    ContractAmendParams.Override.builder()
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addApplicableProductTag("string")
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .entitled(true)
                        .isCommitSpecific(true)
                        .multiplier(0.0)
                        .addOverrideSpecifier(
                            ContractAmendParams.Override.OverrideSpecifier.builder()
                                .addCommitId("string")
                                .presentationGroupValues(
                                    ContractAmendParams.Override.OverrideSpecifier
                                        .PresentationGroupValues
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    ContractAmendParams.Override.OverrideSpecifier
                                        .PricingGroupValues
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .addRecurringCommitId("string")
                                .addRecurringCreditId("string")
                                .build()
                        )
                        .overwriteRate(
                            ContractAmendParams.Override.OverwriteRate.builder()
                                .rateType(ContractAmendParams.Override.OverwriteRate.RateType.FLAT)
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customRate(
                                    ContractAmendParams.Override.OverwriteRate.CustomRate.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .isProrated(true)
                                .price(0.0)
                                .quantity(0.0)
                                .addTier(Tier.builder().price(0.0).size(0.0).build())
                                .build()
                        )
                        .priority(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .target(ContractAmendParams.Override.Target.COMMIT_RATE)
                        .addTier(
                            ContractAmendParams.Override.Tier.builder()
                                .multiplier(0.0)
                                .size(0.0)
                                .build()
                        )
                        .type(ContractAmendParams.Override.Type.OVERWRITE)
                        .build()
                )
                .addProfessionalService(
                    ContractAmendParams.ProfessionalService.builder()
                        .maxAmount(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .quantity(0.0)
                        .unitPrice(0.0)
                        .customFields(
                            ContractAmendParams.ProfessionalService.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
                .addResellerRoyalty(
                    ContractAmendParams.ResellerRoyalty.builder()
                        .resellerType(ContractAmendParams.ResellerRoyalty.ResellerType.AWS)
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .awsOptions(
                            ContractAmendParams.ResellerRoyalty.AwsOptions.builder()
                                .awsAccountNumber("aws_account_number")
                                .awsOfferId("aws_offer_id")
                                .awsPayerReferenceId("aws_payer_reference_id")
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .fraction(0.0)
                        .gcpOptions(
                            ContractAmendParams.ResellerRoyalty.GcpOptions.builder()
                                .gcpAccountId("gcp_account_id")
                                .gcpOfferId("gcp_offer_id")
                                .build()
                        )
                        .netsuiteResellerId("netsuite_reseller_id")
                        .resellerContractValue(0.0)
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .salesforceOpportunityId("salesforce_opportunity_id")
                .addScheduledCharge(
                    ContractAmendParams.ScheduledCharge.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractAmendParams.ScheduledCharge.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.ScheduledCharge.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractAmendParams.ScheduledCharge.Schedule.ScheduleItem
                                        .builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
                .totalContractValue(0.0)
                .build()

        val body = params._body()

        assertNotNull(body)
        assertThat(body.contractId()).isEqualTo("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
        assertThat(body.customerId()).isEqualTo("13117714-3f05-48e5-a6e9-a66093f13b4d")
        assertThat(body.startingAt()).isEqualTo(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
        assertThat(body.commits())
            .contains(
                listOf(
                    ContractAmendParams.Commit.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .type(ContractAmendParams.Commit.Type.PREPAID)
                        .accessSchedule(
                            ContractAmendParams.Commit.AccessSchedule.builder()
                                .addScheduleItem(
                                    ContractAmendParams.Commit.AccessSchedule.ScheduleItem.builder()
                                        .amount(0.0)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .amount(0.0)
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .customFields(
                            ContractAmendParams.Commit.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .invoiceSchedule(
                            ContractAmendParams.Commit.InvoiceSchedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.Commit.InvoiceSchedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractAmendParams.Commit.InvoiceSchedule.ScheduleItem
                                        .builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractAmendParams.Commit.RateType.COMMIT_RATE)
                        .rolloverFraction(0.0)
                        .temporaryId("temporary_id")
                        .build()
                )
            )
        assertThat(body.credits())
            .contains(
                listOf(
                    ContractAmendParams.Credit.builder()
                        .accessSchedule(
                            ContractAmendParams.Credit.AccessSchedule.builder()
                                .addScheduleItem(
                                    ContractAmendParams.Credit.AccessSchedule.ScheduleItem.builder()
                                        .amount(0.0)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .customFields(
                            ContractAmendParams.Credit.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractAmendParams.Credit.RateType.COMMIT_RATE)
                        .build()
                )
            )
        assertThat(body.customFields())
            .contains(
                ContractAmendParams.CustomFields.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(body.discounts())
            .contains(
                listOf(
                    ContractAmendParams.Discount.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractAmendParams.Discount.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.Discount.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractAmendParams.Discount.Schedule.ScheduleItem.builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .customFields(
                            ContractAmendParams.Discount.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
        assertThat(body.netsuiteSalesOrderId()).contains("netsuite_sales_order_id")
        assertThat(body.overrides())
            .contains(
                listOf(
                    ContractAmendParams.Override.builder()
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addApplicableProductTag("string")
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .entitled(true)
                        .isCommitSpecific(true)
                        .multiplier(0.0)
                        .addOverrideSpecifier(
                            ContractAmendParams.Override.OverrideSpecifier.builder()
                                .addCommitId("string")
                                .presentationGroupValues(
                                    ContractAmendParams.Override.OverrideSpecifier
                                        .PresentationGroupValues
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    ContractAmendParams.Override.OverrideSpecifier
                                        .PricingGroupValues
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .addRecurringCommitId("string")
                                .addRecurringCreditId("string")
                                .build()
                        )
                        .overwriteRate(
                            ContractAmendParams.Override.OverwriteRate.builder()
                                .rateType(ContractAmendParams.Override.OverwriteRate.RateType.FLAT)
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customRate(
                                    ContractAmendParams.Override.OverwriteRate.CustomRate.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .isProrated(true)
                                .price(0.0)
                                .quantity(0.0)
                                .addTier(Tier.builder().price(0.0).size(0.0).build())
                                .build()
                        )
                        .priority(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .target(ContractAmendParams.Override.Target.COMMIT_RATE)
                        .addTier(
                            ContractAmendParams.Override.Tier.builder()
                                .multiplier(0.0)
                                .size(0.0)
                                .build()
                        )
                        .type(ContractAmendParams.Override.Type.OVERWRITE)
                        .build()
                )
            )
        assertThat(body.professionalServices())
            .contains(
                listOf(
                    ContractAmendParams.ProfessionalService.builder()
                        .maxAmount(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .quantity(0.0)
                        .unitPrice(0.0)
                        .customFields(
                            ContractAmendParams.ProfessionalService.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
        assertThat(body.resellerRoyalties())
            .contains(
                listOf(
                    ContractAmendParams.ResellerRoyalty.builder()
                        .resellerType(ContractAmendParams.ResellerRoyalty.ResellerType.AWS)
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .awsOptions(
                            ContractAmendParams.ResellerRoyalty.AwsOptions.builder()
                                .awsAccountNumber("aws_account_number")
                                .awsOfferId("aws_offer_id")
                                .awsPayerReferenceId("aws_payer_reference_id")
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .fraction(0.0)
                        .gcpOptions(
                            ContractAmendParams.ResellerRoyalty.GcpOptions.builder()
                                .gcpAccountId("gcp_account_id")
                                .gcpOfferId("gcp_offer_id")
                                .build()
                        )
                        .netsuiteResellerId("netsuite_reseller_id")
                        .resellerContractValue(0.0)
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
            )
        assertThat(body.salesforceOpportunityId()).contains("salesforce_opportunity_id")
        assertThat(body.scheduledCharges())
            .contains(
                listOf(
                    ContractAmendParams.ScheduledCharge.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractAmendParams.ScheduledCharge.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.ScheduledCharge.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractAmendParams.ScheduledCharge.Schedule.ScheduleItem
                                        .builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
        assertThat(body.totalContractValue()).contains(0.0)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            ContractAmendParams.builder()
                .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                .startingAt(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                .build()

        val body = params._body()

        assertNotNull(body)
        assertThat(body.contractId()).isEqualTo("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
        assertThat(body.customerId()).isEqualTo("13117714-3f05-48e5-a6e9-a66093f13b4d")
        assertThat(body.startingAt()).isEqualTo(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
    }
}
