// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ContractScheduleProServicesInvoiceResponseTest {

    @Test
    fun createContractScheduleProServicesInvoiceResponse() {
        val contractScheduleProServicesInvoiceResponse =
            ContractScheduleProServicesInvoiceResponse.builder()
                .data(
                    listOf(
                        Invoice.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .lineItems(
                                listOf(
                                    Invoice.LineItem.builder()
                                        .creditType(
                                            CreditTypeData.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .name("name")
                                        .total(42.23)
                                        .appliedCommitOrCredit(
                                            Invoice.LineItem.AppliedCommitOrCredit.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .type(
                                                    Invoice.LineItem.AppliedCommitOrCredit.Type
                                                        .PREPAID
                                                )
                                                .build()
                                        )
                                        .commitCustomFields(
                                            Invoice.LineItem.CommitCustomFields.builder().build()
                                        )
                                        .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .commitNetsuiteItemId("commit_netsuite_item_id")
                                        .commitNetsuiteSalesOrderId(
                                            "commit_netsuite_sales_order_id"
                                        )
                                        .commitSegmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .commitType("commit_type")
                                        .customFields(
                                            Invoice.LineItem.CustomFields.builder().build()
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .groupKey("group_key")
                                        .groupValue("group_value")
                                        .isProrated(true)
                                        .listPrice(
                                            Rate.builder()
                                                .rateType(Rate.RateType.FLAT)
                                                .creditType(
                                                    CreditTypeData.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .name("name")
                                                        .build()
                                                )
                                                .customRate(Rate.CustomRate.builder().build())
                                                .isProrated(true)
                                                .price(42.23)
                                                .pricingGroupValues(
                                                    Rate.PricingGroupValues.builder().build()
                                                )
                                                .quantity(42.23)
                                                .tiers(
                                                    listOf(
                                                        Tier.builder()
                                                            .price(42.23)
                                                            .size(42.23)
                                                            .build()
                                                    )
                                                )
                                                .useListPrices(true)
                                                .build()
                                        )
                                        .metadata("metadata")
                                        .netsuiteInvoiceBillingEnd(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .netsuiteInvoiceBillingStart(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .netsuiteItemId("netsuite_item_id")
                                        .postpaidCommit(
                                            Invoice.LineItem.PostpaidCommit.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .build()
                                        )
                                        .presentationGroupValues(
                                            Invoice.LineItem.PresentationGroupValues.builder()
                                                .build()
                                        )
                                        .pricingGroupValues(
                                            Invoice.LineItem.PricingGroupValues.builder().build()
                                        )
                                        .productCustomFields(
                                            Invoice.LineItem.ProductCustomFields.builder().build()
                                        )
                                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .productType("product_type")
                                        .professionalServiceCustomFields(
                                            Invoice.LineItem.ProfessionalServiceCustomFields
                                                .builder()
                                                .build()
                                        )
                                        .professionalServiceId(
                                            "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                        )
                                        .quantity(42.23)
                                        .resellerType(Invoice.LineItem.ResellerType.AWS)
                                        .scheduledChargeCustomFields(
                                            Invoice.LineItem.ScheduledChargeCustomFields.builder()
                                                .build()
                                        )
                                        .scheduledChargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .subLineItems(
                                            listOf(
                                                Invoice.LineItem.SubLineItem.builder()
                                                    .customFields(
                                                        Invoice.LineItem.SubLineItem.CustomFields
                                                            .builder()
                                                            .build()
                                                    )
                                                    .name("name")
                                                    .quantity(42.23)
                                                    .subtotal(42.23)
                                                    .chargeId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .creditGrantId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .endDate(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .price(42.23)
                                                    .startDate(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .tierPeriod(
                                                        Invoice.LineItem.SubLineItem.TierPeriod
                                                            .builder()
                                                            .startingAt(
                                                                OffsetDateTime.parse(
                                                                    "2019-12-27T18:11:19.117Z"
                                                                )
                                                            )
                                                            .endingBefore(
                                                                OffsetDateTime.parse(
                                                                    "2019-12-27T18:11:19.117Z"
                                                                )
                                                            )
                                                            .build()
                                                    )
                                                    .tiers(
                                                        listOf(
                                                            Invoice.LineItem.SubLineItem.Tier
                                                                .builder()
                                                                .price(42.23)
                                                                .quantity(42.23)
                                                                .startingAt(42.23)
                                                                .subtotal(42.23)
                                                                .build()
                                                        )
                                                    )
                                                    .build()
                                            )
                                        )
                                        .unitPrice(42.23)
                                        .build()
                                )
                            )
                            .status("DRAFT, VOID, or FINALIZED")
                            .total(42.23)
                            .type(
                                "PLAN_ARREARS, SCHEDULED, USAGE, CORRECTION, CREDIT_PURCHASE, or SEAT_PURCHASE"
                            )
                            .amendmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .billableStatus(Invoice.BillableStatus.BILLABLE)
                            .contractCustomFields(Invoice.ContractCustomFields.builder().build())
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .correctionRecord(
                                Invoice.CorrectionRecord.builder()
                                    .correctedInvoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .memo("memo")
                                    .reason("reason")
                                    .correctedExternalInvoice(
                                        Invoice.CorrectionRecord.CorrectedExternalInvoice.builder()
                                            .billingProviderType(
                                                Invoice.CorrectionRecord.CorrectedExternalInvoice
                                                    .BillingProviderType
                                                    .AWS_MARKETPLACE
                                            )
                                            .externalStatus(
                                                Invoice.CorrectionRecord.CorrectedExternalInvoice
                                                    .ExternalStatus
                                                    .DRAFT
                                            )
                                            .invoiceId("invoice_id")
                                            .issuedAtTimestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .customFields(Invoice.CustomFields.builder().build())
                            .customerCustomFields(Invoice.CustomerCustomFields.builder().build())
                            .endTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .externalInvoice(
                                Invoice.ExternalInvoice.builder()
                                    .billingProviderType(
                                        Invoice.ExternalInvoice.BillingProviderType.AWS_MARKETPLACE
                                    )
                                    .externalStatus(Invoice.ExternalInvoice.ExternalStatus.DRAFT)
                                    .invoiceId("invoice_id")
                                    .issuedAtTimestamp(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .build()
                            )
                            .invoiceAdjustments(
                                listOf(
                                    Invoice.InvoiceAdjustment.builder()
                                        .creditType(
                                            CreditTypeData.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .name("Monthly minimum (\$1,000)")
                                        .total(42.23)
                                        .creditGrantCustomFields(
                                            Invoice.InvoiceAdjustment.CreditGrantCustomFields
                                                .builder()
                                                .build()
                                        )
                                        .creditGrantId("credit_grant_id")
                                        .build()
                                )
                            )
                            .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .netPaymentTermsDays(42.23)
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .planCustomFields(Invoice.PlanCustomFields.builder().build())
                            .planId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .planName("plan_name")
                            .resellerRoyalty(
                                Invoice.ResellerRoyalty.builder()
                                    .fraction("fraction")
                                    .netsuiteResellerId("netsuite_reseller_id")
                                    .resellerType(Invoice.ResellerRoyalty.ResellerType.AWS)
                                    .awsOptions(
                                        Invoice.ResellerRoyalty.AwsOptions.builder()
                                            .awsAccountNumber("aws_account_number")
                                            .awsOfferId("aws_offer_id")
                                            .awsPayerReferenceId("aws_payer_reference_id")
                                            .build()
                                    )
                                    .gcpOptions(
                                        Invoice.ResellerRoyalty.GcpOptions.builder()
                                            .gcpAccountId("gcp_account_id")
                                            .gcpOfferId("gcp_offer_id")
                                            .build()
                                    )
                                    .build()
                            )
                            .salesforceOpportunityId("salesforce_opportunity_id")
                            .startTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .subtotal(42.23)
                            .build()
                    )
                )
                .build()
        assertThat(contractScheduleProServicesInvoiceResponse).isNotNull
        assertThat(contractScheduleProServicesInvoiceResponse.data())
            .containsExactly(
                Invoice.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .creditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .lineItems(
                        listOf(
                            Invoice.LineItem.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .name("name")
                                .total(42.23)
                                .appliedCommitOrCredit(
                                    Invoice.LineItem.AppliedCommitOrCredit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .type(Invoice.LineItem.AppliedCommitOrCredit.Type.PREPAID)
                                        .build()
                                )
                                .commitCustomFields(
                                    Invoice.LineItem.CommitCustomFields.builder().build()
                                )
                                .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .commitNetsuiteItemId("commit_netsuite_item_id")
                                .commitNetsuiteSalesOrderId("commit_netsuite_sales_order_id")
                                .commitSegmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .commitType("commit_type")
                                .customFields(Invoice.LineItem.CustomFields.builder().build())
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .groupKey("group_key")
                                .groupValue("group_value")
                                .isProrated(true)
                                .listPrice(
                                    Rate.builder()
                                        .rateType(Rate.RateType.FLAT)
                                        .creditType(
                                            CreditTypeData.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .customRate(Rate.CustomRate.builder().build())
                                        .isProrated(true)
                                        .price(42.23)
                                        .pricingGroupValues(
                                            Rate.PricingGroupValues.builder().build()
                                        )
                                        .quantity(42.23)
                                        .tiers(
                                            listOf(Tier.builder().price(42.23).size(42.23).build())
                                        )
                                        .useListPrices(true)
                                        .build()
                                )
                                .metadata("metadata")
                                .netsuiteInvoiceBillingEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteInvoiceBillingStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteItemId("netsuite_item_id")
                                .postpaidCommit(
                                    Invoice.LineItem.PostpaidCommit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .presentationGroupValues(
                                    Invoice.LineItem.PresentationGroupValues.builder().build()
                                )
                                .pricingGroupValues(
                                    Invoice.LineItem.PricingGroupValues.builder().build()
                                )
                                .productCustomFields(
                                    Invoice.LineItem.ProductCustomFields.builder().build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .productType("product_type")
                                .professionalServiceCustomFields(
                                    Invoice.LineItem.ProfessionalServiceCustomFields.builder()
                                        .build()
                                )
                                .professionalServiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(42.23)
                                .resellerType(Invoice.LineItem.ResellerType.AWS)
                                .scheduledChargeCustomFields(
                                    Invoice.LineItem.ScheduledChargeCustomFields.builder().build()
                                )
                                .scheduledChargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .subLineItems(
                                    listOf(
                                        Invoice.LineItem.SubLineItem.builder()
                                            .customFields(
                                                Invoice.LineItem.SubLineItem.CustomFields.builder()
                                                    .build()
                                            )
                                            .name("name")
                                            .quantity(42.23)
                                            .subtotal(42.23)
                                            .chargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .endDate(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .price(42.23)
                                            .startDate(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .tierPeriod(
                                                Invoice.LineItem.SubLineItem.TierPeriod.builder()
                                                    .startingAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .endingBefore(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .build()
                                            )
                                            .tiers(
                                                listOf(
                                                    Invoice.LineItem.SubLineItem.Tier.builder()
                                                        .price(42.23)
                                                        .quantity(42.23)
                                                        .startingAt(42.23)
                                                        .subtotal(42.23)
                                                        .build()
                                                )
                                            )
                                            .build()
                                    )
                                )
                                .unitPrice(42.23)
                                .build()
                        )
                    )
                    .status("DRAFT, VOID, or FINALIZED")
                    .total(42.23)
                    .type(
                        "PLAN_ARREARS, SCHEDULED, USAGE, CORRECTION, CREDIT_PURCHASE, or SEAT_PURCHASE"
                    )
                    .amendmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .billableStatus(Invoice.BillableStatus.BILLABLE)
                    .contractCustomFields(Invoice.ContractCustomFields.builder().build())
                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .correctionRecord(
                        Invoice.CorrectionRecord.builder()
                            .correctedInvoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .memo("memo")
                            .reason("reason")
                            .correctedExternalInvoice(
                                Invoice.CorrectionRecord.CorrectedExternalInvoice.builder()
                                    .billingProviderType(
                                        Invoice.CorrectionRecord.CorrectedExternalInvoice
                                            .BillingProviderType
                                            .AWS_MARKETPLACE
                                    )
                                    .externalStatus(
                                        Invoice.CorrectionRecord.CorrectedExternalInvoice
                                            .ExternalStatus
                                            .DRAFT
                                    )
                                    .invoiceId("invoice_id")
                                    .issuedAtTimestamp(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .customFields(Invoice.CustomFields.builder().build())
                    .customerCustomFields(Invoice.CustomerCustomFields.builder().build())
                    .endTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .externalInvoice(
                        Invoice.ExternalInvoice.builder()
                            .billingProviderType(
                                Invoice.ExternalInvoice.BillingProviderType.AWS_MARKETPLACE
                            )
                            .externalStatus(Invoice.ExternalInvoice.ExternalStatus.DRAFT)
                            .invoiceId("invoice_id")
                            .issuedAtTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .invoiceAdjustments(
                        listOf(
                            Invoice.InvoiceAdjustment.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .name("Monthly minimum (\$1,000)")
                                .total(42.23)
                                .creditGrantCustomFields(
                                    Invoice.InvoiceAdjustment.CreditGrantCustomFields.builder()
                                        .build()
                                )
                                .creditGrantId("credit_grant_id")
                                .build()
                        )
                    )
                    .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .netPaymentTermsDays(42.23)
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .planCustomFields(Invoice.PlanCustomFields.builder().build())
                    .planId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .planName("plan_name")
                    .resellerRoyalty(
                        Invoice.ResellerRoyalty.builder()
                            .fraction("fraction")
                            .netsuiteResellerId("netsuite_reseller_id")
                            .resellerType(Invoice.ResellerRoyalty.ResellerType.AWS)
                            .awsOptions(
                                Invoice.ResellerRoyalty.AwsOptions.builder()
                                    .awsAccountNumber("aws_account_number")
                                    .awsOfferId("aws_offer_id")
                                    .awsPayerReferenceId("aws_payer_reference_id")
                                    .build()
                            )
                            .gcpOptions(
                                Invoice.ResellerRoyalty.GcpOptions.builder()
                                    .gcpAccountId("gcp_account_id")
                                    .gcpOfferId("gcp_offer_id")
                                    .build()
                            )
                            .build()
                    )
                    .salesforceOpportunityId("salesforce_opportunity_id")
                    .startTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .subtotal(42.23)
                    .build()
            )
    }
}
