// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import com.metronome.api.core.JsonValue
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ContractCreateHistoricalInvoicesParamsTest {

    @Test
    fun createContractCreateHistoricalInvoicesParams() {
        ContractCreateHistoricalInvoicesParams.builder()
            .invoices(
                listOf(
                    ContractCreateHistoricalInvoicesParams.Invoice.builder()
                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .exclusiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .inclusiveStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .usageLineItems(
                            listOf(
                                ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                    .builder()
                                    .exclusiveEndDate(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .inclusiveStartDate(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .presentationGroupValues(
                                        ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                            .PresentationGroupValues
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                            .PricingGroupValues
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .quantity(0.0)
                                    .subtotalsWithQuantity(
                                        listOf(
                                            ContractCreateHistoricalInvoicesParams.Invoice
                                                .UsageLineItem
                                                .SubtotalsWithQuantity
                                                .builder()
                                                .exclusiveEndDate(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .inclusiveStartDate(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .quantity(0.0)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                        )
                        .billableStatus(
                            ContractCreateHistoricalInvoicesParams.Invoice.BillableStatus.BILLABLE
                        )
                        .breakdownGranularity(
                            ContractCreateHistoricalInvoicesParams.Invoice.BreakdownGranularity.HOUR
                        )
                        .customFields(
                            ContractCreateHistoricalInvoicesParams.Invoice.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .build()
                )
            )
            .preview(true)
            .build()
    }

    @Test
    fun getBody() {
        val params =
            ContractCreateHistoricalInvoicesParams.builder()
                .invoices(
                    listOf(
                        ContractCreateHistoricalInvoicesParams.Invoice.builder()
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .exclusiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .inclusiveStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .issueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .usageLineItems(
                                listOf(
                                    ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                        .builder()
                                        .exclusiveEndDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .inclusiveStartDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .presentationGroupValues(
                                            ContractCreateHistoricalInvoicesParams.Invoice
                                                .UsageLineItem
                                                .PresentationGroupValues
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string")
                                                )
                                                .build()
                                        )
                                        .pricingGroupValues(
                                            ContractCreateHistoricalInvoicesParams.Invoice
                                                .UsageLineItem
                                                .PricingGroupValues
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string")
                                                )
                                                .build()
                                        )
                                        .quantity(0.0)
                                        .subtotalsWithQuantity(
                                            listOf(
                                                ContractCreateHistoricalInvoicesParams.Invoice
                                                    .UsageLineItem
                                                    .SubtotalsWithQuantity
                                                    .builder()
                                                    .exclusiveEndDate(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .inclusiveStartDate(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .quantity(0.0)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                            )
                            .billableStatus(
                                ContractCreateHistoricalInvoicesParams.Invoice.BillableStatus
                                    .BILLABLE
                            )
                            .breakdownGranularity(
                                ContractCreateHistoricalInvoicesParams.Invoice.BreakdownGranularity
                                    .HOUR
                            )
                            .customFields(
                                ContractCreateHistoricalInvoicesParams.Invoice.CustomFields
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                )
                .preview(true)
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.invoices())
            .isEqualTo(
                listOf(
                    ContractCreateHistoricalInvoicesParams.Invoice.builder()
                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .exclusiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .inclusiveStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .usageLineItems(
                            listOf(
                                ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                    .builder()
                                    .exclusiveEndDate(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .inclusiveStartDate(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .presentationGroupValues(
                                        ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                            .PresentationGroupValues
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                            .PricingGroupValues
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .quantity(0.0)
                                    .subtotalsWithQuantity(
                                        listOf(
                                            ContractCreateHistoricalInvoicesParams.Invoice
                                                .UsageLineItem
                                                .SubtotalsWithQuantity
                                                .builder()
                                                .exclusiveEndDate(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .inclusiveStartDate(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .quantity(0.0)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                        )
                        .billableStatus(
                            ContractCreateHistoricalInvoicesParams.Invoice.BillableStatus.BILLABLE
                        )
                        .breakdownGranularity(
                            ContractCreateHistoricalInvoicesParams.Invoice.BreakdownGranularity.HOUR
                        )
                        .customFields(
                            ContractCreateHistoricalInvoicesParams.Invoice.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .build()
                )
            )
        assertThat(body.preview()).isEqualTo(true)
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            ContractCreateHistoricalInvoicesParams.builder()
                .invoices(
                    listOf(
                        ContractCreateHistoricalInvoicesParams.Invoice.builder()
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .exclusiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .inclusiveStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .issueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .usageLineItems(
                                listOf(
                                    ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                        .builder()
                                        .exclusiveEndDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .inclusiveStartDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                            )
                            .build()
                    )
                )
                .preview(true)
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.invoices())
            .isEqualTo(
                listOf(
                    ContractCreateHistoricalInvoicesParams.Invoice.builder()
                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .exclusiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .inclusiveStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .usageLineItems(
                            listOf(
                                ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                    .builder()
                                    .exclusiveEndDate(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .inclusiveStartDate(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                        )
                        .build()
                )
            )
        assertThat(body.preview()).isEqualTo(true)
    }
}
