// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ContractWithoutAmendmentsTest {

    @Test
    fun createContractWithoutAmendments() {
        val contractWithoutAmendments =
            ContractWithoutAmendments.builder()
                .commits(
                    listOf(
                        Commit.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .product(
                                Commit.Product.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .type(Commit.Type.PREPAID)
                            .accessSchedule(
                                Commit.AccessSchedule.builder()
                                    .scheduleItems(
                                        listOf(
                                            Commit.AccessSchedule.ScheduleItem.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .amount(42.23)
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                    )
                                    .creditType(
                                        Commit.AccessSchedule.CreditType.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("string")
                                            .build()
                                    )
                                    .build()
                            )
                            .amount(42.23)
                            .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductTags(listOf("string"))
                            .contract(
                                Commit.Contract.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .customFields(Commit.CustomFields.builder().build())
                            .description("string")
                            .invoiceContract(
                                Commit.InvoiceContract.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .invoiceSchedule(
                                SchedulePointInTime.builder()
                                    .scheduleItems(
                                        listOf(
                                            SchedulePointInTime.ScheduleItem.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .amount(42.23)
                                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .quantity(42.23)
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .unitPrice(42.23)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .ledger(
                                listOf(
                                    Commit.Ledger.ofPrepaidCommitSegmentStartLedgerEntry(
                                        Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                                            .amount(42.23)
                                            .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .type(
                                                Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry
                                                    .Type
                                                    .PREPAID_COMMIT_SEGMENT_START
                                            )
                                            .build()
                                    )
                                )
                            )
                            .name("string")
                            .netsuiteSalesOrderId("string")
                            .priority(42.23)
                            .rolledOverFrom(
                                Commit.RolledOverFrom.builder()
                                    .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .rolloverFraction(42.23)
                            .salesforceOpportunityId("string")
                            .build()
                    )
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("string")
                .overrides(
                    listOf(
                        Override.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .applicableProductTags(listOf("string"))
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .entitled(true)
                            .multiplier(42.23)
                            .overrideSpecifiers(
                                listOf(
                                    Override.OverrideSpecifier.builder()
                                        .presentationGroupValues(
                                            Override.OverrideSpecifier.PresentationGroupValues
                                                .builder()
                                                .build()
                                        )
                                        .pricingGroupValues(
                                            Override.OverrideSpecifier.PricingGroupValues.builder()
                                                .build()
                                        )
                                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .productTags(listOf("string"))
                                        .build()
                                )
                            )
                            .overwriteRate(
                                Override.OverwriteRate.builder()
                                    .rateType(Override.OverwriteRate.RateType.FLAT)
                                    .customRate(Override.OverwriteRate.CustomRate.builder().build())
                                    .isProrated(true)
                                    .price(42.23)
                                    .quantity(42.23)
                                    .tiers(
                                        listOf(
                                            Override.OverwriteRate.Tier.builder()
                                                .price(42.23)
                                                .size(42.23)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .product(
                                Override.Product.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .type(Override.Type.OVERWRITE)
                            .build()
                    )
                )
                .scheduledCharges(
                    listOf(
                        ScheduledCharge.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .product(
                                ScheduledCharge.Product.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .schedule(
                                SchedulePointInTime.builder()
                                    .scheduleItems(
                                        listOf(
                                            SchedulePointInTime.ScheduleItem.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .amount(42.23)
                                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .quantity(42.23)
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .unitPrice(42.23)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .customFields(ScheduledCharge.CustomFields.builder().build())
                            .name("x")
                            .netsuiteSalesOrderId("string")
                            .build()
                    )
                )
                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .transitions(
                    listOf(
                        ContractWithoutAmendments.Transition.builder()
                            .fromContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .toContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .type(ContractWithoutAmendments.Transition.Type.SUPERSEDE)
                            .build()
                    )
                )
                .usageStatementSchedule(
                    ContractWithoutAmendments.UsageStatementSchedule.builder()
                        .frequency(
                            ContractWithoutAmendments.UsageStatementSchedule.Frequency.MONTHLY
                        )
                        .build()
                )
                .credits(
                    listOf(
                        ContractWithoutAmendments.Credit.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .product(
                                ContractWithoutAmendments.Credit.Product.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .type(ContractWithoutAmendments.Credit.Type.CREDIT)
                            .accessSchedule(
                                ContractWithoutAmendments.Credit.AccessSchedule.builder()
                                    .scheduleItems(
                                        listOf(
                                            ContractWithoutAmendments.Credit.AccessSchedule
                                                .ScheduleItem
                                                .builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .amount(42.23)
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                    )
                                    .creditType(
                                        ContractWithoutAmendments.Credit.AccessSchedule.CreditType
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("string")
                                            .build()
                                    )
                                    .build()
                            )
                            .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductTags(listOf("string"))
                            .contract(
                                ContractWithoutAmendments.Credit.Contract.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .customFields(
                                ContractWithoutAmendments.Credit.CustomFields.builder().build()
                            )
                            .description("string")
                            .ledger(
                                listOf(
                                    ContractWithoutAmendments.Credit.Ledger
                                        .ofCreditSegmentStartLedgerEntry(
                                            ContractWithoutAmendments.Credit.Ledger
                                                .CreditSegmentStartLedgerEntry
                                                .builder()
                                                .amount(42.23)
                                                .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .type(
                                                    ContractWithoutAmendments.Credit.Ledger
                                                        .CreditSegmentStartLedgerEntry
                                                        .Type
                                                        .CREDIT_SEGMENT_START
                                                )
                                                .build()
                                        )
                                )
                            )
                            .name("string")
                            .netsuiteSalesOrderId("string")
                            .priority(42.23)
                            .salesforceOpportunityId("string")
                            .build()
                    )
                )
                .discounts(
                    listOf(
                        Discount.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .product(
                                Discount.Product.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .schedule(
                                SchedulePointInTime.builder()
                                    .scheduleItems(
                                        listOf(
                                            SchedulePointInTime.ScheduleItem.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .amount(42.23)
                                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .quantity(42.23)
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .unitPrice(42.23)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("string")
                            .build()
                    )
                )
                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .name("string")
                .netPaymentTermsDays(42.23)
                .netsuiteSalesOrderId("string")
                .professionalServices(
                    listOf(
                        ContractWithoutAmendments.ProfessionalService.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .maxAmount(42.23)
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .quantity(42.23)
                            .unitPrice(42.23)
                            .customFields(
                                ContractWithoutAmendments.ProfessionalService.CustomFields.builder()
                                    .build()
                            )
                            .description("string")
                            .netsuiteSalesOrderId("string")
                            .build()
                    )
                )
                .rateCardId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .resellerRoyalties(
                    listOf(
                        ContractWithoutAmendments.ResellerRoyalty.builder()
                            .fraction(42.23)
                            .netsuiteResellerId("string")
                            .resellerType(
                                ContractWithoutAmendments.ResellerRoyalty.ResellerType.AWS
                            )
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .applicableProductIds(listOf("string"))
                            .applicableProductTags(listOf("string"))
                            .awsAccountNumber("string")
                            .awsOfferId("string")
                            .awsPayerReferenceId("string")
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .gcpAccountId("string")
                            .gcpOfferId("string")
                            .resellerContractValue(42.23)
                            .build()
                    )
                )
                .salesforceOpportunityId("string")
                .totalContractValue(42.23)
                .usageFilter(
                    ContractWithoutAmendments.UsageFilter.builder()
                        .current(
                            ContractWithoutAmendments.UsageFilter.Current.builder()
                                .groupKey("string")
                                .groupValues(listOf("string"))
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .initial(
                            ContractWithoutAmendments.UsageFilter.Initial.builder()
                                .groupKey("string")
                                .groupValues(listOf("string"))
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .updates(
                            listOf(
                                ContractWithoutAmendments.UsageFilter.Update.builder()
                                    .groupKey("string")
                                    .groupValues(listOf("string"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                        )
                        .build()
                )
                .build()
        assertThat(contractWithoutAmendments).isNotNull
        assertThat(contractWithoutAmendments.commits())
            .containsExactly(
                Commit.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .product(
                        Commit.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .type(Commit.Type.PREPAID)
                    .accessSchedule(
                        Commit.AccessSchedule.builder()
                            .scheduleItems(
                                listOf(
                                    Commit.AccessSchedule.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(42.23)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                            )
                            .creditType(
                                Commit.AccessSchedule.CreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .build()
                    )
                    .amount(42.23)
                    .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                    .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                    .applicableProductTags(listOf("string"))
                    .contract(
                        Commit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
                    )
                    .customFields(Commit.CustomFields.builder().build())
                    .description("string")
                    .invoiceContract(
                        Commit.InvoiceContract.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .invoiceSchedule(
                        SchedulePointInTime.builder()
                            .scheduleItems(
                                listOf(
                                    SchedulePointInTime.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(42.23)
                                        .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .quantity(42.23)
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .unitPrice(42.23)
                                        .build()
                                )
                            )
                            .build()
                    )
                    .ledger(
                        listOf(
                            Commit.Ledger.ofPrepaidCommitSegmentStartLedgerEntry(
                                Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                                    .amount(42.23)
                                    .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .type(
                                        Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.Type
                                            .PREPAID_COMMIT_SEGMENT_START
                                    )
                                    .build()
                            )
                        )
                    )
                    .name("string")
                    .netsuiteSalesOrderId("string")
                    .priority(42.23)
                    .rolledOverFrom(
                        Commit.RolledOverFrom.builder()
                            .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .rolloverFraction(42.23)
                    .salesforceOpportunityId("string")
                    .build()
            )
        assertThat(contractWithoutAmendments.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(contractWithoutAmendments.createdBy()).isEqualTo("string")
        assertThat(contractWithoutAmendments.overrides())
            .containsExactly(
                Override.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .applicableProductTags(listOf("string"))
                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .entitled(true)
                    .multiplier(42.23)
                    .overrideSpecifiers(
                        listOf(
                            Override.OverrideSpecifier.builder()
                                .presentationGroupValues(
                                    Override.OverrideSpecifier.PresentationGroupValues.builder()
                                        .build()
                                )
                                .pricingGroupValues(
                                    Override.OverrideSpecifier.PricingGroupValues.builder().build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .productTags(listOf("string"))
                                .build()
                        )
                    )
                    .overwriteRate(
                        Override.OverwriteRate.builder()
                            .rateType(Override.OverwriteRate.RateType.FLAT)
                            .customRate(Override.OverwriteRate.CustomRate.builder().build())
                            .isProrated(true)
                            .price(42.23)
                            .quantity(42.23)
                            .tiers(
                                listOf(
                                    Override.OverwriteRate.Tier.builder()
                                        .price(42.23)
                                        .size(42.23)
                                        .build()
                                )
                            )
                            .build()
                    )
                    .product(
                        Override.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .type(Override.Type.OVERWRITE)
                    .build()
            )
        assertThat(contractWithoutAmendments.scheduledCharges())
            .containsExactly(
                ScheduledCharge.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .product(
                        ScheduledCharge.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .schedule(
                        SchedulePointInTime.builder()
                            .scheduleItems(
                                listOf(
                                    SchedulePointInTime.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(42.23)
                                        .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .quantity(42.23)
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .unitPrice(42.23)
                                        .build()
                                )
                            )
                            .build()
                    )
                    .customFields(ScheduledCharge.CustomFields.builder().build())
                    .name("x")
                    .netsuiteSalesOrderId("string")
                    .build()
            )
        assertThat(contractWithoutAmendments.startingAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(contractWithoutAmendments.transitions())
            .containsExactly(
                ContractWithoutAmendments.Transition.builder()
                    .fromContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .toContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .type(ContractWithoutAmendments.Transition.Type.SUPERSEDE)
                    .build()
            )
        assertThat(contractWithoutAmendments.usageStatementSchedule())
            .isEqualTo(
                ContractWithoutAmendments.UsageStatementSchedule.builder()
                    .frequency(ContractWithoutAmendments.UsageStatementSchedule.Frequency.MONTHLY)
                    .build()
            )
        assertThat(contractWithoutAmendments.credits().get())
            .containsExactly(
                ContractWithoutAmendments.Credit.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .product(
                        ContractWithoutAmendments.Credit.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .type(ContractWithoutAmendments.Credit.Type.CREDIT)
                    .accessSchedule(
                        ContractWithoutAmendments.Credit.AccessSchedule.builder()
                            .scheduleItems(
                                listOf(
                                    ContractWithoutAmendments.Credit.AccessSchedule.ScheduleItem
                                        .builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(42.23)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                            )
                            .creditType(
                                ContractWithoutAmendments.Credit.AccessSchedule.CreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .build()
                    )
                    .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                    .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                    .applicableProductTags(listOf("string"))
                    .contract(
                        ContractWithoutAmendments.Credit.Contract.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .customFields(ContractWithoutAmendments.Credit.CustomFields.builder().build())
                    .description("string")
                    .ledger(
                        listOf(
                            ContractWithoutAmendments.Credit.Ledger.ofCreditSegmentStartLedgerEntry(
                                ContractWithoutAmendments.Credit.Ledger
                                    .CreditSegmentStartLedgerEntry
                                    .builder()
                                    .amount(42.23)
                                    .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .type(
                                        ContractWithoutAmendments.Credit.Ledger
                                            .CreditSegmentStartLedgerEntry
                                            .Type
                                            .CREDIT_SEGMENT_START
                                    )
                                    .build()
                            )
                        )
                    )
                    .name("string")
                    .netsuiteSalesOrderId("string")
                    .priority(42.23)
                    .salesforceOpportunityId("string")
                    .build()
            )
        assertThat(contractWithoutAmendments.discounts().get())
            .containsExactly(
                Discount.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .product(
                        Discount.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .schedule(
                        SchedulePointInTime.builder()
                            .scheduleItems(
                                listOf(
                                    SchedulePointInTime.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(42.23)
                                        .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .quantity(42.23)
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .unitPrice(42.23)
                                        .build()
                                )
                            )
                            .build()
                    )
                    .name("x")
                    .netsuiteSalesOrderId("string")
                    .build()
            )
        assertThat(contractWithoutAmendments.endingBefore())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(contractWithoutAmendments.name()).contains("string")
        assertThat(contractWithoutAmendments.netPaymentTermsDays()).contains(42.23)
        assertThat(contractWithoutAmendments.netsuiteSalesOrderId()).contains("string")
        assertThat(contractWithoutAmendments.professionalServices().get())
            .containsExactly(
                ContractWithoutAmendments.ProfessionalService.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .maxAmount(42.23)
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .quantity(42.23)
                    .unitPrice(42.23)
                    .customFields(
                        ContractWithoutAmendments.ProfessionalService.CustomFields.builder().build()
                    )
                    .description("string")
                    .netsuiteSalesOrderId("string")
                    .build()
            )
        assertThat(contractWithoutAmendments.rateCardId())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(contractWithoutAmendments.resellerRoyalties().get())
            .containsExactly(
                ContractWithoutAmendments.ResellerRoyalty.builder()
                    .fraction(42.23)
                    .netsuiteResellerId("string")
                    .resellerType(ContractWithoutAmendments.ResellerRoyalty.ResellerType.AWS)
                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .applicableProductIds(listOf("string"))
                    .applicableProductTags(listOf("string"))
                    .awsAccountNumber("string")
                    .awsOfferId("string")
                    .awsPayerReferenceId("string")
                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .gcpAccountId("string")
                    .gcpOfferId("string")
                    .resellerContractValue(42.23)
                    .build()
            )
        assertThat(contractWithoutAmendments.salesforceOpportunityId()).contains("string")
        assertThat(contractWithoutAmendments.totalContractValue()).contains(42.23)
        assertThat(contractWithoutAmendments.usageFilter())
            .contains(
                ContractWithoutAmendments.UsageFilter.builder()
                    .current(
                        ContractWithoutAmendments.UsageFilter.Current.builder()
                            .groupKey("string")
                            .groupValues(listOf("string"))
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .initial(
                        ContractWithoutAmendments.UsageFilter.Initial.builder()
                            .groupKey("string")
                            .groupValues(listOf("string"))
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .updates(
                        listOf(
                            ContractWithoutAmendments.UsageFilter.Update.builder()
                                .groupKey("string")
                                .groupValues(listOf("string"))
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                    )
                    .build()
            )
    }
}
