// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import com.metronome.api.models.*
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ContractAmendParamsTest {

    @Test
    fun createContractAmendParams() {
        ContractAmendParams.builder()
            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
            .commits(
                listOf(
                    ContractAmendParams.Commit.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .type(ContractAmendParams.Commit.Type.PREPAID)
                        .accessSchedule(
                            ContractAmendParams.Commit.AccessSchedule.builder()
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.Commit.AccessSchedule.ScheduleItem
                                            .builder()
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .amount(0.0)
                        .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                        .applicableProductTags(listOf("string"))
                        .customFields(ContractAmendParams.Commit.CustomFields.builder().build())
                        .description("description")
                        .invoiceSchedule(
                            ContractAmendParams.Commit.InvoiceSchedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.Commit.InvoiceSchedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.Commit.InvoiceSchedule.ScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractAmendParams.Commit.RateType.COMMIT_RATE)
                        .rolloverFraction(0.0)
                        .temporaryId("temporary_id")
                        .build()
                )
            )
            .credits(
                listOf(
                    ContractAmendParams.Credit.builder()
                        .accessSchedule(
                            ContractAmendParams.Credit.AccessSchedule.builder()
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.Credit.AccessSchedule.ScheduleItem
                                            .builder()
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                        .applicableProductTags(listOf("string"))
                        .customFields(ContractAmendParams.Credit.CustomFields.builder().build())
                        .description("description")
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractAmendParams.Credit.RateType.COMMIT_RATE)
                        .build()
                )
            )
            .customFields(ContractAmendParams.CustomFields.builder().build())
            .discounts(
                listOf(
                    ContractAmendParams.Discount.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractAmendParams.Discount.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.Discount.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.Discount.Schedule.ScheduleItem.builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
            .netsuiteSalesOrderId("netsuite_sales_order_id")
            .overrides(
                listOf(
                    ContractAmendParams.Override.builder()
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .applicableProductTags(listOf("string"))
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .entitled(true)
                        .isCommitSpecific(true)
                        .multiplier(0.0)
                        .overrideSpecifiers(
                            listOf(
                                ContractAmendParams.Override.OverrideSpecifier.builder()
                                    .commitIds(listOf("string"))
                                    .presentationGroupValues(
                                        ContractAmendParams.Override.OverrideSpecifier
                                            .PresentationGroupValues
                                            .builder()
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        ContractAmendParams.Override.OverrideSpecifier
                                            .PricingGroupValues
                                            .builder()
                                            .build()
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .productTags(listOf("string"))
                                    .build()
                            )
                        )
                        .overwriteRate(
                            ContractAmendParams.Override.OverwriteRate.builder()
                                .rateType(ContractAmendParams.Override.OverwriteRate.RateType.FLAT)
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customRate(
                                    ContractAmendParams.Override.OverwriteRate.CustomRate.builder()
                                        .build()
                                )
                                .isProrated(true)
                                .price(0.0)
                                .quantity(0.0)
                                .tiers(listOf(Tier.builder().price(0.0).size(0.0).build()))
                                .build()
                        )
                        .priority(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .target(ContractAmendParams.Override.Target.COMMIT_RATE)
                        .tiers(
                            listOf(
                                ContractAmendParams.Override.Tier.builder()
                                    .multiplier(0.0)
                                    .size(0.0)
                                    .build()
                            )
                        )
                        .type(ContractAmendParams.Override.Type.OVERWRITE)
                        .build()
                )
            )
            .professionalServices(
                listOf(
                    ContractAmendParams.ProfessionalService.builder()
                        .maxAmount(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .quantity(0.0)
                        .unitPrice(0.0)
                        .customFields(
                            ContractAmendParams.ProfessionalService.CustomFields.builder().build()
                        )
                        .description("description")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
            .resellerRoyalties(
                listOf(
                    ContractAmendParams.ResellerRoyalty.builder()
                        .resellerType(ContractAmendParams.ResellerRoyalty.ResellerType.AWS)
                        .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                        .applicableProductTags(listOf("string"))
                        .awsOptions(
                            ContractAmendParams.ResellerRoyalty.AwsOptions.builder()
                                .awsAccountNumber("aws_account_number")
                                .awsOfferId("aws_offer_id")
                                .awsPayerReferenceId("aws_payer_reference_id")
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .fraction(0.0)
                        .gcpOptions(
                            ContractAmendParams.ResellerRoyalty.GcpOptions.builder()
                                .gcpAccountId("gcp_account_id")
                                .gcpOfferId("gcp_offer_id")
                                .build()
                        )
                        .netsuiteResellerId("netsuite_reseller_id")
                        .resellerContractValue(0.0)
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
            )
            .salesforceOpportunityId("salesforce_opportunity_id")
            .scheduledCharges(
                listOf(
                    ContractAmendParams.ScheduledCharge.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractAmendParams.ScheduledCharge.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.ScheduledCharge.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.ScheduledCharge.Schedule.ScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
            .totalContractValue(0.0)
            .build()
    }

    @Test
    fun getBody() {
        val params =
            ContractAmendParams.builder()
                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .commits(
                    listOf(
                        ContractAmendParams.Commit.builder()
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .type(ContractAmendParams.Commit.Type.PREPAID)
                            .accessSchedule(
                                ContractAmendParams.Commit.AccessSchedule.builder()
                                    .scheduleItems(
                                        listOf(
                                            ContractAmendParams.Commit.AccessSchedule.ScheduleItem
                                                .builder()
                                                .amount(0.0)
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                    )
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .amount(0.0)
                            .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductTags(listOf("string"))
                            .customFields(ContractAmendParams.Commit.CustomFields.builder().build())
                            .description("description")
                            .invoiceSchedule(
                                ContractAmendParams.Commit.InvoiceSchedule.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .recurringSchedule(
                                        ContractAmendParams.Commit.InvoiceSchedule.RecurringSchedule
                                            .builder()
                                            .amountDistribution(
                                                ContractAmendParams.Commit.InvoiceSchedule
                                                    .RecurringSchedule
                                                    .AmountDistribution
                                                    .DIVIDED
                                            )
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .frequency(
                                                ContractAmendParams.Commit.InvoiceSchedule
                                                    .RecurringSchedule
                                                    .Frequency
                                                    .MONTHLY
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .scheduleItems(
                                        listOf(
                                            ContractAmendParams.Commit.InvoiceSchedule.ScheduleItem
                                                .builder()
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .priority(0.0)
                            .rateType(ContractAmendParams.Commit.RateType.COMMIT_RATE)
                            .rolloverFraction(0.0)
                            .temporaryId("temporary_id")
                            .build()
                    )
                )
                .credits(
                    listOf(
                        ContractAmendParams.Credit.builder()
                            .accessSchedule(
                                ContractAmendParams.Credit.AccessSchedule.builder()
                                    .scheduleItems(
                                        listOf(
                                            ContractAmendParams.Credit.AccessSchedule.ScheduleItem
                                                .builder()
                                                .amount(0.0)
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                    )
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductTags(listOf("string"))
                            .customFields(ContractAmendParams.Credit.CustomFields.builder().build())
                            .description("description")
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .priority(0.0)
                            .rateType(ContractAmendParams.Credit.RateType.COMMIT_RATE)
                            .build()
                    )
                )
                .customFields(ContractAmendParams.CustomFields.builder().build())
                .discounts(
                    listOf(
                        ContractAmendParams.Discount.builder()
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .schedule(
                                ContractAmendParams.Discount.Schedule.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .recurringSchedule(
                                        ContractAmendParams.Discount.Schedule.RecurringSchedule
                                            .builder()
                                            .amountDistribution(
                                                ContractAmendParams.Discount.Schedule
                                                    .RecurringSchedule
                                                    .AmountDistribution
                                                    .DIVIDED
                                            )
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .frequency(
                                                ContractAmendParams.Discount.Schedule
                                                    .RecurringSchedule
                                                    .Frequency
                                                    .MONTHLY
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .scheduleItems(
                                        listOf(
                                            ContractAmendParams.Discount.Schedule.ScheduleItem
                                                .builder()
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .build()
                    )
                )
                .netsuiteSalesOrderId("netsuite_sales_order_id")
                .overrides(
                    listOf(
                        ContractAmendParams.Override.builder()
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .applicableProductTags(listOf("string"))
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .entitled(true)
                            .isCommitSpecific(true)
                            .multiplier(0.0)
                            .overrideSpecifiers(
                                listOf(
                                    ContractAmendParams.Override.OverrideSpecifier.builder()
                                        .commitIds(listOf("string"))
                                        .presentationGroupValues(
                                            ContractAmendParams.Override.OverrideSpecifier
                                                .PresentationGroupValues
                                                .builder()
                                                .build()
                                        )
                                        .pricingGroupValues(
                                            ContractAmendParams.Override.OverrideSpecifier
                                                .PricingGroupValues
                                                .builder()
                                                .build()
                                        )
                                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .productTags(listOf("string"))
                                        .build()
                                )
                            )
                            .overwriteRate(
                                ContractAmendParams.Override.OverwriteRate.builder()
                                    .rateType(
                                        ContractAmendParams.Override.OverwriteRate.RateType.FLAT
                                    )
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .customRate(
                                        ContractAmendParams.Override.OverwriteRate.CustomRate
                                            .builder()
                                            .build()
                                    )
                                    .isProrated(true)
                                    .price(0.0)
                                    .quantity(0.0)
                                    .tiers(listOf(Tier.builder().price(0.0).size(0.0).build()))
                                    .build()
                            )
                            .priority(0.0)
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .target(ContractAmendParams.Override.Target.COMMIT_RATE)
                            .tiers(
                                listOf(
                                    ContractAmendParams.Override.Tier.builder()
                                        .multiplier(0.0)
                                        .size(0.0)
                                        .build()
                                )
                            )
                            .type(ContractAmendParams.Override.Type.OVERWRITE)
                            .build()
                    )
                )
                .professionalServices(
                    listOf(
                        ContractAmendParams.ProfessionalService.builder()
                            .maxAmount(0.0)
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .quantity(0.0)
                            .unitPrice(0.0)
                            .customFields(
                                ContractAmendParams.ProfessionalService.CustomFields.builder()
                                    .build()
                            )
                            .description("description")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .build()
                    )
                )
                .resellerRoyalties(
                    listOf(
                        ContractAmendParams.ResellerRoyalty.builder()
                            .resellerType(ContractAmendParams.ResellerRoyalty.ResellerType.AWS)
                            .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductTags(listOf("string"))
                            .awsOptions(
                                ContractAmendParams.ResellerRoyalty.AwsOptions.builder()
                                    .awsAccountNumber("aws_account_number")
                                    .awsOfferId("aws_offer_id")
                                    .awsPayerReferenceId("aws_payer_reference_id")
                                    .build()
                            )
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .fraction(0.0)
                            .gcpOptions(
                                ContractAmendParams.ResellerRoyalty.GcpOptions.builder()
                                    .gcpAccountId("gcp_account_id")
                                    .gcpOfferId("gcp_offer_id")
                                    .build()
                            )
                            .netsuiteResellerId("netsuite_reseller_id")
                            .resellerContractValue(0.0)
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                )
                .salesforceOpportunityId("salesforce_opportunity_id")
                .scheduledCharges(
                    listOf(
                        ContractAmendParams.ScheduledCharge.builder()
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .schedule(
                                ContractAmendParams.ScheduledCharge.Schedule.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .recurringSchedule(
                                        ContractAmendParams.ScheduledCharge.Schedule
                                            .RecurringSchedule
                                            .builder()
                                            .amountDistribution(
                                                ContractAmendParams.ScheduledCharge.Schedule
                                                    .RecurringSchedule
                                                    .AmountDistribution
                                                    .DIVIDED
                                            )
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .frequency(
                                                ContractAmendParams.ScheduledCharge.Schedule
                                                    .RecurringSchedule
                                                    .Frequency
                                                    .MONTHLY
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .scheduleItems(
                                        listOf(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .ScheduleItem
                                                .builder()
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .build()
                    )
                )
                .totalContractValue(0.0)
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.contractId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.customerId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.startingAt()).isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(body.commits())
            .isEqualTo(
                listOf(
                    ContractAmendParams.Commit.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .type(ContractAmendParams.Commit.Type.PREPAID)
                        .accessSchedule(
                            ContractAmendParams.Commit.AccessSchedule.builder()
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.Commit.AccessSchedule.ScheduleItem
                                            .builder()
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .amount(0.0)
                        .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                        .applicableProductTags(listOf("string"))
                        .customFields(ContractAmendParams.Commit.CustomFields.builder().build())
                        .description("description")
                        .invoiceSchedule(
                            ContractAmendParams.Commit.InvoiceSchedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.Commit.InvoiceSchedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.Commit.InvoiceSchedule.ScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractAmendParams.Commit.RateType.COMMIT_RATE)
                        .rolloverFraction(0.0)
                        .temporaryId("temporary_id")
                        .build()
                )
            )
        assertThat(body.credits())
            .isEqualTo(
                listOf(
                    ContractAmendParams.Credit.builder()
                        .accessSchedule(
                            ContractAmendParams.Credit.AccessSchedule.builder()
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.Credit.AccessSchedule.ScheduleItem
                                            .builder()
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                        .applicableProductTags(listOf("string"))
                        .customFields(ContractAmendParams.Credit.CustomFields.builder().build())
                        .description("description")
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractAmendParams.Credit.RateType.COMMIT_RATE)
                        .build()
                )
            )
        assertThat(body.customFields())
            .isEqualTo(ContractAmendParams.CustomFields.builder().build())
        assertThat(body.discounts())
            .isEqualTo(
                listOf(
                    ContractAmendParams.Discount.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractAmendParams.Discount.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.Discount.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.Discount.Schedule.ScheduleItem.builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
        assertThat(body.netsuiteSalesOrderId()).isEqualTo("netsuite_sales_order_id")
        assertThat(body.overrides())
            .isEqualTo(
                listOf(
                    ContractAmendParams.Override.builder()
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .applicableProductTags(listOf("string"))
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .entitled(true)
                        .isCommitSpecific(true)
                        .multiplier(0.0)
                        .overrideSpecifiers(
                            listOf(
                                ContractAmendParams.Override.OverrideSpecifier.builder()
                                    .commitIds(listOf("string"))
                                    .presentationGroupValues(
                                        ContractAmendParams.Override.OverrideSpecifier
                                            .PresentationGroupValues
                                            .builder()
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        ContractAmendParams.Override.OverrideSpecifier
                                            .PricingGroupValues
                                            .builder()
                                            .build()
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .productTags(listOf("string"))
                                    .build()
                            )
                        )
                        .overwriteRate(
                            ContractAmendParams.Override.OverwriteRate.builder()
                                .rateType(ContractAmendParams.Override.OverwriteRate.RateType.FLAT)
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customRate(
                                    ContractAmendParams.Override.OverwriteRate.CustomRate.builder()
                                        .build()
                                )
                                .isProrated(true)
                                .price(0.0)
                                .quantity(0.0)
                                .tiers(listOf(Tier.builder().price(0.0).size(0.0).build()))
                                .build()
                        )
                        .priority(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .target(ContractAmendParams.Override.Target.COMMIT_RATE)
                        .tiers(
                            listOf(
                                ContractAmendParams.Override.Tier.builder()
                                    .multiplier(0.0)
                                    .size(0.0)
                                    .build()
                            )
                        )
                        .type(ContractAmendParams.Override.Type.OVERWRITE)
                        .build()
                )
            )
        assertThat(body.professionalServices())
            .isEqualTo(
                listOf(
                    ContractAmendParams.ProfessionalService.builder()
                        .maxAmount(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .quantity(0.0)
                        .unitPrice(0.0)
                        .customFields(
                            ContractAmendParams.ProfessionalService.CustomFields.builder().build()
                        )
                        .description("description")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
        assertThat(body.resellerRoyalties())
            .isEqualTo(
                listOf(
                    ContractAmendParams.ResellerRoyalty.builder()
                        .resellerType(ContractAmendParams.ResellerRoyalty.ResellerType.AWS)
                        .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                        .applicableProductTags(listOf("string"))
                        .awsOptions(
                            ContractAmendParams.ResellerRoyalty.AwsOptions.builder()
                                .awsAccountNumber("aws_account_number")
                                .awsOfferId("aws_offer_id")
                                .awsPayerReferenceId("aws_payer_reference_id")
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .fraction(0.0)
                        .gcpOptions(
                            ContractAmendParams.ResellerRoyalty.GcpOptions.builder()
                                .gcpAccountId("gcp_account_id")
                                .gcpOfferId("gcp_offer_id")
                                .build()
                        )
                        .netsuiteResellerId("netsuite_reseller_id")
                        .resellerContractValue(0.0)
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
            )
        assertThat(body.salesforceOpportunityId()).isEqualTo("salesforce_opportunity_id")
        assertThat(body.scheduledCharges())
            .isEqualTo(
                listOf(
                    ContractAmendParams.ScheduledCharge.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractAmendParams.ScheduledCharge.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .recurringSchedule(
                                    ContractAmendParams.ScheduledCharge.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .scheduleItems(
                                    listOf(
                                        ContractAmendParams.ScheduledCharge.Schedule.ScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
            )
        assertThat(body.totalContractValue()).isEqualTo(0.0)
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            ContractAmendParams.builder()
                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.contractId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.customerId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.startingAt()).isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }
}
