// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ContractRetrieveRateScheduleResponseTest {

    @Test
    fun createContractRetrieveRateScheduleResponse() {
        val contractRetrieveRateScheduleResponse =
            ContractRetrieveRateScheduleResponse.builder()
                .data(
                    listOf(
                        ContractRetrieveRateScheduleResponse.Data.builder()
                            .entitled(true)
                            .listRate(
                                Rate.builder()
                                    .rateType(Rate.RateType.FLAT)
                                    .creditType(
                                        CreditTypeData.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("name")
                                            .build()
                                    )
                                    .customRate(Rate.CustomRate.builder().build())
                                    .isProrated(true)
                                    .price(42.23)
                                    .pricingGroupValues(Rate.PricingGroupValues.builder().build())
                                    .quantity(42.23)
                                    .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                                    .useListPrices(true)
                                    .build()
                            )
                            .productCustomFields(
                                ContractRetrieveRateScheduleResponse.Data.ProductCustomFields
                                    .builder()
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .productName("product_name")
                            .productTags(listOf("string"))
                            .rateCardId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .commitRate(
                                ContractRetrieveRateScheduleResponse.Data.CommitRate.builder()
                                    .rateType(
                                        ContractRetrieveRateScheduleResponse.Data.CommitRate
                                            .RateType
                                            .FLAT
                                    )
                                    .price(42.23)
                                    .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                                    .build()
                            )
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .overrideRate(
                                Rate.builder()
                                    .rateType(Rate.RateType.FLAT)
                                    .creditType(
                                        CreditTypeData.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("name")
                                            .build()
                                    )
                                    .customRate(Rate.CustomRate.builder().build())
                                    .isProrated(true)
                                    .price(42.23)
                                    .pricingGroupValues(Rate.PricingGroupValues.builder().build())
                                    .quantity(42.23)
                                    .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                                    .useListPrices(true)
                                    .build()
                            )
                            .pricingGroupValues(
                                ContractRetrieveRateScheduleResponse.Data.PricingGroupValues
                                    .builder()
                                    .build()
                            )
                            .build()
                    )
                )
                .nextPage("next_page")
                .build()
        assertThat(contractRetrieveRateScheduleResponse).isNotNull
        assertThat(contractRetrieveRateScheduleResponse.data())
            .containsExactly(
                ContractRetrieveRateScheduleResponse.Data.builder()
                    .entitled(true)
                    .listRate(
                        Rate.builder()
                            .rateType(Rate.RateType.FLAT)
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .customRate(Rate.CustomRate.builder().build())
                            .isProrated(true)
                            .price(42.23)
                            .pricingGroupValues(Rate.PricingGroupValues.builder().build())
                            .quantity(42.23)
                            .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                            .useListPrices(true)
                            .build()
                    )
                    .productCustomFields(
                        ContractRetrieveRateScheduleResponse.Data.ProductCustomFields.builder()
                            .build()
                    )
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .productName("product_name")
                    .productTags(listOf("string"))
                    .rateCardId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .commitRate(
                        ContractRetrieveRateScheduleResponse.Data.CommitRate.builder()
                            .rateType(
                                ContractRetrieveRateScheduleResponse.Data.CommitRate.RateType.FLAT
                            )
                            .price(42.23)
                            .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                            .build()
                    )
                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .overrideRate(
                        Rate.builder()
                            .rateType(Rate.RateType.FLAT)
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .customRate(Rate.CustomRate.builder().build())
                            .isProrated(true)
                            .price(42.23)
                            .pricingGroupValues(Rate.PricingGroupValues.builder().build())
                            .quantity(42.23)
                            .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                            .useListPrices(true)
                            .build()
                    )
                    .pricingGroupValues(
                        ContractRetrieveRateScheduleResponse.Data.PricingGroupValues.builder()
                            .build()
                    )
                    .build()
            )
        assertThat(contractRetrieveRateScheduleResponse.nextPage()).contains("next_page")
    }
}
