// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CreditListEntriesResponseTest {

    @Test
    fun createCreditListEntriesResponse() {
        val creditListEntriesResponse =
            CreditListEntriesResponse.builder()
                .data(
                    listOf(
                        CreditListEntriesResponse.Data.builder()
                            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .ledgers(
                                listOf(
                                    CreditListEntriesResponse.Data.Ledger.builder()
                                        .creditType(
                                            CreditListEntriesResponse.Data.Ledger.CreditType
                                                .builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("string")
                                                .build()
                                        )
                                        .endingBalance(
                                            CreditListEntriesResponse.Data.Ledger.EndingBalance
                                                .builder()
                                                .effectiveAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .excludingPending(42.23)
                                                .includingPending(42.23)
                                                .build()
                                        )
                                        .entries(
                                            listOf(
                                                CreditListEntriesResponse.Data.Ledger.Entry
                                                    .builder()
                                                    .amount(42.23)
                                                    .createdBy("string")
                                                    .creditGrantId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .effectiveAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .reason("Automated invoice deduction")
                                                    .runningBalance(42.23)
                                                    .invoiceId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .build()
                                            )
                                        )
                                        .pendingEntries(
                                            listOf(
                                                CreditListEntriesResponse.Data.Ledger.PendingEntry
                                                    .builder()
                                                    .amount(42.23)
                                                    .createdBy("string")
                                                    .creditGrantId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .effectiveAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .reason("Automated invoice deduction")
                                                    .runningBalance(42.23)
                                                    .invoiceId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .build()
                                            )
                                        )
                                        .startingBalance(
                                            CreditListEntriesResponse.Data.Ledger.StartingBalance
                                                .builder()
                                                .effectiveAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .excludingPending(42.23)
                                                .includingPending(42.23)
                                                .build()
                                        )
                                        .build()
                                )
                            )
                            .build()
                    )
                )
                .nextPage("string")
                .build()
        assertThat(creditListEntriesResponse).isNotNull
        assertThat(creditListEntriesResponse.data())
            .containsExactly(
                CreditListEntriesResponse.Data.builder()
                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .ledgers(
                        listOf(
                            CreditListEntriesResponse.Data.Ledger.builder()
                                .creditType(
                                    CreditListEntriesResponse.Data.Ledger.CreditType.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("string")
                                        .build()
                                )
                                .endingBalance(
                                    CreditListEntriesResponse.Data.Ledger.EndingBalance.builder()
                                        .effectiveAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .excludingPending(42.23)
                                        .includingPending(42.23)
                                        .build()
                                )
                                .entries(
                                    listOf(
                                        CreditListEntriesResponse.Data.Ledger.Entry.builder()
                                            .amount(42.23)
                                            .createdBy("string")
                                            .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .effectiveAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .reason("Automated invoice deduction")
                                            .runningBalance(42.23)
                                            .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                )
                                .pendingEntries(
                                    listOf(
                                        CreditListEntriesResponse.Data.Ledger.PendingEntry.builder()
                                            .amount(42.23)
                                            .createdBy("string")
                                            .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .effectiveAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .reason("Automated invoice deduction")
                                            .runningBalance(42.23)
                                            .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                )
                                .startingBalance(
                                    CreditListEntriesResponse.Data.Ledger.StartingBalance.builder()
                                        .effectiveAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .excludingPending(42.23)
                                        .includingPending(42.23)
                                        .build()
                                )
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(creditListEntriesResponse.nextPage()).contains("string")
    }
}
