// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CreditListGrantsResponseTest {

    @Test
    fun createCreditListGrantsResponse() {
        val creditListGrantsResponse =
            CreditListGrantsResponse.builder()
                .data(
                    listOf(
                        CreditListGrantsResponse.Data.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .balance(
                                CreditListGrantsResponse.Data.Balance.builder()
                                    .effectiveAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .excludingPending(42.23)
                                    .includingPending(42.23)
                                    .build()
                            )
                            .customFields(
                                CreditListGrantsResponse.Data.CustomFields.builder().build()
                            )
                            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .deductions(
                                listOf(
                                    CreditListGrantsResponse.Data.Deduction.builder()
                                        .amount(42.23)
                                        .createdBy("string")
                                        .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .effectiveAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .reason("Automated invoice deduction")
                                        .runningBalance(42.23)
                                        .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                            )
                            .effectiveAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .grantAmount(
                                CreditListGrantsResponse.Data.GrantAmount.builder()
                                    .amount(42.23)
                                    .creditType(
                                        CreditListGrantsResponse.Data.GrantAmount.CreditType
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("string")
                                            .build()
                                    )
                                    .build()
                            )
                            .name("string")
                            .paidAmount(
                                CreditListGrantsResponse.Data.PaidAmount.builder()
                                    .amount(42.23)
                                    .creditType(
                                        CreditListGrantsResponse.Data.PaidAmount.CreditType
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("string")
                                            .build()
                                    )
                                    .build()
                            )
                            .pendingDeductions(
                                listOf(
                                    CreditListGrantsResponse.Data.PendingDeduction.builder()
                                        .amount(42.23)
                                        .createdBy("string")
                                        .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .effectiveAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .reason("Automated invoice deduction")
                                        .runningBalance(42.23)
                                        .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                            )
                            .priority(42.23)
                            .creditGrantType("string")
                            .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .products(
                                listOf(
                                    CreditListGrantsResponse.Data.Product.builder()
                                        .id("string")
                                        .name("string")
                                        .build()
                                )
                            )
                            .reason("string")
                            .uniquenessKey("x")
                            .build()
                    )
                )
                .nextPage("string")
                .build()
        assertThat(creditListGrantsResponse).isNotNull
        assertThat(creditListGrantsResponse.data())
            .containsExactly(
                CreditListGrantsResponse.Data.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .balance(
                        CreditListGrantsResponse.Data.Balance.builder()
                            .effectiveAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .excludingPending(42.23)
                            .includingPending(42.23)
                            .build()
                    )
                    .customFields(CreditListGrantsResponse.Data.CustomFields.builder().build())
                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .deductions(
                        listOf(
                            CreditListGrantsResponse.Data.Deduction.builder()
                                .amount(42.23)
                                .createdBy("string")
                                .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .effectiveAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .reason("Automated invoice deduction")
                                .runningBalance(42.23)
                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                    )
                    .effectiveAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .grantAmount(
                        CreditListGrantsResponse.Data.GrantAmount.builder()
                            .amount(42.23)
                            .creditType(
                                CreditListGrantsResponse.Data.GrantAmount.CreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .build()
                    )
                    .name("string")
                    .paidAmount(
                        CreditListGrantsResponse.Data.PaidAmount.builder()
                            .amount(42.23)
                            .creditType(
                                CreditListGrantsResponse.Data.PaidAmount.CreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .build()
                    )
                    .pendingDeductions(
                        listOf(
                            CreditListGrantsResponse.Data.PendingDeduction.builder()
                                .amount(42.23)
                                .createdBy("string")
                                .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .effectiveAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .reason("Automated invoice deduction")
                                .runningBalance(42.23)
                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                    )
                    .priority(42.23)
                    .creditGrantType("string")
                    .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .products(
                        listOf(
                            CreditListGrantsResponse.Data.Product.builder()
                                .id("string")
                                .name("string")
                                .build()
                        )
                    )
                    .reason("string")
                    .uniquenessKey("x")
                    .build()
            )
        assertThat(creditListGrantsResponse.nextPage()).contains("string")
    }
}
