// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CreditGrantListEntriesResponseTest {

    @Test
    fun createCreditGrantListEntriesResponse() {
        val creditGrantListEntriesResponse =
            CreditGrantListEntriesResponse.builder()
                .data(
                    listOf(
                        CreditGrantListEntriesResponse.Data.builder()
                            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .ledgers(
                                listOf(
                                    CreditGrantListEntriesResponse.Data.Ledger.builder()
                                        .creditType(
                                            CreditTypeData.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .endingBalance(
                                            CreditGrantListEntriesResponse.Data.Ledger.EndingBalance
                                                .builder()
                                                .effectiveAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .excludingPending(0.0)
                                                .includingPending(0.0)
                                                .build()
                                        )
                                        .entries(
                                            listOf(
                                                CreditLedgerEntry.builder()
                                                    .amount(0.0)
                                                    .createdBy("created_by")
                                                    .creditGrantId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .effectiveAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .reason("Automated invoice deduction")
                                                    .runningBalance(0.0)
                                                    .invoiceId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .build()
                                            )
                                        )
                                        .pendingEntries(
                                            listOf(
                                                CreditLedgerEntry.builder()
                                                    .amount(0.0)
                                                    .createdBy("created_by")
                                                    .creditGrantId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .effectiveAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .reason("Automated invoice deduction")
                                                    .runningBalance(0.0)
                                                    .invoiceId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .build()
                                            )
                                        )
                                        .startingBalance(
                                            CreditGrantListEntriesResponse.Data.Ledger
                                                .StartingBalance
                                                .builder()
                                                .effectiveAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .excludingPending(0.0)
                                                .includingPending(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                            )
                            .build()
                    )
                )
                .nextPage("next_page")
                .build()
        assertThat(creditGrantListEntriesResponse).isNotNull
        assertThat(creditGrantListEntriesResponse.data())
            .containsExactly(
                CreditGrantListEntriesResponse.Data.builder()
                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .ledgers(
                        listOf(
                            CreditGrantListEntriesResponse.Data.Ledger.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .endingBalance(
                                    CreditGrantListEntriesResponse.Data.Ledger.EndingBalance
                                        .builder()
                                        .effectiveAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .excludingPending(0.0)
                                        .includingPending(0.0)
                                        .build()
                                )
                                .entries(
                                    listOf(
                                        CreditLedgerEntry.builder()
                                            .amount(0.0)
                                            .createdBy("created_by")
                                            .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .effectiveAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .reason("Automated invoice deduction")
                                            .runningBalance(0.0)
                                            .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                )
                                .pendingEntries(
                                    listOf(
                                        CreditLedgerEntry.builder()
                                            .amount(0.0)
                                            .createdBy("created_by")
                                            .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .effectiveAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .reason("Automated invoice deduction")
                                            .runningBalance(0.0)
                                            .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                )
                                .startingBalance(
                                    CreditGrantListEntriesResponse.Data.Ledger.StartingBalance
                                        .builder()
                                        .effectiveAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .excludingPending(0.0)
                                        .includingPending(0.0)
                                        .build()
                                )
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(creditGrantListEntriesResponse.nextPage()).contains("next_page")
    }
}
