// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import com.metronome.api.core.JsonValue
import com.metronome.api.models.*
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CustomerCommitCreateParamsTest {

    @Test
    fun createCustomerCommitCreateParams() {
        CustomerCommitCreateParams.builder()
            .accessSchedule(
                CustomerCommitCreateParams.AccessSchedule.builder()
                    .scheduleItems(
                        listOf(
                            CustomerCommitCreateParams.AccessSchedule.ScheduleItem.builder()
                                .amount(0.0)
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                    )
                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .priority(0.0)
            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .type(CustomerCommitCreateParams.Type.PREPAID)
            .applicableContractIds(listOf("string"))
            .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
            .applicableProductTags(listOf("string"))
            .customFields(
                CustomerCommitCreateParams.CustomFields.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
            .description("description")
            .invoiceContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .invoiceSchedule(
                CustomerCommitCreateParams.InvoiceSchedule.builder()
                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .recurringSchedule(
                        CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule.builder()
                            .amountDistribution(
                                CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule
                                    .AmountDistribution
                                    .DIVIDED
                            )
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .frequency(
                                CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule
                                    .Frequency
                                    .MONTHLY
                            )
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .amount(0.0)
                            .quantity(0.0)
                            .unitPrice(0.0)
                            .build()
                    )
                    .scheduleItems(
                        listOf(
                            CustomerCommitCreateParams.InvoiceSchedule.ScheduleItem.builder()
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .amount(0.0)
                                .quantity(0.0)
                                .unitPrice(0.0)
                                .build()
                        )
                    )
                    .build()
            )
            .name("x")
            .netsuiteSalesOrderId("netsuite_sales_order_id")
            .rateType(CustomerCommitCreateParams.RateType.COMMIT_RATE)
            .salesforceOpportunityId("salesforce_opportunity_id")
            .build()
    }

    @Test
    fun getBody() {
        val params =
            CustomerCommitCreateParams.builder()
                .accessSchedule(
                    CustomerCommitCreateParams.AccessSchedule.builder()
                        .scheduleItems(
                            listOf(
                                CustomerCommitCreateParams.AccessSchedule.ScheduleItem.builder()
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                        )
                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .priority(0.0)
                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .type(CustomerCommitCreateParams.Type.PREPAID)
                .applicableContractIds(listOf("string"))
                .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .applicableProductTags(listOf("string"))
                .customFields(
                    CustomerCommitCreateParams.CustomFields.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .description("description")
                .invoiceContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .invoiceSchedule(
                    CustomerCommitCreateParams.InvoiceSchedule.builder()
                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .recurringSchedule(
                            CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule.builder()
                                .amountDistribution(
                                    CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule
                                        .AmountDistribution
                                        .DIVIDED
                                )
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .frequency(
                                    CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule
                                        .Frequency
                                        .MONTHLY
                                )
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .amount(0.0)
                                .quantity(0.0)
                                .unitPrice(0.0)
                                .build()
                        )
                        .scheduleItems(
                            listOf(
                                CustomerCommitCreateParams.InvoiceSchedule.ScheduleItem.builder()
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                        )
                        .build()
                )
                .name("x")
                .netsuiteSalesOrderId("netsuite_sales_order_id")
                .rateType(CustomerCommitCreateParams.RateType.COMMIT_RATE)
                .salesforceOpportunityId("salesforce_opportunity_id")
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.accessSchedule())
            .isEqualTo(
                CustomerCommitCreateParams.AccessSchedule.builder()
                    .scheduleItems(
                        listOf(
                            CustomerCommitCreateParams.AccessSchedule.ScheduleItem.builder()
                                .amount(0.0)
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                    )
                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
        assertThat(body.customerId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.priority()).isEqualTo(0.0)
        assertThat(body.productId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.type()).isEqualTo(CustomerCommitCreateParams.Type.PREPAID)
        assertThat(body.applicableContractIds()).isEqualTo(listOf("string"))
        assertThat(body.applicableProductIds())
            .isEqualTo(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
        assertThat(body.applicableProductTags()).isEqualTo(listOf("string"))
        assertThat(body.customFields())
            .isEqualTo(
                CustomerCommitCreateParams.CustomFields.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(body.description()).isEqualTo("description")
        assertThat(body.invoiceContractId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.invoiceSchedule())
            .isEqualTo(
                CustomerCommitCreateParams.InvoiceSchedule.builder()
                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .recurringSchedule(
                        CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule.builder()
                            .amountDistribution(
                                CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule
                                    .AmountDistribution
                                    .DIVIDED
                            )
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .frequency(
                                CustomerCommitCreateParams.InvoiceSchedule.RecurringSchedule
                                    .Frequency
                                    .MONTHLY
                            )
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .amount(0.0)
                            .quantity(0.0)
                            .unitPrice(0.0)
                            .build()
                    )
                    .scheduleItems(
                        listOf(
                            CustomerCommitCreateParams.InvoiceSchedule.ScheduleItem.builder()
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .amount(0.0)
                                .quantity(0.0)
                                .unitPrice(0.0)
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(body.name()).isEqualTo("x")
        assertThat(body.netsuiteSalesOrderId()).isEqualTo("netsuite_sales_order_id")
        assertThat(body.rateType()).isEqualTo(CustomerCommitCreateParams.RateType.COMMIT_RATE)
        assertThat(body.salesforceOpportunityId()).isEqualTo("salesforce_opportunity_id")
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            CustomerCommitCreateParams.builder()
                .accessSchedule(
                    CustomerCommitCreateParams.AccessSchedule.builder()
                        .scheduleItems(
                            listOf(
                                CustomerCommitCreateParams.AccessSchedule.ScheduleItem.builder()
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                        )
                        .build()
                )
                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .priority(0.0)
                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .type(CustomerCommitCreateParams.Type.PREPAID)
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.accessSchedule())
            .isEqualTo(
                CustomerCommitCreateParams.AccessSchedule.builder()
                    .scheduleItems(
                        listOf(
                            CustomerCommitCreateParams.AccessSchedule.ScheduleItem.builder()
                                .amount(0.0)
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(body.customerId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.priority()).isEqualTo(0.0)
        assertThat(body.productId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.type()).isEqualTo(CustomerCommitCreateParams.Type.PREPAID)
    }
}
