// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CustomerCommitListResponseTest {

    @Test
    fun createCustomerCommitListResponse() {
        val customerCommitListResponse =
            CustomerCommitListResponse.builder()
                .data(
                    listOf(
                        Commit.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .product(
                                Commit.Product.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .type(Commit.Type.PREPAID)
                            .accessSchedule(
                                ScheduleDuration.builder()
                                    .scheduleItems(
                                        listOf(
                                            ScheduleDuration.ScheduleItem.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .amount(42.23)
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                    )
                                    .creditType(
                                        CreditTypeData.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("name")
                                            .build()
                                    )
                                    .build()
                            )
                            .amount(42.23)
                            .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductTags(listOf("string"))
                            .contract(
                                Commit.Contract.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .customFields(Commit.CustomFields.builder().build())
                            .description("description")
                            .invoiceContract(
                                Commit.InvoiceContract.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .invoiceSchedule(
                                SchedulePointInTime.builder()
                                    .creditType(
                                        CreditTypeData.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("name")
                                            .build()
                                    )
                                    .scheduleItems(
                                        listOf(
                                            SchedulePointInTime.ScheduleItem.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .amount(42.23)
                                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .quantity(42.23)
                                                .timestamp(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .unitPrice(42.23)
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .ledger(
                                listOf(
                                    Commit.Ledger.ofPrepaidCommitSegmentStartLedgerEntry(
                                        Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                                            .amount(42.23)
                                            .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .type(
                                                Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry
                                                    .Type
                                                    .PREPAID_COMMIT_SEGMENT_START
                                            )
                                            .build()
                                    )
                                )
                            )
                            .name("name")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .priority(42.23)
                            .rolledOverFrom(
                                Commit.RolledOverFrom.builder()
                                    .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .rolloverFraction(42.23)
                            .salesforceOpportunityId("salesforce_opportunity_id")
                            .build()
                    )
                )
                .nextPage("next_page")
                .build()
        assertThat(customerCommitListResponse).isNotNull
        assertThat(customerCommitListResponse.data())
            .containsExactly(
                Commit.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .product(
                        Commit.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .type(Commit.Type.PREPAID)
                    .accessSchedule(
                        ScheduleDuration.builder()
                            .scheduleItems(
                                listOf(
                                    ScheduleDuration.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(42.23)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                            )
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .build()
                    )
                    .amount(42.23)
                    .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                    .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                    .applicableProductTags(listOf("string"))
                    .contract(
                        Commit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
                    )
                    .customFields(Commit.CustomFields.builder().build())
                    .description("description")
                    .invoiceContract(
                        Commit.InvoiceContract.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .invoiceSchedule(
                        SchedulePointInTime.builder()
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .scheduleItems(
                                listOf(
                                    SchedulePointInTime.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(42.23)
                                        .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .quantity(42.23)
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .unitPrice(42.23)
                                        .build()
                                )
                            )
                            .build()
                    )
                    .ledger(
                        listOf(
                            Commit.Ledger.ofPrepaidCommitSegmentStartLedgerEntry(
                                Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.builder()
                                    .amount(42.23)
                                    .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .type(
                                        Commit.Ledger.PrepaidCommitSegmentStartLedgerEntry.Type
                                            .PREPAID_COMMIT_SEGMENT_START
                                    )
                                    .build()
                            )
                        )
                    )
                    .name("name")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .priority(42.23)
                    .rolledOverFrom(
                        Commit.RolledOverFrom.builder()
                            .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .rolloverFraction(42.23)
                    .salesforceOpportunityId("salesforce_opportunity_id")
                    .build()
            )
        assertThat(customerCommitListResponse.nextPage()).contains("next_page")
    }
}
