// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CustomerInvoiceRetrieveResponseTest {

    @Test
    fun createCustomerInvoiceRetrieveResponse() {
        val customerInvoiceRetrieveResponse =
            CustomerInvoiceRetrieveResponse.builder()
                .data(
                    Invoice.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .billableStatus(Invoice.BillableStatus.BILLABLE)
                        .creditType(
                            Invoice.CreditType.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("string")
                                .build()
                        )
                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .lineItems(
                            listOf(
                                Invoice.LineItem.builder()
                                    .creditType(
                                        Invoice.LineItem.CreditType.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("string")
                                            .build()
                                    )
                                    .name("string")
                                    .total(42.23)
                                    .commitCustomFields(
                                        Invoice.LineItem.CommitCustomFields.builder().build()
                                    )
                                    .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .commitNetsuiteItemId("string")
                                    .commitNetsuiteSalesOrderId("string")
                                    .commitSegmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .commitType("string")
                                    .customFields(Invoice.LineItem.CustomFields.builder().build())
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .groupKey("string")
                                    .groupValue("string")
                                    .isProrated(true)
                                    .metadata("string")
                                    .netsuiteInvoiceBillingEnd(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .netsuiteInvoiceBillingStart(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .netsuiteItemId("string")
                                    .postpaidCommit(
                                        Invoice.LineItem.PostpaidCommit.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                    .presentationGroupValues(
                                        Invoice.LineItem.PresentationGroupValues.builder().build()
                                    )
                                    .pricingGroupValues(
                                        Invoice.LineItem.PricingGroupValues.builder().build()
                                    )
                                    .productCustomFields(
                                        Invoice.LineItem.ProductCustomFields.builder().build()
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .productType("string")
                                    .professionalServiceCustomFields(
                                        Invoice.LineItem.ProfessionalServiceCustomFields.builder()
                                            .build()
                                    )
                                    .professionalServiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .quantity(42.23)
                                    .resellerType(Invoice.LineItem.ResellerType.AWS)
                                    .scheduledChargeCustomFields(
                                        Invoice.LineItem.ScheduledChargeCustomFields.builder()
                                            .build()
                                    )
                                    .scheduledChargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .subLineItems(
                                        listOf(
                                            Invoice.LineItem.SubLineItem.builder()
                                                .customFields(
                                                    Invoice.LineItem.SubLineItem.CustomFields
                                                        .builder()
                                                        .build()
                                                )
                                                .name("string")
                                                .quantity(42.23)
                                                .subtotal(42.23)
                                                .chargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .creditGrantId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .price(42.23)
                                                .tiers(
                                                    listOf(
                                                        Invoice.LineItem.SubLineItem.Tier.builder()
                                                            .price(42.23)
                                                            .quantity(42.23)
                                                            .startingAt(42.23)
                                                            .subtotal(42.23)
                                                            .build()
                                                    )
                                                )
                                                .build()
                                        )
                                    )
                                    .unitPrice(42.23)
                                    .build()
                            )
                        )
                        .status("DRAFT, VOID, or FINALIZED")
                        .total(42.23)
                        .type(
                            "PLAN_ARREARS, SCHEDULED, USAGE, CORRECTION, CREDIT_PURCHASE, or SEAT_PURCHASE"
                        )
                        .amendmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .contractCustomFields(Invoice.ContractCustomFields.builder().build())
                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .correctionRecord(
                            Invoice.CorrectionRecord.builder()
                                .correctedInvoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .memo("string")
                                .reason("string")
                                .correctedExternalInvoice(
                                    Invoice.CorrectionRecord.CorrectedExternalInvoice.builder()
                                        .billingProviderType(
                                            Invoice.CorrectionRecord.CorrectedExternalInvoice
                                                .BillingProviderType
                                                .AWS_MARKETPLACE
                                        )
                                        .externalStatus(
                                            Invoice.CorrectionRecord.CorrectedExternalInvoice
                                                .ExternalStatus
                                                .DRAFT
                                        )
                                        .invoiceId("string")
                                        .issuedAtTimestamp(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .customFields(Invoice.CustomFields.builder().build())
                        .customerCustomFields(Invoice.CustomerCustomFields.builder().build())
                        .endTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalInvoice(
                            Invoice.ExternalInvoice.builder()
                                .billingProviderType(
                                    Invoice.ExternalInvoice.BillingProviderType.AWS_MARKETPLACE
                                )
                                .externalStatus(Invoice.ExternalInvoice.ExternalStatus.DRAFT)
                                .invoiceId("string")
                                .issuedAtTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .invoiceAdjustments(
                            listOf(
                                Invoice.InvoiceAdjustment.builder()
                                    .creditType(
                                        Invoice.InvoiceAdjustment.CreditType.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("string")
                                            .build()
                                    )
                                    .name("Monthly minimum (\$1,000)")
                                    .total(42.23)
                                    .creditGrantId("string")
                                    .build()
                            )
                        )
                        .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .netPaymentTermsDays(42.23)
                        .netsuiteSalesOrderId("string")
                        .planCustomFields(Invoice.PlanCustomFields.builder().build())
                        .planId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .planName("string")
                        .resellerRoyalty(
                            Invoice.ResellerRoyalty.builder()
                                .fraction("string")
                                .netsuiteResellerId("string")
                                .resellerType(Invoice.ResellerRoyalty.ResellerType.AWS)
                                .awsOptions(
                                    Invoice.ResellerRoyalty.AwsOptions.builder()
                                        .awsAccountNumber("string")
                                        .awsOfferId("string")
                                        .awsPayerReferenceId("string")
                                        .build()
                                )
                                .gcpOptions(
                                    Invoice.ResellerRoyalty.GcpOptions.builder()
                                        .gcpAccountId("string")
                                        .gcpOfferId("string")
                                        .build()
                                )
                                .build()
                        )
                        .salesforceOpportunityId("string")
                        .startTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .subtotal(42.23)
                        .build()
                )
                .build()
        assertThat(customerInvoiceRetrieveResponse).isNotNull
        assertThat(customerInvoiceRetrieveResponse.data())
            .isEqualTo(
                Invoice.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .billableStatus(Invoice.BillableStatus.BILLABLE)
                    .creditType(
                        Invoice.CreditType.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .lineItems(
                        listOf(
                            Invoice.LineItem.builder()
                                .creditType(
                                    Invoice.LineItem.CreditType.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("string")
                                        .build()
                                )
                                .name("string")
                                .total(42.23)
                                .commitCustomFields(
                                    Invoice.LineItem.CommitCustomFields.builder().build()
                                )
                                .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .commitNetsuiteItemId("string")
                                .commitNetsuiteSalesOrderId("string")
                                .commitSegmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .commitType("string")
                                .customFields(Invoice.LineItem.CustomFields.builder().build())
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .groupKey("string")
                                .groupValue("string")
                                .isProrated(true)
                                .metadata("string")
                                .netsuiteInvoiceBillingEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteInvoiceBillingStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteItemId("string")
                                .postpaidCommit(
                                    Invoice.LineItem.PostpaidCommit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .presentationGroupValues(
                                    Invoice.LineItem.PresentationGroupValues.builder().build()
                                )
                                .pricingGroupValues(
                                    Invoice.LineItem.PricingGroupValues.builder().build()
                                )
                                .productCustomFields(
                                    Invoice.LineItem.ProductCustomFields.builder().build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .productType("string")
                                .professionalServiceCustomFields(
                                    Invoice.LineItem.ProfessionalServiceCustomFields.builder()
                                        .build()
                                )
                                .professionalServiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(42.23)
                                .resellerType(Invoice.LineItem.ResellerType.AWS)
                                .scheduledChargeCustomFields(
                                    Invoice.LineItem.ScheduledChargeCustomFields.builder().build()
                                )
                                .scheduledChargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .subLineItems(
                                    listOf(
                                        Invoice.LineItem.SubLineItem.builder()
                                            .customFields(
                                                Invoice.LineItem.SubLineItem.CustomFields.builder()
                                                    .build()
                                            )
                                            .name("string")
                                            .quantity(42.23)
                                            .subtotal(42.23)
                                            .chargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .price(42.23)
                                            .tiers(
                                                listOf(
                                                    Invoice.LineItem.SubLineItem.Tier.builder()
                                                        .price(42.23)
                                                        .quantity(42.23)
                                                        .startingAt(42.23)
                                                        .subtotal(42.23)
                                                        .build()
                                                )
                                            )
                                            .build()
                                    )
                                )
                                .unitPrice(42.23)
                                .build()
                        )
                    )
                    .status("DRAFT, VOID, or FINALIZED")
                    .total(42.23)
                    .type(
                        "PLAN_ARREARS, SCHEDULED, USAGE, CORRECTION, CREDIT_PURCHASE, or SEAT_PURCHASE"
                    )
                    .amendmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .contractCustomFields(Invoice.ContractCustomFields.builder().build())
                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .correctionRecord(
                        Invoice.CorrectionRecord.builder()
                            .correctedInvoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .memo("string")
                            .reason("string")
                            .correctedExternalInvoice(
                                Invoice.CorrectionRecord.CorrectedExternalInvoice.builder()
                                    .billingProviderType(
                                        Invoice.CorrectionRecord.CorrectedExternalInvoice
                                            .BillingProviderType
                                            .AWS_MARKETPLACE
                                    )
                                    .externalStatus(
                                        Invoice.CorrectionRecord.CorrectedExternalInvoice
                                            .ExternalStatus
                                            .DRAFT
                                    )
                                    .invoiceId("string")
                                    .issuedAtTimestamp(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .customFields(Invoice.CustomFields.builder().build())
                    .customerCustomFields(Invoice.CustomerCustomFields.builder().build())
                    .endTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .externalInvoice(
                        Invoice.ExternalInvoice.builder()
                            .billingProviderType(
                                Invoice.ExternalInvoice.BillingProviderType.AWS_MARKETPLACE
                            )
                            .externalStatus(Invoice.ExternalInvoice.ExternalStatus.DRAFT)
                            .invoiceId("string")
                            .issuedAtTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .invoiceAdjustments(
                        listOf(
                            Invoice.InvoiceAdjustment.builder()
                                .creditType(
                                    Invoice.InvoiceAdjustment.CreditType.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("string")
                                        .build()
                                )
                                .name("Monthly minimum (\$1,000)")
                                .total(42.23)
                                .creditGrantId("string")
                                .build()
                        )
                    )
                    .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .netPaymentTermsDays(42.23)
                    .netsuiteSalesOrderId("string")
                    .planCustomFields(Invoice.PlanCustomFields.builder().build())
                    .planId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .planName("string")
                    .resellerRoyalty(
                        Invoice.ResellerRoyalty.builder()
                            .fraction("string")
                            .netsuiteResellerId("string")
                            .resellerType(Invoice.ResellerRoyalty.ResellerType.AWS)
                            .awsOptions(
                                Invoice.ResellerRoyalty.AwsOptions.builder()
                                    .awsAccountNumber("string")
                                    .awsOfferId("string")
                                    .awsPayerReferenceId("string")
                                    .build()
                            )
                            .gcpOptions(
                                Invoice.ResellerRoyalty.GcpOptions.builder()
                                    .gcpAccountId("string")
                                    .gcpOfferId("string")
                                    .build()
                            )
                            .build()
                    )
                    .salesforceOpportunityId("string")
                    .startTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .subtotal(42.23)
                    .build()
            )
    }
}
