// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CustomerCreditListResponseTest {

    @Test
    fun createCustomerCreditListResponse() {
        val customerCreditListResponse =
            CustomerCreditListResponse.builder()
                .data(
                    listOf(
                        Credit.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .product(
                                Credit.Product.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .type(Credit.Type.CREDIT)
                            .accessSchedule(
                                ScheduleDuration.builder()
                                    .scheduleItems(
                                        listOf(
                                            ScheduleDuration.ScheduleItem.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .amount(42.23)
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                    )
                                    .creditType(
                                        CreditTypeData.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("name")
                                            .build()
                                    )
                                    .build()
                            )
                            .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                            .applicableProductTags(listOf("string"))
                            .contract(
                                Credit.Contract.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .customFields(Credit.CustomFields.builder().build())
                            .description("description")
                            .ledger(
                                listOf(
                                    Credit.Ledger.ofCreditSegmentStartLedgerEntry(
                                        Credit.Ledger.CreditSegmentStartLedgerEntry.builder()
                                            .amount(42.23)
                                            .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .type(
                                                Credit.Ledger.CreditSegmentStartLedgerEntry.Type
                                                    .CREDIT_SEGMENT_START
                                            )
                                            .build()
                                    )
                                )
                            )
                            .name("name")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .priority(42.23)
                            .rateType(Credit.RateType.COMMIT_RATE)
                            .salesforceOpportunityId("salesforce_opportunity_id")
                            .build()
                    )
                )
                .nextPage("next_page")
                .build()
        assertThat(customerCreditListResponse).isNotNull
        assertThat(customerCreditListResponse.data())
            .containsExactly(
                Credit.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .product(
                        Credit.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .type(Credit.Type.CREDIT)
                    .accessSchedule(
                        ScheduleDuration.builder()
                            .scheduleItems(
                                listOf(
                                    ScheduleDuration.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(42.23)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                            )
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .build()
                    )
                    .applicableContractIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                    .applicableProductIds(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                    .applicableProductTags(listOf("string"))
                    .contract(
                        Credit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
                    )
                    .customFields(Credit.CustomFields.builder().build())
                    .description("description")
                    .ledger(
                        listOf(
                            Credit.Ledger.ofCreditSegmentStartLedgerEntry(
                                Credit.Ledger.CreditSegmentStartLedgerEntry.builder()
                                    .amount(42.23)
                                    .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .type(
                                        Credit.Ledger.CreditSegmentStartLedgerEntry.Type
                                            .CREDIT_SEGMENT_START
                                    )
                                    .build()
                            )
                        )
                    )
                    .name("name")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .priority(42.23)
                    .rateType(Credit.RateType.COMMIT_RATE)
                    .salesforceOpportunityId("salesforce_opportunity_id")
                    .build()
            )
        assertThat(customerCreditListResponse.nextPage()).contains("next_page")
    }
}
