// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class OverrideTest {

    @Test
    fun createOverride() {
        val override =
            Override.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .applicableProductTags(listOf("string"))
                .creditType(
                    CreditTypeData.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .name("name")
                        .build()
                )
                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .entitled(true)
                .isProrated(true)
                .multiplier(42.23)
                .overrideSpecifiers(
                    listOf(
                        Override.OverrideSpecifier.builder()
                            .presentationGroupValues(
                                Override.OverrideSpecifier.PresentationGroupValues.builder().build()
                            )
                            .pricingGroupValues(
                                Override.OverrideSpecifier.PricingGroupValues.builder().build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .productTags(listOf("string"))
                            .build()
                    )
                )
                .overrideTiers(
                    listOf(Override.OverrideTier.builder().multiplier(42.23).size(42.23).build())
                )
                .overwriteRate(
                    Override.OverwriteRate.builder()
                        .rateType(Override.OverwriteRate.RateType.FLAT)
                        .creditType(
                            CreditTypeData.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .build()
                        )
                        .customRate(Override.OverwriteRate.CustomRate.builder().build())
                        .isProrated(true)
                        .price(42.23)
                        .quantity(42.23)
                        .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                        .build()
                )
                .price(42.23)
                .priority(42.23)
                .product(
                    Override.Product.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .name("name")
                        .build()
                )
                .quantity(42.23)
                .rateType(Override.RateType.FLAT)
                .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                .type(Override.Type.OVERWRITE)
                .value(Override.Value.builder().build())
                .build()
        assertThat(override).isNotNull
        assertThat(override.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(override.startingAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(override.applicableProductTags().get()).containsExactly("string")
        assertThat(override.creditType())
            .contains(
                CreditTypeData.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .name("name")
                    .build()
            )
        assertThat(override.endingBefore())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(override.entitled()).contains(true)
        assertThat(override.isProrated()).contains(true)
        assertThat(override.multiplier()).contains(42.23)
        assertThat(override.overrideSpecifiers().get())
            .containsExactly(
                Override.OverrideSpecifier.builder()
                    .presentationGroupValues(
                        Override.OverrideSpecifier.PresentationGroupValues.builder().build()
                    )
                    .pricingGroupValues(
                        Override.OverrideSpecifier.PricingGroupValues.builder().build()
                    )
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .productTags(listOf("string"))
                    .build()
            )
        assertThat(override.overrideTiers().get())
            .containsExactly(Override.OverrideTier.builder().multiplier(42.23).size(42.23).build())
        assertThat(override.overwriteRate())
            .contains(
                Override.OverwriteRate.builder()
                    .rateType(Override.OverwriteRate.RateType.FLAT)
                    .creditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .customRate(Override.OverwriteRate.CustomRate.builder().build())
                    .isProrated(true)
                    .price(42.23)
                    .quantity(42.23)
                    .tiers(listOf(Tier.builder().price(42.23).size(42.23).build()))
                    .build()
            )
        assertThat(override.price()).contains(42.23)
        assertThat(override.priority()).contains(42.23)
        assertThat(override.product())
            .contains(
                Override.Product.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .name("name")
                    .build()
            )
        assertThat(override.quantity()).contains(42.23)
        assertThat(override.rateType()).contains(Override.RateType.FLAT)
        assertThat(override.tiers().get())
            .containsExactly(Tier.builder().price(42.23).size(42.23).build())
        assertThat(override.type()).contains(Override.Type.OVERWRITE)
        assertThat(override.value()).contains(Override.Value.builder().build())
    }
}
