// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PlanDetailTest {

    @Test
    fun createPlanDetail() {
        val planDetail =
            PlanDetail.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .customFields(PlanDetail.CustomFields.builder().build())
                .name("string")
                .creditGrants(
                    listOf(
                        PlanDetail.CreditGrant.builder()
                            .amountGranted(42.23)
                            .amountGrantedCreditType(
                                PlanDetail.CreditGrant.AmountGrantedCreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .amountPaid(42.23)
                            .amountPaidCreditType(
                                PlanDetail.CreditGrant.AmountPaidCreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .effectiveDuration(42.23)
                            .name("string")
                            .priority("string")
                            .sendInvoice(true)
                            .reason("string")
                            .recurrenceDuration(42.23)
                            .recurrenceInterval(42.23)
                            .build()
                    )
                )
                .description("string")
                .minimums(
                    listOf(
                        PlanDetail.Minimum.builder()
                            .creditType(
                                PlanDetail.Minimum.CreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .name("string")
                            .startPeriod(42.23)
                            .value(42.23)
                            .build()
                    )
                )
                .overageRates(
                    listOf(
                        PlanDetail.OverageRate.builder()
                            .creditType(
                                PlanDetail.OverageRate.CreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .fiatCreditType(
                                PlanDetail.OverageRate.FiatCreditType.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .build()
                            )
                            .startPeriod(42.23)
                            .toFiatConversionFactor(42.23)
                            .build()
                    )
                )
                .build()
        assertThat(planDetail).isNotNull
        assertThat(planDetail.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(planDetail.customFields()).isEqualTo(PlanDetail.CustomFields.builder().build())
        assertThat(planDetail.name()).isEqualTo("string")
        assertThat(planDetail.creditGrants().get())
            .containsExactly(
                PlanDetail.CreditGrant.builder()
                    .amountGranted(42.23)
                    .amountGrantedCreditType(
                        PlanDetail.CreditGrant.AmountGrantedCreditType.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .amountPaid(42.23)
                    .amountPaidCreditType(
                        PlanDetail.CreditGrant.AmountPaidCreditType.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .effectiveDuration(42.23)
                    .name("string")
                    .priority("string")
                    .sendInvoice(true)
                    .reason("string")
                    .recurrenceDuration(42.23)
                    .recurrenceInterval(42.23)
                    .build()
            )
        assertThat(planDetail.description()).contains("string")
        assertThat(planDetail.minimums().get())
            .containsExactly(
                PlanDetail.Minimum.builder()
                    .creditType(
                        PlanDetail.Minimum.CreditType.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .name("string")
                    .startPeriod(42.23)
                    .value(42.23)
                    .build()
            )
        assertThat(planDetail.overageRates().get())
            .containsExactly(
                PlanDetail.OverageRate.builder()
                    .creditType(
                        PlanDetail.OverageRate.CreditType.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .fiatCreditType(
                        PlanDetail.OverageRate.FiatCreditType.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .build()
                    )
                    .startPeriod(42.23)
                    .toFiatConversionFactor(42.23)
                    .build()
            )
    }
}
