// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PlanDetailTest {

    @Test
    fun createPlanDetail() {
        val planDetail =
            PlanDetail.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .customFields(PlanDetail.CustomFields.builder().build())
                .name("name")
                .creditGrants(
                    listOf(
                        PlanDetail.CreditGrant.builder()
                            .amountGranted(0.0)
                            .amountGrantedCreditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .amountPaid(0.0)
                            .amountPaidCreditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .effectiveDuration(0.0)
                            .name("name")
                            .priority("priority")
                            .sendInvoice(true)
                            .reason("reason")
                            .recurrenceDuration(0.0)
                            .recurrenceInterval(0.0)
                            .build()
                    )
                )
                .description("description")
                .minimums(
                    listOf(
                        PlanDetail.Minimum.builder()
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .name("name")
                            .startPeriod(0.0)
                            .value(0.0)
                            .build()
                    )
                )
                .overageRates(
                    listOf(
                        PlanDetail.OverageRate.builder()
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .fiatCreditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .startPeriod(0.0)
                            .toFiatConversionFactor(0.0)
                            .build()
                    )
                )
                .build()
        assertThat(planDetail).isNotNull
        assertThat(planDetail.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(planDetail.customFields()).isEqualTo(PlanDetail.CustomFields.builder().build())
        assertThat(planDetail.name()).isEqualTo("name")
        assertThat(planDetail.creditGrants().get())
            .containsExactly(
                PlanDetail.CreditGrant.builder()
                    .amountGranted(0.0)
                    .amountGrantedCreditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .amountPaid(0.0)
                    .amountPaidCreditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .effectiveDuration(0.0)
                    .name("name")
                    .priority("priority")
                    .sendInvoice(true)
                    .reason("reason")
                    .recurrenceDuration(0.0)
                    .recurrenceInterval(0.0)
                    .build()
            )
        assertThat(planDetail.description()).contains("description")
        assertThat(planDetail.minimums().get())
            .containsExactly(
                PlanDetail.Minimum.builder()
                    .creditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .name("name")
                    .startPeriod(0.0)
                    .value(0.0)
                    .build()
            )
        assertThat(planDetail.overageRates().get())
            .containsExactly(
                PlanDetail.OverageRate.builder()
                    .creditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .fiatCreditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .startPeriod(0.0)
                    .toFiatConversionFactor(0.0)
                    .build()
            )
    }
}
