// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import com.metronome.api.core.JsonValue
import kotlin.test.assertNotNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class V1CustomerSetBillingConfigurationsParamsTest {

    @Test
    fun create() {
        V1CustomerSetBillingConfigurationsParams.builder()
            .data(
                listOf(
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("stripe_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty(
                                    "stripe_collection_method",
                                    JsonValue.from("bar"),
                                )
                                .putAdditionalProperty(
                                    "leave_stripe_invoices_in_draft",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_product_code", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty(
                                    "azure_subscription_id",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("5b9e3072-415b-4842-94f0-0b6700c8b6be")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_product_code", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                .putAdditionalProperty(
                                    "aws_is_subscription_product",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("gcp_entitlement_id", JsonValue.from("bar"))
                                .putAdditionalProperty("gcp_service_name", JsonValue.from("bar"))
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty(
                                    "netsuite_customer_id",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                )
            )
            .build()
    }

    @Test
    fun body() {
        val params =
            V1CustomerSetBillingConfigurationsParams.builder()
                .data(
                    listOf(
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                V1CustomerSetBillingConfigurationsParams.Data.Configuration
                                    .builder()
                                    .putAdditionalProperty(
                                        "stripe_customer_id",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty(
                                        "stripe_collection_method",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty(
                                        "leave_stripe_invoices_in_draft",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                V1CustomerSetBillingConfigurationsParams.Data.Configuration
                                    .builder()
                                    .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                    .putAdditionalProperty(
                                        "aws_product_code",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                    .build()
                            )
                            .deliveryMethod(
                                V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                V1CustomerSetBillingConfigurationsParams.Data.Configuration
                                    .builder()
                                    .putAdditionalProperty(
                                        "azure_subscription_id",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("5b9e3072-415b-4842-94f0-0b6700c8b6be")
                            .taxProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                V1CustomerSetBillingConfigurationsParams.Data.Configuration
                                    .builder()
                                    .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                    .putAdditionalProperty(
                                        "aws_product_code",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                    .putAdditionalProperty(
                                        "aws_is_subscription_product",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                V1CustomerSetBillingConfigurationsParams.Data.Configuration
                                    .builder()
                                    .putAdditionalProperty(
                                        "gcp_entitlement_id",
                                        JsonValue.from("bar"),
                                    )
                                    .putAdditionalProperty(
                                        "gcp_service_name",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .configuration(
                                V1CustomerSetBillingConfigurationsParams.Data.Configuration
                                    .builder()
                                    .putAdditionalProperty(
                                        "netsuite_customer_id",
                                        JsonValue.from("bar"),
                                    )
                                    .build()
                            )
                            .deliveryMethod(
                                V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .taxProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                            )
                            .build(),
                    )
                )
                .build()

        val body = params._body()

        assertNotNull(body)
        assertThat(body.data())
            .isEqualTo(
                listOf(
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("stripe_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty(
                                    "stripe_collection_method",
                                    JsonValue.from("bar"),
                                )
                                .putAdditionalProperty(
                                    "leave_stripe_invoices_in_draft",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_product_code", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty(
                                    "azure_subscription_id",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("5b9e3072-415b-4842-94f0-0b6700c8b6be")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("aws_customer_id", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_product_code", JsonValue.from("bar"))
                                .putAdditionalProperty("aws_region", JsonValue.from("bar"))
                                .putAdditionalProperty(
                                    "aws_is_subscription_product",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty("gcp_entitlement_id", JsonValue.from("bar"))
                                .putAdditionalProperty("gcp_service_name", JsonValue.from("bar"))
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .configuration(
                            V1CustomerSetBillingConfigurationsParams.Data.Configuration.builder()
                                .putAdditionalProperty(
                                    "netsuite_customer_id",
                                    JsonValue.from("bar"),
                                )
                                .build()
                        )
                        .deliveryMethod(
                            V1CustomerSetBillingConfigurationsParams.Data.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .deliveryMethodId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .taxProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.TaxProvider.ANROK
                        )
                        .build(),
                )
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            V1CustomerSetBillingConfigurationsParams.builder()
                .data(
                    listOf(
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                        V1CustomerSetBillingConfigurationsParams.Data.builder()
                            .billingProvider(
                                V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                            .build(),
                    )
                )
                .build()

        val body = params._body()

        assertNotNull(body)
        assertThat(body.data())
            .isEqualTo(
                listOf(
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .build(),
                    V1CustomerSetBillingConfigurationsParams.Data.builder()
                        .billingProvider(
                            V1CustomerSetBillingConfigurationsParams.Data.BillingProvider
                                .AWS_MARKETPLACE
                        )
                        .customerId("4db51251-61de-4bfe-b9ce-495e244f3491")
                        .build(),
                )
            )
    }
}
