// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models

import com.metronome.api.core.JsonValue
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class V1PlanGetDetailsResponseTest {

    @Test
    fun createV1PlanGetDetailsResponse() {
        val v1PlanGetDetailsResponse =
            V1PlanGetDetailsResponse.builder()
                .data(
                    PlanDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .customFields(
                            PlanDetail.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .addCreditGrant(
                            PlanDetail.CreditGrant.builder()
                                .amountGranted(0.0)
                                .amountGrantedCreditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .amountPaid(0.0)
                                .amountPaidCreditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .effectiveDuration(0.0)
                                .name("name")
                                .priority("priority")
                                .sendInvoice(true)
                                .reason("reason")
                                .recurrenceDuration(0.0)
                                .recurrenceInterval(0.0)
                                .build()
                        )
                        .description("description")
                        .addMinimum(
                            PlanDetail.Minimum.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .name("name")
                                .startPeriod(0.0)
                                .value(0.0)
                                .build()
                        )
                        .addOverageRate(
                            PlanDetail.OverageRate.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .fiatCreditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .startPeriod(0.0)
                                .toFiatConversionFactor(0.0)
                                .build()
                        )
                        .build()
                )
                .build()
        assertThat(v1PlanGetDetailsResponse).isNotNull
        assertThat(v1PlanGetDetailsResponse.data())
            .isEqualTo(
                PlanDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .customFields(
                        PlanDetail.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .name("name")
                    .addCreditGrant(
                        PlanDetail.CreditGrant.builder()
                            .amountGranted(0.0)
                            .amountGrantedCreditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .amountPaid(0.0)
                            .amountPaidCreditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .effectiveDuration(0.0)
                            .name("name")
                            .priority("priority")
                            .sendInvoice(true)
                            .reason("reason")
                            .recurrenceDuration(0.0)
                            .recurrenceInterval(0.0)
                            .build()
                    )
                    .description("description")
                    .addMinimum(
                        PlanDetail.Minimum.builder()
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .name("name")
                            .startPeriod(0.0)
                            .value(0.0)
                            .build()
                    )
                    .addOverageRate(
                        PlanDetail.OverageRate.builder()
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .fiatCreditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .startPeriod(0.0)
                            .toFiatConversionFactor(0.0)
                            .build()
                    )
                    .build()
            )
    }
}
