// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models.v1.customers.credits

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.metronome.api.core.JsonValue
import com.metronome.api.core.jsonMapper
import com.metronome.api.models.CommitHierarchyConfiguration
import com.metronome.api.models.CommitSpecifier
import com.metronome.api.models.Credit
import com.metronome.api.models.CreditTypeData
import com.metronome.api.models.ScheduleDuration
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CreditListPageResponseTest {

    @Test
    fun create() {
        val creditListPageResponse =
            CreditListPageResponse.builder()
                .addData(
                    Credit.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .product(
                            Credit.Product.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .build()
                        )
                        .type(Credit.Type.CREDIT)
                        .accessSchedule(
                            ScheduleDuration.builder()
                                .addScheduleItem(
                                    ScheduleDuration.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(0.0)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .build()
                        )
                        .addApplicableContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .balance(0.0)
                        .contract(
                            Credit.Contract.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .customFields(
                            Credit.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .hierarchyConfiguration(
                            CommitHierarchyConfiguration.builder()
                                .childAccess(
                                    CommitHierarchyConfiguration.ChildAccess
                                        .CommitHierarchyChildAccessAll
                                        .builder()
                                        .type(
                                            CommitHierarchyConfiguration.ChildAccess
                                                .CommitHierarchyChildAccessAll
                                                .Type
                                                .ALL
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addLedger(
                            Credit.Ledger.CreditSegmentStartLedgerEntry.builder()
                                .amount(0.0)
                                .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .type(
                                    Credit.Ledger.CreditSegmentStartLedgerEntry.Type
                                        .CREDIT_SEGMENT_START
                                )
                                .build()
                        )
                        .name("name")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(Credit.RateType.COMMIT_RATE)
                        .recurringCreditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .rolledOverFrom(
                            Credit.RolledOverFrom.builder()
                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .creditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .salesforceOpportunityId("salesforce_opportunity_id")
                        .addSpecifier(
                            CommitSpecifier.builder()
                                .presentationGroupValues(
                                    CommitSpecifier.PresentationGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    CommitSpecifier.PricingGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .build()
                        )
                        .subscriptionConfig(
                            Credit.SubscriptionConfig.builder()
                                .allocation(Credit.SubscriptionConfig.Allocation.INDIVIDUAL)
                                .applySeatIncreaseConfig(
                                    Credit.SubscriptionConfig.ApplySeatIncreaseConfig.builder()
                                        .isProrated(true)
                                        .build()
                                )
                                .subscriptionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .uniquenessKey("x")
                        .build()
                )
                .nextPage("next_page")
                .build()

        assertThat(creditListPageResponse.data())
            .containsExactly(
                Credit.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .product(
                        Credit.Product.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .type(Credit.Type.CREDIT)
                    .accessSchedule(
                        ScheduleDuration.builder()
                            .addScheduleItem(
                                ScheduleDuration.ScheduleItem.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .build()
                    )
                    .addApplicableContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductTag("string")
                    .balance(0.0)
                    .contract(
                        Credit.Contract.builder().id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e").build()
                    )
                    .customFields(
                        Credit.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .description("description")
                    .hierarchyConfiguration(
                        CommitHierarchyConfiguration.builder()
                            .childAccess(
                                CommitHierarchyConfiguration.ChildAccess
                                    .CommitHierarchyChildAccessAll
                                    .builder()
                                    .type(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .Type
                                            .ALL
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .addLedger(
                        Credit.Ledger.CreditSegmentStartLedgerEntry.builder()
                            .amount(0.0)
                            .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .type(
                                Credit.Ledger.CreditSegmentStartLedgerEntry.Type
                                    .CREDIT_SEGMENT_START
                            )
                            .build()
                    )
                    .name("name")
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .priority(0.0)
                    .rateType(Credit.RateType.COMMIT_RATE)
                    .recurringCreditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .rolledOverFrom(
                        Credit.RolledOverFrom.builder()
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .creditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .salesforceOpportunityId("salesforce_opportunity_id")
                    .addSpecifier(
                        CommitSpecifier.builder()
                            .presentationGroupValues(
                                CommitSpecifier.PresentationGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .pricingGroupValues(
                                CommitSpecifier.PricingGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addProductTag("string")
                            .build()
                    )
                    .subscriptionConfig(
                        Credit.SubscriptionConfig.builder()
                            .allocation(Credit.SubscriptionConfig.Allocation.INDIVIDUAL)
                            .applySeatIncreaseConfig(
                                Credit.SubscriptionConfig.ApplySeatIncreaseConfig.builder()
                                    .isProrated(true)
                                    .build()
                            )
                            .subscriptionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .uniquenessKey("x")
                    .build()
            )
        assertThat(creditListPageResponse.nextPage()).contains("next_page")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val creditListPageResponse =
            CreditListPageResponse.builder()
                .addData(
                    Credit.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .product(
                            Credit.Product.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .build()
                        )
                        .type(Credit.Type.CREDIT)
                        .accessSchedule(
                            ScheduleDuration.builder()
                                .addScheduleItem(
                                    ScheduleDuration.ScheduleItem.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .amount(0.0)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .build()
                        )
                        .addApplicableContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .balance(0.0)
                        .contract(
                            Credit.Contract.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .customFields(
                            Credit.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .hierarchyConfiguration(
                            CommitHierarchyConfiguration.builder()
                                .childAccess(
                                    CommitHierarchyConfiguration.ChildAccess
                                        .CommitHierarchyChildAccessAll
                                        .builder()
                                        .type(
                                            CommitHierarchyConfiguration.ChildAccess
                                                .CommitHierarchyChildAccessAll
                                                .Type
                                                .ALL
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addLedger(
                            Credit.Ledger.CreditSegmentStartLedgerEntry.builder()
                                .amount(0.0)
                                .segmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .type(
                                    Credit.Ledger.CreditSegmentStartLedgerEntry.Type
                                        .CREDIT_SEGMENT_START
                                )
                                .build()
                        )
                        .name("name")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(Credit.RateType.COMMIT_RATE)
                        .recurringCreditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .rolledOverFrom(
                            Credit.RolledOverFrom.builder()
                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .creditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .salesforceOpportunityId("salesforce_opportunity_id")
                        .addSpecifier(
                            CommitSpecifier.builder()
                                .presentationGroupValues(
                                    CommitSpecifier.PresentationGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    CommitSpecifier.PricingGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .build()
                        )
                        .subscriptionConfig(
                            Credit.SubscriptionConfig.builder()
                                .allocation(Credit.SubscriptionConfig.Allocation.INDIVIDUAL)
                                .applySeatIncreaseConfig(
                                    Credit.SubscriptionConfig.ApplySeatIncreaseConfig.builder()
                                        .isProrated(true)
                                        .build()
                                )
                                .subscriptionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .uniquenessKey("x")
                        .build()
                )
                .nextPage("next_page")
                .build()

        val roundtrippedCreditListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(creditListPageResponse),
                jacksonTypeRef<CreditListPageResponse>(),
            )

        assertThat(roundtrippedCreditListPageResponse).isEqualTo(creditListPageResponse)
    }
}
