// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.services

import com.github.tomakehurst.wiremock.client.WireMock.anyUrl
import com.github.tomakehurst.wiremock.client.WireMock.equalTo
import com.github.tomakehurst.wiremock.client.WireMock.matchingJsonPath
import com.github.tomakehurst.wiremock.client.WireMock.ok
import com.github.tomakehurst.wiremock.client.WireMock.post
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.stubFor
import com.github.tomakehurst.wiremock.client.WireMock.verify
import com.github.tomakehurst.wiremock.junit5.WireMockRuntimeInfo
import com.github.tomakehurst.wiremock.junit5.WireMockTest
import com.metronome.api.client.MetronomeClient
import com.metronome.api.client.okhttp.MetronomeOkHttpClient
import com.metronome.api.core.JsonValue
import com.metronome.api.models.BaseThresholdCommit
import com.metronome.api.models.BaseUsageFilter
import com.metronome.api.models.CommitHierarchyConfiguration
import com.metronome.api.models.CommitSpecifierInput
import com.metronome.api.models.PaymentGateConfig
import com.metronome.api.models.PrepaidBalanceThresholdConfiguration
import com.metronome.api.models.SpendThresholdConfiguration
import com.metronome.api.models.Tier
import com.metronome.api.models.v1.contracts.ContractCreateParams
import com.metronome.api.models.v1.usage.UsageIngestParams
import java.time.OffsetDateTime
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.parallel.ResourceLock

@WireMockTest
@ResourceLock("https://github.com/wiremock/wiremock/issues/169")
internal class ServiceParamsTest {

    private lateinit var client: MetronomeClient

    @BeforeEach
    fun beforeEach(wmRuntimeInfo: WireMockRuntimeInfo) {
        client =
            MetronomeOkHttpClient.builder()
                .baseUrl(wmRuntimeInfo.httpBaseUrl)
                .bearerToken("My Bearer Token")
                .build()
    }

    @Test
    fun create() {
        val contractService = client.v1().contracts()
        stubFor(post(anyUrl()).willReturn(ok("{}")))

        contractService.create(
            ContractCreateParams.builder()
                .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                .startingAt(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                .billingProviderConfiguration(
                    ContractCreateParams.BillingProviderConfiguration.builder()
                        .billingProvider(
                            ContractCreateParams.BillingProviderConfiguration.BillingProvider.STRIPE
                        )
                        .billingProviderConfigurationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .deliveryMethod(
                            ContractCreateParams.BillingProviderConfiguration.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .build()
                )
                .addCommit(
                    ContractCreateParams.Commit.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .type(ContractCreateParams.Commit.Type.PREPAID)
                        .accessSchedule(
                            ContractCreateParams.Commit.AccessSchedule.builder()
                                .addScheduleItem(
                                    ContractCreateParams.Commit.AccessSchedule.ScheduleItem
                                        .builder()
                                        .amount(0.0)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .amount(0.0)
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .customFields(
                            ContractCreateParams.Commit.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .hierarchyConfiguration(
                            CommitHierarchyConfiguration.builder()
                                .childAccess(
                                    CommitHierarchyConfiguration.ChildAccess
                                        .CommitHierarchyChildAccessAll
                                        .builder()
                                        .type(
                                            CommitHierarchyConfiguration.ChildAccess
                                                .CommitHierarchyChildAccessAll
                                                .Type
                                                .ALL
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .invoiceSchedule(
                            ContractCreateParams.Commit.InvoiceSchedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .doNotInvoice(true)
                                .recurringSchedule(
                                    ContractCreateParams.Commit.InvoiceSchedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractCreateParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractCreateParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractCreateParams.Commit.InvoiceSchedule.ScheduleItem
                                        .builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .paymentGateConfig(
                            ContractCreateParams.Commit.PaymentGateConfig.builder()
                                .paymentGateType(
                                    ContractCreateParams.Commit.PaymentGateConfig.PaymentGateType
                                        .NONE
                                )
                                .precalculatedTaxConfig(
                                    ContractCreateParams.Commit.PaymentGateConfig
                                        .PrecalculatedTaxConfig
                                        .builder()
                                        .taxAmount(0.0)
                                        .taxName("tax_name")
                                        .build()
                                )
                                .stripeConfig(
                                    ContractCreateParams.Commit.PaymentGateConfig.StripeConfig
                                        .builder()
                                        .paymentType(
                                            ContractCreateParams.Commit.PaymentGateConfig
                                                .StripeConfig
                                                .PaymentType
                                                .INVOICE
                                        )
                                        .invoiceMetadata(
                                            ContractCreateParams.Commit.PaymentGateConfig
                                                .StripeConfig
                                                .InvoiceMetadata
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .onSessionPayment(true)
                                        .build()
                                )
                                .taxType(ContractCreateParams.Commit.PaymentGateConfig.TaxType.NONE)
                                .build()
                        )
                        .priority(0.0)
                        .rateType(ContractCreateParams.Commit.RateType.COMMIT_RATE)
                        .rolloverFraction(0.0)
                        .addSpecifier(
                            CommitSpecifierInput.builder()
                                .presentationGroupValues(
                                    CommitSpecifierInput.PresentationGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    CommitSpecifierInput.PricingGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .build()
                        )
                        .temporaryId("temporary_id")
                        .build()
                )
                .addCredit(
                    ContractCreateParams.Credit.builder()
                        .accessSchedule(
                            ContractCreateParams.Credit.AccessSchedule.builder()
                                .addScheduleItem(
                                    ContractCreateParams.Credit.AccessSchedule.ScheduleItem
                                        .builder()
                                        .amount(0.0)
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .customFields(
                            ContractCreateParams.Credit.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .hierarchyConfiguration(
                            CommitHierarchyConfiguration.builder()
                                .childAccess(
                                    CommitHierarchyConfiguration.ChildAccess
                                        .CommitHierarchyChildAccessAll
                                        .builder()
                                        .type(
                                            CommitHierarchyConfiguration.ChildAccess
                                                .CommitHierarchyChildAccessAll
                                                .Type
                                                .ALL
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .priority(0.0)
                        .rateType(ContractCreateParams.Credit.RateType.COMMIT_RATE)
                        .rolloverFraction(0.0)
                        .addSpecifier(
                            CommitSpecifierInput.builder()
                                .presentationGroupValues(
                                    CommitSpecifierInput.PresentationGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    CommitSpecifierInput.PricingGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .build()
                        )
                        .build()
                )
                .customFields(
                    ContractCreateParams.CustomFields.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .addDiscount(
                    ContractCreateParams.Discount.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractCreateParams.Discount.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .doNotInvoice(true)
                                .recurringSchedule(
                                    ContractCreateParams.Discount.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractCreateParams.Discount.Schedule.RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractCreateParams.Discount.Schedule.RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractCreateParams.Discount.Schedule.ScheduleItem.builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .customFields(
                            ContractCreateParams.Discount.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .hierarchyConfiguration(
                    ContractCreateParams.HierarchyConfiguration.builder()
                        .parent(
                            ContractCreateParams.HierarchyConfiguration.Parent.builder()
                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .parentBehavior(
                            ContractCreateParams.HierarchyConfiguration.ParentBehavior.builder()
                                .invoiceConsolidationType(
                                    ContractCreateParams.HierarchyConfiguration.ParentBehavior
                                        .InvoiceConsolidationType
                                        .CONCATENATE
                                )
                                .build()
                        )
                        .payer(ContractCreateParams.HierarchyConfiguration.Payer.SELF)
                        .usageStatementBehavior(
                            ContractCreateParams.HierarchyConfiguration.UsageStatementBehavior
                                .CONSOLIDATE
                        )
                        .build()
                )
                .multiplierOverridePrioritization(
                    ContractCreateParams.MultiplierOverridePrioritization.LOWEST_MULTIPLIER
                )
                .name("name")
                .netPaymentTermsDays(0.0)
                .netsuiteSalesOrderId("netsuite_sales_order_id")
                .addOverride(
                    ContractCreateParams.Override.builder()
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addApplicableProductTag("string")
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .entitled(true)
                        .isCommitSpecific(true)
                        .multiplier(0.0)
                        .addOverrideSpecifier(
                            ContractCreateParams.Override.OverrideSpecifier.builder()
                                .billingFrequency(
                                    ContractCreateParams.Override.OverrideSpecifier.BillingFrequency
                                        .MONTHLY
                                )
                                .addCommitId("string")
                                .presentationGroupValues(
                                    ContractCreateParams.Override.OverrideSpecifier
                                        .PresentationGroupValues
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    ContractCreateParams.Override.OverrideSpecifier
                                        .PricingGroupValues
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .addRecurringCommitId("string")
                                .build()
                        )
                        .overwriteRate(
                            ContractCreateParams.Override.OverwriteRate.builder()
                                .rateType(ContractCreateParams.Override.OverwriteRate.RateType.FLAT)
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customRate(
                                    ContractCreateParams.Override.OverwriteRate.CustomRate.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .isProrated(true)
                                .price(0.0)
                                .quantity(0.0)
                                .addTier(Tier.builder().price(0.0).size(0.0).build())
                                .build()
                        )
                        .priority(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .target(ContractCreateParams.Override.Target.COMMIT_RATE)
                        .addTier(
                            ContractCreateParams.Override.Tier.builder()
                                .multiplier(0.0)
                                .size(0.0)
                                .build()
                        )
                        .type(ContractCreateParams.Override.Type.OVERWRITE)
                        .build()
                )
                .packageAlias("package_alias")
                .packageId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .prepaidBalanceThresholdConfiguration(
                    PrepaidBalanceThresholdConfiguration.builder()
                        .commit(
                            PrepaidBalanceThresholdConfiguration.Commit.builder()
                                .productId("product_id")
                                .description("description")
                                .name("name")
                                .priority(0.0)
                                .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addApplicableProductTag("string")
                                .addSpecifier(
                                    CommitSpecifierInput.builder()
                                        .presentationGroupValues(
                                            CommitSpecifierInput.PresentationGroupValues.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .pricingGroupValues(
                                            CommitSpecifierInput.PricingGroupValues.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .addProductTag("string")
                                        .build()
                                )
                                .build()
                        )
                        .isEnabled(true)
                        .paymentGateConfig(
                            PaymentGateConfig.builder()
                                .paymentGateType(PaymentGateConfig.PaymentGateType.NONE)
                                .precalculatedTaxConfig(
                                    PaymentGateConfig.PrecalculatedTaxConfig.builder()
                                        .taxAmount(0.0)
                                        .taxName("tax_name")
                                        .build()
                                )
                                .stripeConfig(
                                    PaymentGateConfig.StripeConfig.builder()
                                        .paymentType(
                                            PaymentGateConfig.StripeConfig.PaymentType.INVOICE
                                        )
                                        .invoiceMetadata(
                                            PaymentGateConfig.StripeConfig.InvoiceMetadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .taxType(PaymentGateConfig.TaxType.NONE)
                                .build()
                        )
                        .rechargeToAmount(0.0)
                        .thresholdAmount(0.0)
                        .customCreditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .discountConfiguration(
                            PrepaidBalanceThresholdConfiguration.DiscountConfiguration.builder()
                                .paymentFraction(0.0)
                                .build()
                        )
                        .build()
                )
                .addProfessionalService(
                    ContractCreateParams.ProfessionalService.builder()
                        .maxAmount(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .quantity(0.0)
                        .unitPrice(0.0)
                        .customFields(
                            ContractCreateParams.ProfessionalService.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
                .rateCardAlias("rate_card_alias")
                .rateCardId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                .addRecurringCommit(
                    ContractCreateParams.RecurringCommit.builder()
                        .accessAmount(
                            ContractCreateParams.RecurringCommit.AccessAmount.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .unitPrice(0.0)
                                .quantity(0.0)
                                .build()
                        )
                        .commitDuration(
                            ContractCreateParams.RecurringCommit.CommitDuration.builder()
                                .value(0.0)
                                .unit(
                                    ContractCreateParams.RecurringCommit.CommitDuration.Unit.PERIODS
                                )
                                .build()
                        )
                        .priority(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .description("description")
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .hierarchyConfiguration(
                            CommitHierarchyConfiguration.builder()
                                .childAccess(
                                    CommitHierarchyConfiguration.ChildAccess
                                        .CommitHierarchyChildAccessAll
                                        .builder()
                                        .type(
                                            CommitHierarchyConfiguration.ChildAccess
                                                .CommitHierarchyChildAccessAll
                                                .Type
                                                .ALL
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .invoiceAmount(
                            ContractCreateParams.RecurringCommit.InvoiceAmount.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(0.0)
                                .unitPrice(0.0)
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .proration(ContractCreateParams.RecurringCommit.Proration.NONE)
                        .rateType(ContractCreateParams.RecurringCommit.RateType.COMMIT_RATE)
                        .recurrenceFrequency(
                            ContractCreateParams.RecurringCommit.RecurrenceFrequency.MONTHLY
                        )
                        .rolloverFraction(0.0)
                        .addSpecifier(
                            CommitSpecifierInput.builder()
                                .presentationGroupValues(
                                    CommitSpecifierInput.PresentationGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    CommitSpecifierInput.PricingGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .build()
                        )
                        .subscriptionConfig(
                            ContractCreateParams.RecurringCommit.SubscriptionConfig.builder()
                                .applySeatIncreaseConfig(
                                    ContractCreateParams.RecurringCommit.SubscriptionConfig
                                        .ApplySeatIncreaseConfig
                                        .builder()
                                        .isProrated(true)
                                        .build()
                                )
                                .subscriptionId("subscription_id")
                                .allocation(
                                    ContractCreateParams.RecurringCommit.SubscriptionConfig
                                        .Allocation
                                        .INDIVIDUAL
                                )
                                .build()
                        )
                        .temporaryId("temporary_id")
                        .build()
                )
                .addRecurringCredit(
                    ContractCreateParams.RecurringCredit.builder()
                        .accessAmount(
                            ContractCreateParams.RecurringCredit.AccessAmount.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .unitPrice(0.0)
                                .quantity(0.0)
                                .build()
                        )
                        .commitDuration(
                            ContractCreateParams.RecurringCredit.CommitDuration.builder()
                                .value(0.0)
                                .unit(
                                    ContractCreateParams.RecurringCredit.CommitDuration.Unit.PERIODS
                                )
                                .build()
                        )
                        .priority(0.0)
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .description("description")
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .hierarchyConfiguration(
                            CommitHierarchyConfiguration.builder()
                                .childAccess(
                                    CommitHierarchyConfiguration.ChildAccess
                                        .CommitHierarchyChildAccessAll
                                        .builder()
                                        .type(
                                            CommitHierarchyConfiguration.ChildAccess
                                                .CommitHierarchyChildAccessAll
                                                .Type
                                                .ALL
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .proration(ContractCreateParams.RecurringCredit.Proration.NONE)
                        .rateType(ContractCreateParams.RecurringCredit.RateType.COMMIT_RATE)
                        .recurrenceFrequency(
                            ContractCreateParams.RecurringCredit.RecurrenceFrequency.MONTHLY
                        )
                        .rolloverFraction(0.0)
                        .addSpecifier(
                            CommitSpecifierInput.builder()
                                .presentationGroupValues(
                                    CommitSpecifierInput.PresentationGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    CommitSpecifierInput.PricingGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .build()
                        )
                        .subscriptionConfig(
                            ContractCreateParams.RecurringCredit.SubscriptionConfig.builder()
                                .applySeatIncreaseConfig(
                                    ContractCreateParams.RecurringCredit.SubscriptionConfig
                                        .ApplySeatIncreaseConfig
                                        .builder()
                                        .isProrated(true)
                                        .build()
                                )
                                .subscriptionId("subscription_id")
                                .allocation(
                                    ContractCreateParams.RecurringCredit.SubscriptionConfig
                                        .Allocation
                                        .INDIVIDUAL
                                )
                                .build()
                        )
                        .temporaryId("temporary_id")
                        .build()
                )
                .addResellerRoyalty(
                    ContractCreateParams.ResellerRoyalty.builder()
                        .fraction(0.0)
                        .netsuiteResellerId("netsuite_reseller_id")
                        .resellerType(ContractCreateParams.ResellerRoyalty.ResellerType.AWS)
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addApplicableProductTag("string")
                        .awsOptions(
                            ContractCreateParams.ResellerRoyalty.AwsOptions.builder()
                                .awsAccountNumber("aws_account_number")
                                .awsOfferId("aws_offer_id")
                                .awsPayerReferenceId("aws_payer_reference_id")
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .gcpOptions(
                            ContractCreateParams.ResellerRoyalty.GcpOptions.builder()
                                .gcpAccountId("gcp_account_id")
                                .gcpOfferId("gcp_offer_id")
                                .build()
                        )
                        .resellerContractValue(0.0)
                        .build()
                )
                .revenueSystemConfiguration(
                    ContractCreateParams.RevenueSystemConfiguration.builder()
                        .deliveryMethod(
                            ContractCreateParams.RevenueSystemConfiguration.DeliveryMethod
                                .DIRECT_TO_BILLING_PROVIDER
                        )
                        .provider(ContractCreateParams.RevenueSystemConfiguration.Provider.NETSUITE)
                        .revenueSystemConfigurationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .salesforceOpportunityId("salesforce_opportunity_id")
                .addScheduledCharge(
                    ContractCreateParams.ScheduledCharge.builder()
                        .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .schedule(
                            ContractCreateParams.ScheduledCharge.Schedule.builder()
                                .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .doNotInvoice(true)
                                .recurringSchedule(
                                    ContractCreateParams.ScheduledCharge.Schedule.RecurringSchedule
                                        .builder()
                                        .amountDistribution(
                                            ContractCreateParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .AmountDistribution
                                                .DIVIDED
                                        )
                                        .endingBefore(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frequency(
                                            ContractCreateParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .Frequency
                                                .MONTHLY
                                        )
                                        .startingAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .addScheduleItem(
                                    ContractCreateParams.ScheduledCharge.Schedule.ScheduleItem
                                        .builder()
                                        .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .amount(0.0)
                                        .quantity(0.0)
                                        .unitPrice(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .customFields(
                            ContractCreateParams.ScheduledCharge.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("x")
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .build()
                )
                .scheduledChargesOnUsageInvoices(
                    ContractCreateParams.ScheduledChargesOnUsageInvoices.ALL
                )
                .spendThresholdConfiguration(
                    SpendThresholdConfiguration.builder()
                        .commit(
                            BaseThresholdCommit.builder()
                                .productId("product_id")
                                .description("description")
                                .name("name")
                                .priority(0.0)
                                .build()
                        )
                        .isEnabled(true)
                        .paymentGateConfig(
                            PaymentGateConfig.builder()
                                .paymentGateType(PaymentGateConfig.PaymentGateType.NONE)
                                .precalculatedTaxConfig(
                                    PaymentGateConfig.PrecalculatedTaxConfig.builder()
                                        .taxAmount(0.0)
                                        .taxName("tax_name")
                                        .build()
                                )
                                .stripeConfig(
                                    PaymentGateConfig.StripeConfig.builder()
                                        .paymentType(
                                            PaymentGateConfig.StripeConfig.PaymentType.INVOICE
                                        )
                                        .invoiceMetadata(
                                            PaymentGateConfig.StripeConfig.InvoiceMetadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .taxType(PaymentGateConfig.TaxType.NONE)
                                .build()
                        )
                        .thresholdAmount(0.0)
                        .discountConfiguration(
                            SpendThresholdConfiguration.DiscountConfiguration.builder()
                                .paymentFraction(0.0)
                                .build()
                        )
                        .build()
                )
                .addSubscription(
                    ContractCreateParams.Subscription.builder()
                        .collectionSchedule(
                            ContractCreateParams.Subscription.CollectionSchedule.ADVANCE
                        )
                        .proration(
                            ContractCreateParams.Subscription.Proration.builder()
                                .invoiceBehavior(
                                    ContractCreateParams.Subscription.Proration.InvoiceBehavior
                                        .BILL_IMMEDIATELY
                                )
                                .isProrated(true)
                                .build()
                        )
                        .subscriptionRate(
                            ContractCreateParams.Subscription.SubscriptionRate.builder()
                                .billingFrequency(
                                    ContractCreateParams.Subscription.SubscriptionRate
                                        .BillingFrequency
                                        .MONTHLY
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .customFields(
                            ContractCreateParams.Subscription.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .description("description")
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .initialQuantity(0.0)
                        .name("name")
                        .quantityManagementMode(
                            ContractCreateParams.Subscription.QuantityManagementMode.SEAT_BASED
                        )
                        .seatConfig(
                            ContractCreateParams.Subscription.SeatConfig.builder()
                                .addInitialSeatId("string")
                                .seatGroupKey("seat_group_key")
                                .initialUnassignedSeats(0.0)
                                .build()
                        )
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .temporaryId("temporary_id")
                        .build()
                )
                .totalContractValue(0.0)
                .transition(
                    ContractCreateParams.Transition.builder()
                        .fromContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .type(ContractCreateParams.Transition.Type.SUPERSEDE)
                        .futureInvoiceBehavior(
                            ContractCreateParams.Transition.FutureInvoiceBehavior.builder()
                                .trueup(
                                    ContractCreateParams.Transition.FutureInvoiceBehavior.Trueup
                                        .REMOVE
                                )
                                .build()
                        )
                        .build()
                )
                .uniquenessKey("x")
                .usageFilter(
                    BaseUsageFilter.builder()
                        .groupKey("group_key")
                        .addGroupValue("string")
                        .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .usageStatementSchedule(
                    ContractCreateParams.UsageStatementSchedule.builder()
                        .frequency(ContractCreateParams.UsageStatementSchedule.Frequency.MONTHLY)
                        .billingAnchorDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .day(ContractCreateParams.UsageStatementSchedule.Day.FIRST_OF_MONTH)
                        .invoiceGenerationStartingAt(
                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                        )
                        .build()
                )
                .putAdditionalHeader("Secret-Header", "42")
                .putAdditionalQueryParam("secret_query_param", "42")
                .putAdditionalBodyProperty("secretProperty", JsonValue.from("42"))
                .build()
        )

        verify(
            postRequestedFor(anyUrl())
                .withHeader("Secret-Header", equalTo("42"))
                .withQueryParam("secret_query_param", equalTo("42"))
                .withRequestBody(matchingJsonPath("$.secretProperty", equalTo("42")))
        )
    }

    @Test
    fun ingest() {
        val usageService = client.v1().usage()
        stubFor(post(anyUrl()).willReturn(ok("{}")))

        usageService.ingest(
            UsageIngestParams.builder()
                .addUsage(
                    UsageIngestParams.Usage.builder()
                        .customerId("team@example.com")
                        .eventType("heartbeat")
                        .timestamp("2021-01-01T00:00:00Z")
                        .transactionId("2021-01-01T00:00:00Z_cluster42")
                        .properties(
                            UsageIngestParams.Usage.Properties.builder()
                                .putAdditionalProperty("cluster_id", JsonValue.from("bar"))
                                .putAdditionalProperty("cpu_seconds", JsonValue.from("bar"))
                                .putAdditionalProperty("region", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .putAdditionalHeader("Secret-Header", "42")
                .putAdditionalQueryParam("secret_query_param", "42")
                .build()
        )

        verify(
            postRequestedFor(anyUrl())
                .withHeader("Secret-Header", equalTo("42"))
                .withQueryParam("secret_query_param", equalTo("42"))
        )
    }
}
