// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.models.v1.customers.invoices

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.metronome.api.core.JsonValue
import com.metronome.api.core.jsonMapper
import com.metronome.api.models.CreditTypeData
import com.metronome.api.models.Rate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InvoiceRetrieveResponseTest {

    @Test
    fun create() {
        val invoiceRetrieveResponse =
            InvoiceRetrieveResponse.builder()
                .data(
                    Invoice.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creditType(
                            CreditTypeData.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .build()
                        )
                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addLineItem(
                            Invoice.LineItem.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .name("name")
                                .total(0.0)
                                .type("type")
                                .appliedCommitOrCredit(
                                    Invoice.LineItem.AppliedCommitOrCredit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .type(Invoice.LineItem.AppliedCommitOrCredit.Type.PREPAID)
                                        .build()
                                )
                                .commitCustomFields(
                                    Invoice.LineItem.CommitCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .commitNetsuiteItemId("commit_netsuite_item_id")
                                .commitNetsuiteSalesOrderId("commit_netsuite_sales_order_id")
                                .commitSegmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .commitType("commit_type")
                                .customFields(
                                    Invoice.LineItem.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .discountCustomFields(
                                    Invoice.LineItem.DiscountCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .discountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .groupKey("group_key")
                                .groupValue("group_value")
                                .isProrated(true)
                                .listPrice(
                                    Rate.builder()
                                        .rateType(Rate.RateType.FLAT)
                                        .creditType(
                                            CreditTypeData.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .customRate(
                                            Rate.CustomRate.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .isProrated(true)
                                        .price(0.0)
                                        .pricingGroupValues(
                                            Rate.PricingGroupValues.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .quantity(0.0)
                                        .addTier(Rate.Tier.builder().price(0.0).size(0.0).build())
                                        .build()
                                )
                                .metadata("metadata")
                                .netsuiteInvoiceBillingEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteInvoiceBillingStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteItemId("netsuite_item_id")
                                .origin(
                                    Invoice.LineItem.Origin.builder()
                                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .lineItemId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .postpaidCommit(
                                    Invoice.LineItem.PostpaidCommit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .presentationGroupValues(
                                    Invoice.LineItem.PresentationGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    Invoice.LineItem.PricingGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productCustomFields(
                                    Invoice.LineItem.ProductCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .productType("product_type")
                                .professionalServiceCustomFields(
                                    Invoice.LineItem.ProfessionalServiceCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .professionalServiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(0.0)
                                .resellerType(Invoice.LineItem.ResellerType.AWS)
                                .scheduledChargeCustomFields(
                                    Invoice.LineItem.ScheduledChargeCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .scheduledChargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addSubLineItem(
                                    Invoice.LineItem.SubLineItem.builder()
                                        .customFields(
                                            Invoice.LineItem.SubLineItem.CustomFields.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .name("name")
                                        .quantity(0.0)
                                        .subtotal(0.0)
                                        .chargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .price(0.0)
                                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .tierPeriod(
                                            Invoice.LineItem.SubLineItem.TierPeriod.builder()
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                        .addTier(
                                            Invoice.LineItem.SubLineItem.Tier.builder()
                                                .price(0.0)
                                                .quantity(0.0)
                                                .startingAt(0.0)
                                                .subtotal(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .subscriptionCustomFields(
                                    Invoice.LineItem.SubscriptionCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .subscriptionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .tier(
                                    Invoice.LineItem.Tier.builder()
                                        .level(0.0)
                                        .startingAt("starting_at")
                                        .size("size")
                                        .build()
                                )
                                .unitPrice(0.0)
                                .build()
                        )
                        .status("DRAFT, VOID, or FINALIZED")
                        .total(0.0)
                        .type("SCHEDULED or USAGE")
                        .amendmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .billableStatus(JsonValue.from(mapOf<String, Any>()))
                        .addConstituentInvoice(
                            Invoice.ConstituentInvoice.builder()
                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .contractCustomFields(
                            Invoice.ContractCustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .correctionRecord(
                            Invoice.CorrectionRecord.builder()
                                .correctedInvoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .memo("memo")
                                .reason("reason")
                                .correctedExternalInvoice(
                                    Invoice.CorrectionRecord.CorrectedExternalInvoice.builder()
                                        .billingProviderType(
                                            Invoice.CorrectionRecord.CorrectedExternalInvoice
                                                .BillingProviderType
                                                .AWS_MARKETPLACE
                                        )
                                        .billingProviderError("billing_provider_error")
                                        .externalPaymentId("external_payment_id")
                                        .externalStatus(
                                            Invoice.CorrectionRecord.CorrectedExternalInvoice
                                                .ExternalStatus
                                                .DRAFT
                                        )
                                        .invoiceId("invoice_id")
                                        .invoicedSubTotal(0.0)
                                        .invoicedTotal(0.0)
                                        .issuedAtTimestamp(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .pdfUrl("https://example.com")
                                        .tax(
                                            Invoice.CorrectionRecord.CorrectedExternalInvoice.Tax
                                                .builder()
                                                .totalTaxAmount(0.0)
                                                .totalTaxableAmount(0.0)
                                                .transactionId("transaction_id")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .customFields(
                            Invoice.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .customerCustomFields(
                            Invoice.CustomerCustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .endTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalInvoice(
                            Invoice.ExternalInvoice.builder()
                                .billingProviderType(
                                    Invoice.ExternalInvoice.BillingProviderType.AWS_MARKETPLACE
                                )
                                .billingProviderError("billing_provider_error")
                                .externalPaymentId("external_payment_id")
                                .externalStatus(Invoice.ExternalInvoice.ExternalStatus.DRAFT)
                                .invoiceId("invoice_id")
                                .invoicedSubTotal(0.0)
                                .invoicedTotal(0.0)
                                .issuedAtTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .pdfUrl("https://example.com")
                                .tax(
                                    Invoice.ExternalInvoice.Tax.builder()
                                        .totalTaxAmount(0.0)
                                        .totalTaxableAmount(0.0)
                                        .transactionId("transaction_id")
                                        .build()
                                )
                                .build()
                        )
                        .addInvoiceAdjustment(
                            Invoice.InvoiceAdjustment.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .name("Monthly minimum (\$1,000)")
                                .total(0.0)
                                .creditGrantCustomFields(
                                    Invoice.InvoiceAdjustment.CreditGrantCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .creditGrantId("credit_grant_id")
                                .build()
                        )
                        .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .netPaymentTermsDays(0.0)
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .payer(
                            Invoice.Payer.builder()
                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .planCustomFields(
                            Invoice.PlanCustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .planId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .planName("plan_name")
                        .resellerRoyalty(
                            Invoice.ResellerRoyalty.builder()
                                .fraction("fraction")
                                .netsuiteResellerId("netsuite_reseller_id")
                                .resellerType(Invoice.ResellerRoyalty.ResellerType.AWS)
                                .awsOptions(
                                    Invoice.ResellerRoyalty.AwsOptions.builder()
                                        .awsAccountNumber("aws_account_number")
                                        .awsOfferId("aws_offer_id")
                                        .awsPayerReferenceId("aws_payer_reference_id")
                                        .build()
                                )
                                .gcpOptions(
                                    Invoice.ResellerRoyalty.GcpOptions.builder()
                                        .gcpAccountId("gcp_account_id")
                                        .gcpOfferId("gcp_offer_id")
                                        .build()
                                )
                                .build()
                        )
                        .addRevenueSystemInvoice(
                            Invoice.RevenueSystemInvoice.builder()
                                .revenueSystemExternalEntityType(
                                    "revenue_system_external_entity_type"
                                )
                                .revenueSystemProvider("revenue_system_provider")
                                .syncStatus("sync_status")
                                .errorMessage("error_message")
                                .revenueSystemExternalEntityId("revenue_system_external_entity_id")
                                .build()
                        )
                        .salesforceOpportunityId("salesforce_opportunity_id")
                        .startTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .subtotal(0.0)
                        .build()
                )
                .build()

        assertThat(invoiceRetrieveResponse.data())
            .isEqualTo(
                Invoice.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .creditType(
                        CreditTypeData.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("name")
                            .build()
                    )
                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addLineItem(
                        Invoice.LineItem.builder()
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .name("name")
                            .total(0.0)
                            .type("type")
                            .appliedCommitOrCredit(
                                Invoice.LineItem.AppliedCommitOrCredit.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .type(Invoice.LineItem.AppliedCommitOrCredit.Type.PREPAID)
                                    .build()
                            )
                            .commitCustomFields(
                                Invoice.LineItem.CommitCustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .commitNetsuiteItemId("commit_netsuite_item_id")
                            .commitNetsuiteSalesOrderId("commit_netsuite_sales_order_id")
                            .commitSegmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .commitType("commit_type")
                            .customFields(
                                Invoice.LineItem.CustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .discountCustomFields(
                                Invoice.LineItem.DiscountCustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .discountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .groupKey("group_key")
                            .groupValue("group_value")
                            .isProrated(true)
                            .listPrice(
                                Rate.builder()
                                    .rateType(Rate.RateType.FLAT)
                                    .creditType(
                                        CreditTypeData.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("name")
                                            .build()
                                    )
                                    .customRate(
                                        Rate.CustomRate.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .isProrated(true)
                                    .price(0.0)
                                    .pricingGroupValues(
                                        Rate.PricingGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .quantity(0.0)
                                    .addTier(Rate.Tier.builder().price(0.0).size(0.0).build())
                                    .build()
                            )
                            .metadata("metadata")
                            .netsuiteInvoiceBillingEnd(
                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                            )
                            .netsuiteInvoiceBillingStart(
                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                            )
                            .netsuiteItemId("netsuite_item_id")
                            .origin(
                                Invoice.LineItem.Origin.builder()
                                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .lineItemId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .postpaidCommit(
                                Invoice.LineItem.PostpaidCommit.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .presentationGroupValues(
                                Invoice.LineItem.PresentationGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .pricingGroupValues(
                                Invoice.LineItem.PricingGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .productCustomFields(
                                Invoice.LineItem.ProductCustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addProductTag("string")
                            .productType("product_type")
                            .professionalServiceCustomFields(
                                Invoice.LineItem.ProfessionalServiceCustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .professionalServiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .quantity(0.0)
                            .resellerType(Invoice.LineItem.ResellerType.AWS)
                            .scheduledChargeCustomFields(
                                Invoice.LineItem.ScheduledChargeCustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .scheduledChargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addSubLineItem(
                                Invoice.LineItem.SubLineItem.builder()
                                    .customFields(
                                        Invoice.LineItem.SubLineItem.CustomFields.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .name("name")
                                    .quantity(0.0)
                                    .subtotal(0.0)
                                    .chargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .price(0.0)
                                    .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .tierPeriod(
                                        Invoice.LineItem.SubLineItem.TierPeriod.builder()
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .addTier(
                                        Invoice.LineItem.SubLineItem.Tier.builder()
                                            .price(0.0)
                                            .quantity(0.0)
                                            .startingAt(0.0)
                                            .subtotal(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .subscriptionCustomFields(
                                Invoice.LineItem.SubscriptionCustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .subscriptionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .tier(
                                Invoice.LineItem.Tier.builder()
                                    .level(0.0)
                                    .startingAt("starting_at")
                                    .size("size")
                                    .build()
                            )
                            .unitPrice(0.0)
                            .build()
                    )
                    .status("DRAFT, VOID, or FINALIZED")
                    .total(0.0)
                    .type("SCHEDULED or USAGE")
                    .amendmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .billableStatus(JsonValue.from(mapOf<String, Any>()))
                    .addConstituentInvoice(
                        Invoice.ConstituentInvoice.builder()
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .contractCustomFields(
                        Invoice.ContractCustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .correctionRecord(
                        Invoice.CorrectionRecord.builder()
                            .correctedInvoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .memo("memo")
                            .reason("reason")
                            .correctedExternalInvoice(
                                Invoice.CorrectionRecord.CorrectedExternalInvoice.builder()
                                    .billingProviderType(
                                        Invoice.CorrectionRecord.CorrectedExternalInvoice
                                            .BillingProviderType
                                            .AWS_MARKETPLACE
                                    )
                                    .billingProviderError("billing_provider_error")
                                    .externalPaymentId("external_payment_id")
                                    .externalStatus(
                                        Invoice.CorrectionRecord.CorrectedExternalInvoice
                                            .ExternalStatus
                                            .DRAFT
                                    )
                                    .invoiceId("invoice_id")
                                    .invoicedSubTotal(0.0)
                                    .invoicedTotal(0.0)
                                    .issuedAtTimestamp(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .pdfUrl("https://example.com")
                                    .tax(
                                        Invoice.CorrectionRecord.CorrectedExternalInvoice.Tax
                                            .builder()
                                            .totalTaxAmount(0.0)
                                            .totalTaxableAmount(0.0)
                                            .transactionId("transaction_id")
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .customFields(
                        Invoice.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .customerCustomFields(
                        Invoice.CustomerCustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .endTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .externalInvoice(
                        Invoice.ExternalInvoice.builder()
                            .billingProviderType(
                                Invoice.ExternalInvoice.BillingProviderType.AWS_MARKETPLACE
                            )
                            .billingProviderError("billing_provider_error")
                            .externalPaymentId("external_payment_id")
                            .externalStatus(Invoice.ExternalInvoice.ExternalStatus.DRAFT)
                            .invoiceId("invoice_id")
                            .invoicedSubTotal(0.0)
                            .invoicedTotal(0.0)
                            .issuedAtTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .pdfUrl("https://example.com")
                            .tax(
                                Invoice.ExternalInvoice.Tax.builder()
                                    .totalTaxAmount(0.0)
                                    .totalTaxableAmount(0.0)
                                    .transactionId("transaction_id")
                                    .build()
                            )
                            .build()
                    )
                    .addInvoiceAdjustment(
                        Invoice.InvoiceAdjustment.builder()
                            .creditType(
                                CreditTypeData.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("name")
                                    .build()
                            )
                            .name("Monthly minimum (\$1,000)")
                            .total(0.0)
                            .creditGrantCustomFields(
                                Invoice.InvoiceAdjustment.CreditGrantCustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .creditGrantId("credit_grant_id")
                            .build()
                    )
                    .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .netPaymentTermsDays(0.0)
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .payer(
                        Invoice.Payer.builder()
                            .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .planCustomFields(
                        Invoice.PlanCustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .planId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .planName("plan_name")
                    .resellerRoyalty(
                        Invoice.ResellerRoyalty.builder()
                            .fraction("fraction")
                            .netsuiteResellerId("netsuite_reseller_id")
                            .resellerType(Invoice.ResellerRoyalty.ResellerType.AWS)
                            .awsOptions(
                                Invoice.ResellerRoyalty.AwsOptions.builder()
                                    .awsAccountNumber("aws_account_number")
                                    .awsOfferId("aws_offer_id")
                                    .awsPayerReferenceId("aws_payer_reference_id")
                                    .build()
                            )
                            .gcpOptions(
                                Invoice.ResellerRoyalty.GcpOptions.builder()
                                    .gcpAccountId("gcp_account_id")
                                    .gcpOfferId("gcp_offer_id")
                                    .build()
                            )
                            .build()
                    )
                    .addRevenueSystemInvoice(
                        Invoice.RevenueSystemInvoice.builder()
                            .revenueSystemExternalEntityType("revenue_system_external_entity_type")
                            .revenueSystemProvider("revenue_system_provider")
                            .syncStatus("sync_status")
                            .errorMessage("error_message")
                            .revenueSystemExternalEntityId("revenue_system_external_entity_id")
                            .build()
                    )
                    .salesforceOpportunityId("salesforce_opportunity_id")
                    .startTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .subtotal(0.0)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val invoiceRetrieveResponse =
            InvoiceRetrieveResponse.builder()
                .data(
                    Invoice.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creditType(
                            CreditTypeData.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("name")
                                .build()
                        )
                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addLineItem(
                            Invoice.LineItem.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .name("name")
                                .total(0.0)
                                .type("type")
                                .appliedCommitOrCredit(
                                    Invoice.LineItem.AppliedCommitOrCredit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .type(Invoice.LineItem.AppliedCommitOrCredit.Type.PREPAID)
                                        .build()
                                )
                                .commitCustomFields(
                                    Invoice.LineItem.CommitCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .commitNetsuiteItemId("commit_netsuite_item_id")
                                .commitNetsuiteSalesOrderId("commit_netsuite_sales_order_id")
                                .commitSegmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .commitType("commit_type")
                                .customFields(
                                    Invoice.LineItem.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .discountCustomFields(
                                    Invoice.LineItem.DiscountCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .discountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .groupKey("group_key")
                                .groupValue("group_value")
                                .isProrated(true)
                                .listPrice(
                                    Rate.builder()
                                        .rateType(Rate.RateType.FLAT)
                                        .creditType(
                                            CreditTypeData.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("name")
                                                .build()
                                        )
                                        .customRate(
                                            Rate.CustomRate.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .isProrated(true)
                                        .price(0.0)
                                        .pricingGroupValues(
                                            Rate.PricingGroupValues.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .quantity(0.0)
                                        .addTier(Rate.Tier.builder().price(0.0).size(0.0).build())
                                        .build()
                                )
                                .metadata("metadata")
                                .netsuiteInvoiceBillingEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteInvoiceBillingStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteItemId("netsuite_item_id")
                                .origin(
                                    Invoice.LineItem.Origin.builder()
                                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .lineItemId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .postpaidCommit(
                                    Invoice.LineItem.PostpaidCommit.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .presentationGroupValues(
                                    Invoice.LineItem.PresentationGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    Invoice.LineItem.PricingGroupValues.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productCustomFields(
                                    Invoice.LineItem.ProductCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addProductTag("string")
                                .productType("product_type")
                                .professionalServiceCustomFields(
                                    Invoice.LineItem.ProfessionalServiceCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .professionalServiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(0.0)
                                .resellerType(Invoice.LineItem.ResellerType.AWS)
                                .scheduledChargeCustomFields(
                                    Invoice.LineItem.ScheduledChargeCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .scheduledChargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addSubLineItem(
                                    Invoice.LineItem.SubLineItem.builder()
                                        .customFields(
                                            Invoice.LineItem.SubLineItem.CustomFields.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .name("name")
                                        .quantity(0.0)
                                        .subtotal(0.0)
                                        .chargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .creditGrantId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .price(0.0)
                                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .tierPeriod(
                                            Invoice.LineItem.SubLineItem.TierPeriod.builder()
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                        .addTier(
                                            Invoice.LineItem.SubLineItem.Tier.builder()
                                                .price(0.0)
                                                .quantity(0.0)
                                                .startingAt(0.0)
                                                .subtotal(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .subscriptionCustomFields(
                                    Invoice.LineItem.SubscriptionCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .subscriptionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .tier(
                                    Invoice.LineItem.Tier.builder()
                                        .level(0.0)
                                        .startingAt("starting_at")
                                        .size("size")
                                        .build()
                                )
                                .unitPrice(0.0)
                                .build()
                        )
                        .status("DRAFT, VOID, or FINALIZED")
                        .total(0.0)
                        .type("SCHEDULED or USAGE")
                        .amendmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .billableStatus(JsonValue.from(mapOf<String, Any>()))
                        .addConstituentInvoice(
                            Invoice.ConstituentInvoice.builder()
                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .invoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .contractCustomFields(
                            Invoice.ContractCustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .correctionRecord(
                            Invoice.CorrectionRecord.builder()
                                .correctedInvoiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .memo("memo")
                                .reason("reason")
                                .correctedExternalInvoice(
                                    Invoice.CorrectionRecord.CorrectedExternalInvoice.builder()
                                        .billingProviderType(
                                            Invoice.CorrectionRecord.CorrectedExternalInvoice
                                                .BillingProviderType
                                                .AWS_MARKETPLACE
                                        )
                                        .billingProviderError("billing_provider_error")
                                        .externalPaymentId("external_payment_id")
                                        .externalStatus(
                                            Invoice.CorrectionRecord.CorrectedExternalInvoice
                                                .ExternalStatus
                                                .DRAFT
                                        )
                                        .invoiceId("invoice_id")
                                        .invoicedSubTotal(0.0)
                                        .invoicedTotal(0.0)
                                        .issuedAtTimestamp(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .pdfUrl("https://example.com")
                                        .tax(
                                            Invoice.CorrectionRecord.CorrectedExternalInvoice.Tax
                                                .builder()
                                                .totalTaxAmount(0.0)
                                                .totalTaxableAmount(0.0)
                                                .transactionId("transaction_id")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .customFields(
                            Invoice.CustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .customerCustomFields(
                            Invoice.CustomerCustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .endTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalInvoice(
                            Invoice.ExternalInvoice.builder()
                                .billingProviderType(
                                    Invoice.ExternalInvoice.BillingProviderType.AWS_MARKETPLACE
                                )
                                .billingProviderError("billing_provider_error")
                                .externalPaymentId("external_payment_id")
                                .externalStatus(Invoice.ExternalInvoice.ExternalStatus.DRAFT)
                                .invoiceId("invoice_id")
                                .invoicedSubTotal(0.0)
                                .invoicedTotal(0.0)
                                .issuedAtTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .pdfUrl("https://example.com")
                                .tax(
                                    Invoice.ExternalInvoice.Tax.builder()
                                        .totalTaxAmount(0.0)
                                        .totalTaxableAmount(0.0)
                                        .transactionId("transaction_id")
                                        .build()
                                )
                                .build()
                        )
                        .addInvoiceAdjustment(
                            Invoice.InvoiceAdjustment.builder()
                                .creditType(
                                    CreditTypeData.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .name("name")
                                        .build()
                                )
                                .name("Monthly minimum (\$1,000)")
                                .total(0.0)
                                .creditGrantCustomFields(
                                    Invoice.InvoiceAdjustment.CreditGrantCustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .creditGrantId("credit_grant_id")
                                .build()
                        )
                        .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .netPaymentTermsDays(0.0)
                        .netsuiteSalesOrderId("netsuite_sales_order_id")
                        .payer(
                            Invoice.Payer.builder()
                                .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .planCustomFields(
                            Invoice.PlanCustomFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .planId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .planName("plan_name")
                        .resellerRoyalty(
                            Invoice.ResellerRoyalty.builder()
                                .fraction("fraction")
                                .netsuiteResellerId("netsuite_reseller_id")
                                .resellerType(Invoice.ResellerRoyalty.ResellerType.AWS)
                                .awsOptions(
                                    Invoice.ResellerRoyalty.AwsOptions.builder()
                                        .awsAccountNumber("aws_account_number")
                                        .awsOfferId("aws_offer_id")
                                        .awsPayerReferenceId("aws_payer_reference_id")
                                        .build()
                                )
                                .gcpOptions(
                                    Invoice.ResellerRoyalty.GcpOptions.builder()
                                        .gcpAccountId("gcp_account_id")
                                        .gcpOfferId("gcp_offer_id")
                                        .build()
                                )
                                .build()
                        )
                        .addRevenueSystemInvoice(
                            Invoice.RevenueSystemInvoice.builder()
                                .revenueSystemExternalEntityType(
                                    "revenue_system_external_entity_type"
                                )
                                .revenueSystemProvider("revenue_system_provider")
                                .syncStatus("sync_status")
                                .errorMessage("error_message")
                                .revenueSystemExternalEntityId("revenue_system_external_entity_id")
                                .build()
                        )
                        .salesforceOpportunityId("salesforce_opportunity_id")
                        .startTimestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .subtotal(0.0)
                        .build()
                )
                .build()

        val roundtrippedInvoiceRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(invoiceRetrieveResponse),
                jacksonTypeRef<InvoiceRetrieveResponse>(),
            )

        assertThat(roundtrippedInvoiceRetrieveResponse).isEqualTo(invoiceRetrieveResponse)
    }
}
