// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.services.blocking.v2

import com.metronome.api.TestServerExtension
import com.metronome.api.client.okhttp.MetronomeOkHttpClient
import com.metronome.api.core.JsonValue
import com.metronome.api.models.CommitHierarchyConfiguration
import com.metronome.api.models.CommitSpecifierInput
import com.metronome.api.models.PaymentGateConfigV2
import com.metronome.api.models.PrepaidBalanceThresholdConfigurationV2
import com.metronome.api.models.SpendThresholdConfigurationV2
import com.metronome.api.models.Tier
import com.metronome.api.models.UpdateBaseThresholdCommit
import com.metronome.api.models.V2ContractEditCommitParams
import com.metronome.api.models.V2ContractEditCreditParams
import com.metronome.api.models.V2ContractEditParams
import com.metronome.api.models.V2ContractGetEditHistoryParams
import com.metronome.api.models.V2ContractListParams
import com.metronome.api.models.V2ContractRetrieveParams
import java.time.OffsetDateTime
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
class ContractServiceTest {

    @Test
    fun retrieve() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.v2().contracts()

        val contract =
            contractService.retrieve(
                V2ContractRetrieveParams.builder()
                    .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .asOfDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .includeBalance(true)
                    .includeLedgers(true)
                    .build()
            )

        contract.validate()
    }

    @Test
    fun list() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.v2().contracts()

        val contract =
            contractService.list(
                V2ContractListParams.builder()
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .coveringDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .includeArchived(true)
                    .includeBalance(true)
                    .includeLedgers(true)
                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )

        contract.validate()
    }

    @Test
    fun edit() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.v2().contracts()

        val response =
            contractService.edit(
                V2ContractEditParams.builder()
                    .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .addBillingProviderConfigurationUpdate(
                        V2ContractEditParams.AddBillingProviderConfigurationUpdate.builder()
                            .billingProviderConfiguration(
                                V2ContractEditParams.AddBillingProviderConfigurationUpdate
                                    .BillingProviderConfiguration
                                    .builder()
                                    .billingProvider(
                                        V2ContractEditParams.AddBillingProviderConfigurationUpdate
                                            .BillingProviderConfiguration
                                            .BillingProvider
                                            .AWS_MARKETPLACE
                                    )
                                    .billingProviderConfigurationId(
                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                    )
                                    .deliveryMethod(
                                        V2ContractEditParams.AddBillingProviderConfigurationUpdate
                                            .BillingProviderConfiguration
                                            .DeliveryMethod
                                            .DIRECT_TO_BILLING_PROVIDER
                                    )
                                    .build()
                            )
                            .schedule(
                                V2ContractEditParams.AddBillingProviderConfigurationUpdate.Schedule
                                    .builder()
                                    .effectiveAt(
                                        V2ContractEditParams.AddBillingProviderConfigurationUpdate
                                            .Schedule
                                            .EffectiveAt
                                            .START_OF_CURRENT_PERIOD
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .addAddCommit(
                        V2ContractEditParams.AddCommit.builder()
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .type(V2ContractEditParams.AddCommit.Type.PREPAID)
                            .accessSchedule(
                                V2ContractEditParams.AddCommit.AccessSchedule.builder()
                                    .addScheduleItem(
                                        V2ContractEditParams.AddCommit.AccessSchedule.ScheduleItem
                                            .builder()
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .amount(0.0)
                            .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addApplicableProductTag("string")
                            .customFields(
                                V2ContractEditParams.AddCommit.CustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .description("description")
                            .hierarchyConfiguration(
                                CommitHierarchyConfiguration.builder()
                                    .childAccess(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .builder()
                                            .type(
                                                CommitHierarchyConfiguration.ChildAccess
                                                    .CommitHierarchyChildAccessAll
                                                    .Type
                                                    .ALL
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .invoiceSchedule(
                                V2ContractEditParams.AddCommit.InvoiceSchedule.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .doNotInvoice(true)
                                    .recurringSchedule(
                                        V2ContractEditParams.AddCommit.InvoiceSchedule
                                            .RecurringSchedule
                                            .builder()
                                            .amountDistribution(
                                                V2ContractEditParams.AddCommit.InvoiceSchedule
                                                    .RecurringSchedule
                                                    .AmountDistribution
                                                    .DIVIDED
                                            )
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .frequency(
                                                V2ContractEditParams.AddCommit.InvoiceSchedule
                                                    .RecurringSchedule
                                                    .Frequency
                                                    .MONTHLY
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .addScheduleItem(
                                        V2ContractEditParams.AddCommit.InvoiceSchedule.ScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .paymentGateConfig(
                                V2ContractEditParams.AddCommit.PaymentGateConfig.builder()
                                    .paymentGateType(
                                        V2ContractEditParams.AddCommit.PaymentGateConfig
                                            .PaymentGateType
                                            .NONE
                                    )
                                    .precalculatedTaxConfig(
                                        V2ContractEditParams.AddCommit.PaymentGateConfig
                                            .PrecalculatedTaxConfig
                                            .builder()
                                            .taxAmount(0.0)
                                            .taxName("tax_name")
                                            .build()
                                    )
                                    .stripeConfig(
                                        V2ContractEditParams.AddCommit.PaymentGateConfig
                                            .StripeConfig
                                            .builder()
                                            .paymentType(
                                                V2ContractEditParams.AddCommit.PaymentGateConfig
                                                    .StripeConfig
                                                    .PaymentType
                                                    .INVOICE
                                            )
                                            .invoiceMetadata(
                                                V2ContractEditParams.AddCommit.PaymentGateConfig
                                                    .StripeConfig
                                                    .InvoiceMetadata
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .onSessionPayment(true)
                                            .build()
                                    )
                                    .taxType(
                                        V2ContractEditParams.AddCommit.PaymentGateConfig.TaxType
                                            .NONE
                                    )
                                    .build()
                            )
                            .priority(0.0)
                            .rateType(V2ContractEditParams.AddCommit.RateType.COMMIT_RATE)
                            .rolloverFraction(0.0)
                            .addSpecifier(
                                CommitSpecifierInput.builder()
                                    .presentationGroupValues(
                                        CommitSpecifierInput.PresentationGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        CommitSpecifierInput.PricingGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addProductTag("string")
                                    .build()
                            )
                            .temporaryId("temporary_id")
                            .build()
                    )
                    .addAddCredit(
                        V2ContractEditParams.AddCredit.builder()
                            .accessSchedule(
                                V2ContractEditParams.AddCredit.AccessSchedule.builder()
                                    .addScheduleItem(
                                        V2ContractEditParams.AddCredit.AccessSchedule.ScheduleItem
                                            .builder()
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addApplicableProductTag("string")
                            .customFields(
                                V2ContractEditParams.AddCredit.CustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .description("description")
                            .hierarchyConfiguration(
                                CommitHierarchyConfiguration.builder()
                                    .childAccess(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .builder()
                                            .type(
                                                CommitHierarchyConfiguration.ChildAccess
                                                    .CommitHierarchyChildAccessAll
                                                    .Type
                                                    .ALL
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .priority(0.0)
                            .rateType(V2ContractEditParams.AddCredit.RateType.COMMIT_RATE)
                            .addSpecifier(
                                CommitSpecifierInput.builder()
                                    .presentationGroupValues(
                                        CommitSpecifierInput.PresentationGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        CommitSpecifierInput.PricingGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addProductTag("string")
                                    .build()
                            )
                            .build()
                    )
                    .addAddDiscount(
                        V2ContractEditParams.AddDiscount.builder()
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .schedule(
                                V2ContractEditParams.AddDiscount.Schedule.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .doNotInvoice(true)
                                    .recurringSchedule(
                                        V2ContractEditParams.AddDiscount.Schedule.RecurringSchedule
                                            .builder()
                                            .amountDistribution(
                                                V2ContractEditParams.AddDiscount.Schedule
                                                    .RecurringSchedule
                                                    .AmountDistribution
                                                    .DIVIDED
                                            )
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .frequency(
                                                V2ContractEditParams.AddDiscount.Schedule
                                                    .RecurringSchedule
                                                    .Frequency
                                                    .MONTHLY
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .addScheduleItem(
                                        V2ContractEditParams.AddDiscount.Schedule.ScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .customFields(
                                V2ContractEditParams.AddDiscount.CustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .build()
                    )
                    .addAddOverride(
                        V2ContractEditParams.AddOverride.builder()
                            .startingAt(OffsetDateTime.parse("2024-11-02T00:00:00Z"))
                            .addApplicableProductTag("string")
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .entitled(true)
                            .isCommitSpecific(true)
                            .multiplier(2.0)
                            .addOverrideSpecifier(
                                V2ContractEditParams.AddOverride.OverrideSpecifier.builder()
                                    .billingFrequency(
                                        V2ContractEditParams.AddOverride.OverrideSpecifier
                                            .BillingFrequency
                                            .MONTHLY
                                    )
                                    .addCommitId("string")
                                    .presentationGroupValues(
                                        V2ContractEditParams.AddOverride.OverrideSpecifier
                                            .PresentationGroupValues
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        V2ContractEditParams.AddOverride.OverrideSpecifier
                                            .PricingGroupValues
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addProductTag("string")
                                    .addRecurringCommitId("string")
                                    .addRecurringCreditId("string")
                                    .build()
                            )
                            .overwriteRate(
                                V2ContractEditParams.AddOverride.OverwriteRate.builder()
                                    .rateType(
                                        V2ContractEditParams.AddOverride.OverwriteRate.RateType.FLAT
                                    )
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .customRate(
                                        V2ContractEditParams.AddOverride.OverwriteRate.CustomRate
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .isProrated(true)
                                    .price(0.0)
                                    .quantity(0.0)
                                    .addTier(Tier.builder().price(0.0).size(0.0).build())
                                    .build()
                            )
                            .priority(100.0)
                            .productId("d4fc086c-d8e5-4091-a235-fbba5da4ec14")
                            .target(V2ContractEditParams.AddOverride.Target.COMMIT_RATE)
                            .addTier(
                                V2ContractEditParams.AddOverride.Tier.builder()
                                    .multiplier(0.0)
                                    .size(0.0)
                                    .build()
                            )
                            .type(V2ContractEditParams.AddOverride.Type.OVERWRITE)
                            .build()
                    )
                    .addPrepaidBalanceThresholdConfiguration(
                        PrepaidBalanceThresholdConfigurationV2.builder()
                            .commit(
                                PrepaidBalanceThresholdConfigurationV2.Commit.builder()
                                    .description("description")
                                    .name("name")
                                    .productId("product_id")
                                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addApplicableProductTag("string")
                                    .addSpecifier(
                                        CommitSpecifierInput.builder()
                                            .presentationGroupValues(
                                                CommitSpecifierInput.PresentationGroupValues
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .pricingGroupValues(
                                                CommitSpecifierInput.PricingGroupValues.builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .addProductTag("string")
                                            .build()
                                    )
                                    .build()
                            )
                            .isEnabled(true)
                            .paymentGateConfig(
                                PaymentGateConfigV2.builder()
                                    .paymentGateType(PaymentGateConfigV2.PaymentGateType.NONE)
                                    .precalculatedTaxConfig(
                                        PaymentGateConfigV2.PrecalculatedTaxConfig.builder()
                                            .taxAmount(0.0)
                                            .taxName("tax_name")
                                            .build()
                                    )
                                    .stripeConfig(
                                        PaymentGateConfigV2.StripeConfig.builder()
                                            .paymentType(
                                                PaymentGateConfigV2.StripeConfig.PaymentType.INVOICE
                                            )
                                            .invoiceMetadata(
                                                PaymentGateConfigV2.StripeConfig.InvoiceMetadata
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .taxType(PaymentGateConfigV2.TaxType.NONE)
                                    .build()
                            )
                            .rechargeToAmount(0.0)
                            .thresholdAmount(0.0)
                            .customCreditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .addAddProfessionalService(
                        V2ContractEditParams.AddProfessionalService.builder()
                            .maxAmount(0.0)
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .quantity(0.0)
                            .unitPrice(0.0)
                            .customFields(
                                V2ContractEditParams.AddProfessionalService.CustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .description("description")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .build()
                    )
                    .addAddRecurringCommit(
                        V2ContractEditParams.AddRecurringCommit.builder()
                            .accessAmount(
                                V2ContractEditParams.AddRecurringCommit.AccessAmount.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .unitPrice(0.0)
                                    .quantity(0.0)
                                    .build()
                            )
                            .commitDuration(
                                V2ContractEditParams.AddRecurringCommit.CommitDuration.builder()
                                    .value(0.0)
                                    .unit(
                                        V2ContractEditParams.AddRecurringCommit.CommitDuration.Unit
                                            .PERIODS
                                    )
                                    .build()
                            )
                            .priority(0.0)
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addApplicableProductTag("string")
                            .description("description")
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .hierarchyConfiguration(
                                CommitHierarchyConfiguration.builder()
                                    .childAccess(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .builder()
                                            .type(
                                                CommitHierarchyConfiguration.ChildAccess
                                                    .CommitHierarchyChildAccessAll
                                                    .Type
                                                    .ALL
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .invoiceAmount(
                                V2ContractEditParams.AddRecurringCommit.InvoiceAmount.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .proration(V2ContractEditParams.AddRecurringCommit.Proration.NONE)
                            .rateType(V2ContractEditParams.AddRecurringCommit.RateType.COMMIT_RATE)
                            .recurrenceFrequency(
                                V2ContractEditParams.AddRecurringCommit.RecurrenceFrequency.MONTHLY
                            )
                            .rolloverFraction(0.0)
                            .addSpecifier(
                                CommitSpecifierInput.builder()
                                    .presentationGroupValues(
                                        CommitSpecifierInput.PresentationGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        CommitSpecifierInput.PricingGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addProductTag("string")
                                    .build()
                            )
                            .subscriptionConfig(
                                V2ContractEditParams.AddRecurringCommit.SubscriptionConfig.builder()
                                    .applySeatIncreaseConfig(
                                        V2ContractEditParams.AddRecurringCommit.SubscriptionConfig
                                            .ApplySeatIncreaseConfig
                                            .builder()
                                            .isProrated(true)
                                            .build()
                                    )
                                    .subscriptionId("subscription_id")
                                    .allocation(
                                        V2ContractEditParams.AddRecurringCommit.SubscriptionConfig
                                            .Allocation
                                            .POOLED
                                    )
                                    .build()
                            )
                            .temporaryId("temporary_id")
                            .build()
                    )
                    .addAddRecurringCredit(
                        V2ContractEditParams.AddRecurringCredit.builder()
                            .accessAmount(
                                V2ContractEditParams.AddRecurringCredit.AccessAmount.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .unitPrice(0.0)
                                    .quantity(0.0)
                                    .build()
                            )
                            .commitDuration(
                                V2ContractEditParams.AddRecurringCredit.CommitDuration.builder()
                                    .value(0.0)
                                    .unit(
                                        V2ContractEditParams.AddRecurringCredit.CommitDuration.Unit
                                            .PERIODS
                                    )
                                    .build()
                            )
                            .priority(0.0)
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addApplicableProductTag("string")
                            .description("description")
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .hierarchyConfiguration(
                                CommitHierarchyConfiguration.builder()
                                    .childAccess(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .builder()
                                            .type(
                                                CommitHierarchyConfiguration.ChildAccess
                                                    .CommitHierarchyChildAccessAll
                                                    .Type
                                                    .ALL
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .proration(V2ContractEditParams.AddRecurringCredit.Proration.NONE)
                            .rateType(V2ContractEditParams.AddRecurringCredit.RateType.COMMIT_RATE)
                            .recurrenceFrequency(
                                V2ContractEditParams.AddRecurringCredit.RecurrenceFrequency.MONTHLY
                            )
                            .rolloverFraction(0.0)
                            .addSpecifier(
                                CommitSpecifierInput.builder()
                                    .presentationGroupValues(
                                        CommitSpecifierInput.PresentationGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .pricingGroupValues(
                                        CommitSpecifierInput.PricingGroupValues.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addProductTag("string")
                                    .build()
                            )
                            .subscriptionConfig(
                                V2ContractEditParams.AddRecurringCredit.SubscriptionConfig.builder()
                                    .applySeatIncreaseConfig(
                                        V2ContractEditParams.AddRecurringCredit.SubscriptionConfig
                                            .ApplySeatIncreaseConfig
                                            .builder()
                                            .isProrated(true)
                                            .build()
                                    )
                                    .subscriptionId("subscription_id")
                                    .allocation(
                                        V2ContractEditParams.AddRecurringCredit.SubscriptionConfig
                                            .Allocation
                                            .POOLED
                                    )
                                    .build()
                            )
                            .temporaryId("temporary_id")
                            .build()
                    )
                    .addAddResellerRoyalty(
                        V2ContractEditParams.AddResellerRoyalty.builder()
                            .resellerType(V2ContractEditParams.AddResellerRoyalty.ResellerType.AWS)
                            .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addApplicableProductTag("string")
                            .awsOptions(
                                V2ContractEditParams.AddResellerRoyalty.AwsOptions.builder()
                                    .awsAccountNumber("aws_account_number")
                                    .awsOfferId("aws_offer_id")
                                    .awsPayerReferenceId("aws_payer_reference_id")
                                    .build()
                            )
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .fraction(0.0)
                            .gcpOptions(
                                V2ContractEditParams.AddResellerRoyalty.GcpOptions.builder()
                                    .gcpAccountId("gcp_account_id")
                                    .gcpOfferId("gcp_offer_id")
                                    .build()
                            )
                            .netsuiteResellerId("netsuite_reseller_id")
                            .resellerContractValue(0.0)
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .addRevenueSystemConfigurationUpdate(
                        V2ContractEditParams.AddRevenueSystemConfigurationUpdate.builder()
                            .revenueSystemConfiguration(
                                V2ContractEditParams.AddRevenueSystemConfigurationUpdate
                                    .RevenueSystemConfiguration
                                    .builder()
                                    .deliveryMethod(
                                        V2ContractEditParams.AddRevenueSystemConfigurationUpdate
                                            .RevenueSystemConfiguration
                                            .DeliveryMethod
                                            .DIRECT_TO_BILLING_PROVIDER
                                    )
                                    .provider(
                                        V2ContractEditParams.AddRevenueSystemConfigurationUpdate
                                            .RevenueSystemConfiguration
                                            .Provider
                                            .NETSUITE
                                    )
                                    .revenueSystemConfigurationId(
                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                    )
                                    .build()
                            )
                            .schedule(
                                V2ContractEditParams.AddRevenueSystemConfigurationUpdate.Schedule
                                    .builder()
                                    .effectiveAt(
                                        V2ContractEditParams.AddRevenueSystemConfigurationUpdate
                                            .Schedule
                                            .EffectiveAt
                                            .START_OF_CURRENT_PERIOD
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .addAddScheduledCharge(
                        V2ContractEditParams.AddScheduledCharge.builder()
                            .productId("2e30f074-d04c-412e-a134-851ebfa5ceb2")
                            .schedule(
                                V2ContractEditParams.AddScheduledCharge.Schedule.builder()
                                    .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .doNotInvoice(true)
                                    .recurringSchedule(
                                        V2ContractEditParams.AddScheduledCharge.Schedule
                                            .RecurringSchedule
                                            .builder()
                                            .amountDistribution(
                                                V2ContractEditParams.AddScheduledCharge.Schedule
                                                    .RecurringSchedule
                                                    .AmountDistribution
                                                    .DIVIDED
                                            )
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .frequency(
                                                V2ContractEditParams.AddScheduledCharge.Schedule
                                                    .RecurringSchedule
                                                    .Frequency
                                                    .MONTHLY
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .addScheduleItem(
                                        V2ContractEditParams.AddScheduledCharge.Schedule
                                            .ScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2020-02-15T00:00:00.000Z")
                                            )
                                            .amount(0.0)
                                            .quantity(1.0)
                                            .unitPrice(1000000.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .customFields(
                                V2ContractEditParams.AddScheduledCharge.CustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .name("x")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .build()
                    )
                    .addSpendThresholdConfiguration(
                        SpendThresholdConfigurationV2.builder()
                            .commit(
                                UpdateBaseThresholdCommit.builder()
                                    .description("description")
                                    .name("name")
                                    .productId("product_id")
                                    .build()
                            )
                            .isEnabled(true)
                            .paymentGateConfig(
                                PaymentGateConfigV2.builder()
                                    .paymentGateType(PaymentGateConfigV2.PaymentGateType.NONE)
                                    .precalculatedTaxConfig(
                                        PaymentGateConfigV2.PrecalculatedTaxConfig.builder()
                                            .taxAmount(0.0)
                                            .taxName("tax_name")
                                            .build()
                                    )
                                    .stripeConfig(
                                        PaymentGateConfigV2.StripeConfig.builder()
                                            .paymentType(
                                                PaymentGateConfigV2.StripeConfig.PaymentType.INVOICE
                                            )
                                            .invoiceMetadata(
                                                PaymentGateConfigV2.StripeConfig.InvoiceMetadata
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .taxType(PaymentGateConfigV2.TaxType.NONE)
                                    .build()
                            )
                            .thresholdAmount(0.0)
                            .build()
                    )
                    .addAddSubscription(
                        V2ContractEditParams.AddSubscription.builder()
                            .collectionSchedule(
                                V2ContractEditParams.AddSubscription.CollectionSchedule.ADVANCE
                            )
                            .proration(
                                V2ContractEditParams.AddSubscription.Proration.builder()
                                    .invoiceBehavior(
                                        V2ContractEditParams.AddSubscription.Proration
                                            .InvoiceBehavior
                                            .BILL_IMMEDIATELY
                                    )
                                    .isProrated(true)
                                    .build()
                            )
                            .subscriptionRate(
                                V2ContractEditParams.AddSubscription.SubscriptionRate.builder()
                                    .billingFrequency(
                                        V2ContractEditParams.AddSubscription.SubscriptionRate
                                            .BillingFrequency
                                            .MONTHLY
                                    )
                                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .customFields(
                                V2ContractEditParams.AddSubscription.CustomFields.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .description("description")
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .initialQuantity(0.0)
                            .name("name")
                            .quantityManagementMode(
                                V2ContractEditParams.AddSubscription.QuantityManagementMode
                                    .SEAT_BASED
                            )
                            .seatConfig(
                                V2ContractEditParams.AddSubscription.SeatConfig.builder()
                                    .addInitialSeatId("string")
                                    .seatGroupKey("seat_group_key")
                                    .initialUnassignedSeats(0.0)
                                    .build()
                            )
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .temporaryId("temporary_id")
                            .build()
                    )
                    .allowContractEndingBeforeFinalizedInvoice(true)
                    .addArchiveCommit(
                        V2ContractEditParams.ArchiveCommit.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .addArchiveCredit(
                        V2ContractEditParams.ArchiveCredit.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .addArchiveScheduledCharge(
                        V2ContractEditParams.ArchiveScheduledCharge.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .addRemoveOverride(
                        V2ContractEditParams.RemoveOverride.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .uniquenessKey("x")
                    .addUpdateCommit(
                        V2ContractEditParams.UpdateCommit.builder()
                            .commitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .accessSchedule(
                                V2ContractEditParams.UpdateCommit.AccessSchedule.builder()
                                    .addAddScheduleItem(
                                        V2ContractEditParams.UpdateCommit.AccessSchedule
                                            .AddScheduleItem
                                            .builder()
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .addRemoveScheduleItem(
                                        V2ContractEditParams.UpdateCommit.AccessSchedule
                                            .RemoveScheduleItem
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                    .addUpdateScheduleItem(
                                        V2ContractEditParams.UpdateCommit.AccessSchedule
                                            .UpdateScheduleItem
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addApplicableProductTag("string")
                            .description("description")
                            .hierarchyConfiguration(
                                CommitHierarchyConfiguration.builder()
                                    .childAccess(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .builder()
                                            .type(
                                                CommitHierarchyConfiguration.ChildAccess
                                                    .CommitHierarchyChildAccessAll
                                                    .Type
                                                    .ALL
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .invoiceSchedule(
                                V2ContractEditParams.UpdateCommit.InvoiceSchedule.builder()
                                    .addAddScheduleItem(
                                        V2ContractEditParams.UpdateCommit.InvoiceSchedule
                                            .AddScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .addRemoveScheduleItem(
                                        V2ContractEditParams.UpdateCommit.InvoiceSchedule
                                            .RemoveScheduleItem
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                    .addUpdateScheduleItem(
                                        V2ContractEditParams.UpdateCommit.InvoiceSchedule
                                            .UpdateScheduleItem
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .name("name")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .priority(0.0)
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .rateType(V2ContractEditParams.UpdateCommit.RateType.LIST_RATE)
                            .rolloverFraction(0.0)
                            .build()
                    )
                    .updateContractEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .updateContractName("update_contract_name")
                    .addUpdateCredit(
                        V2ContractEditParams.UpdateCredit.builder()
                            .creditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .accessSchedule(
                                V2ContractEditParams.UpdateCredit.AccessSchedule.builder()
                                    .addAddScheduleItem(
                                        V2ContractEditParams.UpdateCredit.AccessSchedule
                                            .AddScheduleItem
                                            .builder()
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .addRemoveScheduleItem(
                                        V2ContractEditParams.UpdateCredit.AccessSchedule
                                            .RemoveScheduleItem
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                    .addUpdateScheduleItem(
                                        V2ContractEditParams.UpdateCredit.AccessSchedule
                                            .UpdateScheduleItem
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .amount(0.0)
                                            .endingBefore(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addApplicableProductTag("string")
                            .description("description")
                            .hierarchyConfiguration(
                                CommitHierarchyConfiguration.builder()
                                    .childAccess(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .builder()
                                            .type(
                                                CommitHierarchyConfiguration.ChildAccess
                                                    .CommitHierarchyChildAccessAll
                                                    .Type
                                                    .ALL
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .name("name")
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .priority(0.0)
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .rateType(V2ContractEditParams.UpdateCredit.RateType.LIST_RATE)
                            .build()
                    )
                    .updateNetPaymentTermsDays(0.0)
                    .updatePrepaidBalanceThresholdConfiguration(
                        V2ContractEditParams.UpdatePrepaidBalanceThresholdConfiguration.builder()
                            .commit(
                                V2ContractEditParams.UpdatePrepaidBalanceThresholdConfiguration
                                    .Commit
                                    .builder()
                                    .description("description")
                                    .name("name")
                                    .productId("product_id")
                                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addApplicableProductTag("string")
                                    .addSpecifier(
                                        CommitSpecifierInput.builder()
                                            .presentationGroupValues(
                                                CommitSpecifierInput.PresentationGroupValues
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .pricingGroupValues(
                                                CommitSpecifierInput.PricingGroupValues.builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .addProductTag("string")
                                            .build()
                                    )
                                    .build()
                            )
                            .customCreditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .isEnabled(true)
                            .paymentGateConfig(
                                PaymentGateConfigV2.builder()
                                    .paymentGateType(PaymentGateConfigV2.PaymentGateType.NONE)
                                    .precalculatedTaxConfig(
                                        PaymentGateConfigV2.PrecalculatedTaxConfig.builder()
                                            .taxAmount(0.0)
                                            .taxName("tax_name")
                                            .build()
                                    )
                                    .stripeConfig(
                                        PaymentGateConfigV2.StripeConfig.builder()
                                            .paymentType(
                                                PaymentGateConfigV2.StripeConfig.PaymentType.INVOICE
                                            )
                                            .invoiceMetadata(
                                                PaymentGateConfigV2.StripeConfig.InvoiceMetadata
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .taxType(PaymentGateConfigV2.TaxType.NONE)
                                    .build()
                            )
                            .rechargeToAmount(0.0)
                            .thresholdAmount(0.0)
                            .build()
                    )
                    .addUpdateRecurringCommit(
                        V2ContractEditParams.UpdateRecurringCommit.builder()
                            .recurringCommitId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .accessAmount(
                                V2ContractEditParams.UpdateRecurringCommit.AccessAmount.builder()
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .invoiceAmount(
                                V2ContractEditParams.UpdateRecurringCommit.InvoiceAmount.builder()
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .rateType(V2ContractEditParams.UpdateRecurringCommit.RateType.LIST_RATE)
                            .build()
                    )
                    .addUpdateRecurringCredit(
                        V2ContractEditParams.UpdateRecurringCredit.builder()
                            .recurringCreditId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .accessAmount(
                                V2ContractEditParams.UpdateRecurringCredit.AccessAmount.builder()
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .rateType(V2ContractEditParams.UpdateRecurringCredit.RateType.LIST_RATE)
                            .build()
                    )
                    .addUpdateScheduledCharge(
                        V2ContractEditParams.UpdateScheduledCharge.builder()
                            .scheduledChargeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .invoiceSchedule(
                                V2ContractEditParams.UpdateScheduledCharge.InvoiceSchedule.builder()
                                    .addAddScheduleItem(
                                        V2ContractEditParams.UpdateScheduledCharge.InvoiceSchedule
                                            .AddScheduleItem
                                            .builder()
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .addRemoveScheduleItem(
                                        V2ContractEditParams.UpdateScheduledCharge.InvoiceSchedule
                                            .RemoveScheduleItem
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .build()
                                    )
                                    .addUpdateScheduleItem(
                                        V2ContractEditParams.UpdateScheduledCharge.InvoiceSchedule
                                            .UpdateScheduleItem
                                            .builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .amount(0.0)
                                            .quantity(0.0)
                                            .timestamp(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .unitPrice(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .netsuiteSalesOrderId("netsuite_sales_order_id")
                            .build()
                    )
                    .updateSpendThresholdConfiguration(
                        V2ContractEditParams.UpdateSpendThresholdConfiguration.builder()
                            .commit(
                                UpdateBaseThresholdCommit.builder()
                                    .description("description")
                                    .name("name")
                                    .productId("product_id")
                                    .build()
                            )
                            .isEnabled(true)
                            .paymentGateConfig(
                                PaymentGateConfigV2.builder()
                                    .paymentGateType(PaymentGateConfigV2.PaymentGateType.NONE)
                                    .precalculatedTaxConfig(
                                        PaymentGateConfigV2.PrecalculatedTaxConfig.builder()
                                            .taxAmount(0.0)
                                            .taxName("tax_name")
                                            .build()
                                    )
                                    .stripeConfig(
                                        PaymentGateConfigV2.StripeConfig.builder()
                                            .paymentType(
                                                PaymentGateConfigV2.StripeConfig.PaymentType.INVOICE
                                            )
                                            .invoiceMetadata(
                                                PaymentGateConfigV2.StripeConfig.InvoiceMetadata
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .taxType(PaymentGateConfigV2.TaxType.NONE)
                                    .build()
                            )
                            .thresholdAmount(0.0)
                            .build()
                    )
                    .addUpdateSubscription(
                        V2ContractEditParams.UpdateSubscription.builder()
                            .subscriptionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .quantityManagementModeUpdate(
                                V2ContractEditParams.UpdateSubscription.QuantityManagementModeUpdate
                                    .builder()
                                    .quantityManagementMode(
                                        V2ContractEditParams.UpdateSubscription
                                            .QuantityManagementModeUpdate
                                            .QuantityManagementMode
                                            .SEAT_BASED
                                    )
                                    .seatConfig(
                                        V2ContractEditParams.UpdateSubscription
                                            .QuantityManagementModeUpdate
                                            .SeatConfig
                                            .builder()
                                            .seatGroupKey("seat_group_key")
                                            .build()
                                    )
                                    .build()
                            )
                            .addQuantityUpdate(
                                V2ContractEditParams.UpdateSubscription.QuantityUpdate.builder()
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .quantity(0.0)
                                    .quantityDelta(0.0)
                                    .build()
                            )
                            .seatUpdates(
                                V2ContractEditParams.UpdateSubscription.SeatUpdates.builder()
                                    .addAddSeatId(
                                        V2ContractEditParams.UpdateSubscription.SeatUpdates
                                            .AddSeatId
                                            .builder()
                                            .addSeatId("string")
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .addAddUnassignedSeat(
                                        V2ContractEditParams.UpdateSubscription.SeatUpdates
                                            .AddUnassignedSeat
                                            .builder()
                                            .quantity(1.0)
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .addRemoveSeatId(
                                        V2ContractEditParams.UpdateSubscription.SeatUpdates
                                            .RemoveSeatId
                                            .builder()
                                            .addSeatId("string")
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .addRemoveUnassignedSeat(
                                        V2ContractEditParams.UpdateSubscription.SeatUpdates
                                            .RemoveUnassignedSeat
                                            .builder()
                                            .quantity(1.0)
                                            .startingAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )

        response.validate()
    }

    @Test
    fun editCommit() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.v2().contracts()

        val response =
            contractService.editCommit(
                V2ContractEditCommitParams.builder()
                    .commitId("5e7e82cf-ccb7-428c-a96f-a8e4f67af822")
                    .customerId("4c91c473-fc12-445a-9c38-40421d47023f")
                    .accessSchedule(
                        V2ContractEditCommitParams.AccessSchedule.builder()
                            .addAddScheduleItem(
                                V2ContractEditCommitParams.AccessSchedule.AddScheduleItem.builder()
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .addRemoveScheduleItem(
                                V2ContractEditCommitParams.AccessSchedule.RemoveScheduleItem
                                    .builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .addUpdateScheduleItem(
                                V2ContractEditCommitParams.AccessSchedule.UpdateScheduleItem
                                    .builder()
                                    .id("d5edbd32-c744-48cb-9475-a9bca0e6fa39")
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2025-03-12T00:00:00Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .build()
                    )
                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductTag("string")
                    .description("description")
                    .hierarchyConfiguration(
                        CommitHierarchyConfiguration.builder()
                            .childAccess(
                                CommitHierarchyConfiguration.ChildAccess
                                    .CommitHierarchyChildAccessAll
                                    .builder()
                                    .type(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .Type
                                            .ALL
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .invoiceContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .invoiceSchedule(
                        V2ContractEditCommitParams.InvoiceSchedule.builder()
                            .addAddScheduleItem(
                                V2ContractEditCommitParams.InvoiceSchedule.AddScheduleItem.builder()
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .addRemoveScheduleItem(
                                V2ContractEditCommitParams.InvoiceSchedule.RemoveScheduleItem
                                    .builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .addUpdateScheduleItem(
                                V2ContractEditCommitParams.InvoiceSchedule.UpdateScheduleItem
                                    .builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .amount(0.0)
                                    .quantity(0.0)
                                    .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .unitPrice(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .name("name")
                    .priority(0.0)
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .rateType(V2ContractEditCommitParams.RateType.LIST_RATE)
                    .addSpecifier(
                        CommitSpecifierInput.builder()
                            .presentationGroupValues(
                                CommitSpecifierInput.PresentationGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .pricingGroupValues(
                                CommitSpecifierInput.PricingGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addProductTag("string")
                            .build()
                    )
                    .build()
            )

        response.validate()
    }

    @Test
    fun editCredit() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.v2().contracts()

        val response =
            contractService.editCredit(
                V2ContractEditCreditParams.builder()
                    .creditId("5e7e82cf-ccb7-428c-a96f-a8e4f67af822")
                    .customerId("4c91c473-fc12-445a-9c38-40421d47023f")
                    .accessSchedule(
                        V2ContractEditCreditParams.AccessSchedule.builder()
                            .addAddScheduleItem(
                                V2ContractEditCreditParams.AccessSchedule.AddScheduleItem.builder()
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .addRemoveScheduleItem(
                                V2ContractEditCreditParams.AccessSchedule.RemoveScheduleItem
                                    .builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .addUpdateScheduleItem(
                                V2ContractEditCreditParams.AccessSchedule.UpdateScheduleItem
                                    .builder()
                                    .id("d5edbd32-c744-48cb-9475-a9bca0e6fa39")
                                    .amount(0.0)
                                    .endingBefore(OffsetDateTime.parse("2025-03-12T00:00:00Z"))
                                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .build()
                    )
                    .addApplicableProductId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addApplicableProductTag("string")
                    .description("description")
                    .hierarchyConfiguration(
                        CommitHierarchyConfiguration.builder()
                            .childAccess(
                                CommitHierarchyConfiguration.ChildAccess
                                    .CommitHierarchyChildAccessAll
                                    .builder()
                                    .type(
                                        CommitHierarchyConfiguration.ChildAccess
                                            .CommitHierarchyChildAccessAll
                                            .Type
                                            .ALL
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .name("name")
                    .priority(0.0)
                    .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .rateType(V2ContractEditCreditParams.RateType.LIST_RATE)
                    .addSpecifier(
                        CommitSpecifierInput.builder()
                            .presentationGroupValues(
                                CommitSpecifierInput.PresentationGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .pricingGroupValues(
                                CommitSpecifierInput.PricingGroupValues.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addProductTag("string")
                            .build()
                    )
                    .build()
            )

        response.validate()
    }

    @Test
    fun getEditHistory() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.v2().contracts()

        val response =
            contractService.getEditHistory(
                V2ContractGetEditHistoryParams.builder()
                    .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .build()
            )

        response.validate()
    }
}
