// File generated from our OpenAPI spec by Stainless.

package com.metronome.api.services.blocking

import com.metronome.api.TestServerExtension
import com.metronome.api.client.okhttp.MetronomeOkHttpClient
import com.metronome.api.core.JsonValue
import com.metronome.api.models.BaseUsageFilter
import com.metronome.api.models.ContractAddManualBalanceEntryParams
import com.metronome.api.models.ContractAmendParams
import com.metronome.api.models.ContractArchiveParams
import com.metronome.api.models.ContractCreateHistoricalInvoicesParams
import com.metronome.api.models.ContractCreateParams
import com.metronome.api.models.ContractListBalancesParams
import com.metronome.api.models.ContractListParams
import com.metronome.api.models.ContractRetrieveParams
import com.metronome.api.models.ContractRetrieveRateScheduleParams
import com.metronome.api.models.ContractScheduleProServicesInvoiceParams
import com.metronome.api.models.ContractSetUsageFilterParams
import com.metronome.api.models.ContractUpdateEndDateParams
import com.metronome.api.models.Tier
import java.time.OffsetDateTime
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
class ContractServiceTest {

    @Test
    fun callCreate() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractCreateResponse =
            contractService.create(
                ContractCreateParams.builder()
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .startingAt(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                    .billingProviderConfiguration(
                        ContractCreateParams.BillingProviderConfiguration.builder()
                            .billingProvider(
                                ContractCreateParams.BillingProviderConfiguration.BillingProvider
                                    .AWS_MARKETPLACE
                            )
                            .billingProviderConfigurationId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .deliveryMethod(
                                ContractCreateParams.BillingProviderConfiguration.DeliveryMethod
                                    .DIRECT_TO_BILLING_PROVIDER
                            )
                            .build()
                    )
                    .commits(
                        listOf(
                            ContractCreateParams.Commit.builder()
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .type(ContractCreateParams.Commit.Type.PREPAID)
                                .accessSchedule(
                                    ContractCreateParams.Commit.AccessSchedule.builder()
                                        .scheduleItems(
                                            listOf(
                                                ContractCreateParams.Commit.AccessSchedule
                                                    .ScheduleItem
                                                    .builder()
                                                    .amount(0.0)
                                                    .endingBefore(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .startingAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .build()
                                            )
                                        )
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .amount(0.0)
                                .applicableProductIds(
                                    listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                )
                                .applicableProductTags(listOf("string"))
                                .customFields(
                                    ContractCreateParams.Commit.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .description("description")
                                .invoiceSchedule(
                                    ContractCreateParams.Commit.InvoiceSchedule.builder()
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .recurringSchedule(
                                            ContractCreateParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .builder()
                                                .amountDistribution(
                                                    ContractCreateParams.Commit.InvoiceSchedule
                                                        .RecurringSchedule
                                                        .AmountDistribution
                                                        .DIVIDED
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .frequency(
                                                    ContractCreateParams.Commit.InvoiceSchedule
                                                        .RecurringSchedule
                                                        .Frequency
                                                        .MONTHLY
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                        .scheduleItems(
                                            listOf(
                                                ContractCreateParams.Commit.InvoiceSchedule
                                                    .ScheduleItem
                                                    .builder()
                                                    .timestamp(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .amount(0.0)
                                                    .quantity(0.0)
                                                    .unitPrice(0.0)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                                .name("x")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .priority(0.0)
                                .rateType(ContractCreateParams.Commit.RateType.COMMIT_RATE)
                                .rolloverFraction(0.0)
                                .temporaryId("temporary_id")
                                .build()
                        )
                    )
                    .credits(
                        listOf(
                            ContractCreateParams.Credit.builder()
                                .accessSchedule(
                                    ContractCreateParams.Credit.AccessSchedule.builder()
                                        .scheduleItems(
                                            listOf(
                                                ContractCreateParams.Credit.AccessSchedule
                                                    .ScheduleItem
                                                    .builder()
                                                    .amount(0.0)
                                                    .endingBefore(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .startingAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .build()
                                            )
                                        )
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .applicableProductIds(
                                    listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                )
                                .applicableProductTags(listOf("string"))
                                .customFields(
                                    ContractCreateParams.Credit.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .description("description")
                                .name("x")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .priority(0.0)
                                .rateType(ContractCreateParams.Credit.RateType.COMMIT_RATE)
                                .build()
                        )
                    )
                    .customFields(
                        ContractCreateParams.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .discounts(
                        listOf(
                            ContractCreateParams.Discount.builder()
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .schedule(
                                    ContractCreateParams.Discount.Schedule.builder()
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .recurringSchedule(
                                            ContractCreateParams.Discount.Schedule.RecurringSchedule
                                                .builder()
                                                .amountDistribution(
                                                    ContractCreateParams.Discount.Schedule
                                                        .RecurringSchedule
                                                        .AmountDistribution
                                                        .DIVIDED
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .frequency(
                                                    ContractCreateParams.Discount.Schedule
                                                        .RecurringSchedule
                                                        .Frequency
                                                        .MONTHLY
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                        .scheduleItems(
                                            listOf(
                                                ContractCreateParams.Discount.Schedule.ScheduleItem
                                                    .builder()
                                                    .timestamp(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .amount(0.0)
                                                    .quantity(0.0)
                                                    .unitPrice(0.0)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                                .name("x")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .build()
                        )
                    )
                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .multiplierOverridePrioritization(
                        ContractCreateParams.MultiplierOverridePrioritization.LOWEST_MULTIPLIER
                    )
                    .name("name")
                    .netPaymentTermsDays(0.0)
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .overrides(
                        listOf(
                            ContractCreateParams.Override.builder()
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .applicableProductTags(listOf("string"))
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .entitled(true)
                                .isCommitSpecific(true)
                                .multiplier(0.0)
                                .overrideSpecifiers(
                                    listOf(
                                        ContractCreateParams.Override.OverrideSpecifier.builder()
                                            .commitIds(listOf("string"))
                                            .presentationGroupValues(
                                                ContractCreateParams.Override.OverrideSpecifier
                                                    .PresentationGroupValues
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string")
                                                    )
                                                    .build()
                                            )
                                            .pricingGroupValues(
                                                ContractCreateParams.Override.OverrideSpecifier
                                                    .PricingGroupValues
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string")
                                                    )
                                                    .build()
                                            )
                                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .productTags(listOf("string"))
                                            .build()
                                    )
                                )
                                .overwriteRate(
                                    ContractCreateParams.Override.OverwriteRate.builder()
                                        .rateType(
                                            ContractCreateParams.Override.OverwriteRate.RateType
                                                .FLAT
                                        )
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .customRate(
                                            ContractCreateParams.Override.OverwriteRate.CustomRate
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .isProrated(true)
                                        .price(0.0)
                                        .quantity(0.0)
                                        .tiers(listOf(Tier.builder().price(0.0).size(0.0).build()))
                                        .build()
                                )
                                .priority(0.0)
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .target(ContractCreateParams.Override.Target.COMMIT_RATE)
                                .tiers(
                                    listOf(
                                        ContractCreateParams.Override.Tier.builder()
                                            .multiplier(0.0)
                                            .size(0.0)
                                            .build()
                                    )
                                )
                                .type(ContractCreateParams.Override.Type.OVERWRITE)
                                .build()
                        )
                    )
                    .professionalServices(
                        listOf(
                            ContractCreateParams.ProfessionalService.builder()
                                .maxAmount(0.0)
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(0.0)
                                .unitPrice(0.0)
                                .customFields(
                                    ContractCreateParams.ProfessionalService.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .description("description")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .build()
                        )
                    )
                    .rateCardAlias("rate_card_alias")
                    .rateCardId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .resellerRoyalties(
                        listOf(
                            ContractCreateParams.ResellerRoyalty.builder()
                                .fraction(0.0)
                                .netsuiteResellerId("netsuite_reseller_id")
                                .resellerType(ContractCreateParams.ResellerRoyalty.ResellerType.AWS)
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .applicableProductIds(
                                    listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                )
                                .applicableProductTags(listOf("string"))
                                .awsOptions(
                                    ContractCreateParams.ResellerRoyalty.AwsOptions.builder()
                                        .awsAccountNumber("aws_account_number")
                                        .awsOfferId("aws_offer_id")
                                        .awsPayerReferenceId("aws_payer_reference_id")
                                        .build()
                                )
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .gcpOptions(
                                    ContractCreateParams.ResellerRoyalty.GcpOptions.builder()
                                        .gcpAccountId("gcp_account_id")
                                        .gcpOfferId("gcp_offer_id")
                                        .build()
                                )
                                .resellerContractValue(0.0)
                                .build()
                        )
                    )
                    .salesforceOpportunityId("salesforce_opportunity_id")
                    .scheduledCharges(
                        listOf(
                            ContractCreateParams.ScheduledCharge.builder()
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .schedule(
                                    ContractCreateParams.ScheduledCharge.Schedule.builder()
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .recurringSchedule(
                                            ContractCreateParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .builder()
                                                .amountDistribution(
                                                    ContractCreateParams.ScheduledCharge.Schedule
                                                        .RecurringSchedule
                                                        .AmountDistribution
                                                        .DIVIDED
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .frequency(
                                                    ContractCreateParams.ScheduledCharge.Schedule
                                                        .RecurringSchedule
                                                        .Frequency
                                                        .MONTHLY
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                        .scheduleItems(
                                            listOf(
                                                ContractCreateParams.ScheduledCharge.Schedule
                                                    .ScheduleItem
                                                    .builder()
                                                    .timestamp(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .amount(0.0)
                                                    .quantity(0.0)
                                                    .unitPrice(0.0)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                                .name("x")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .build()
                        )
                    )
                    .scheduledChargesOnUsageInvoices(
                        ContractCreateParams.ScheduledChargesOnUsageInvoices.ALL
                    )
                    .totalContractValue(0.0)
                    .transition(
                        ContractCreateParams.Transition.builder()
                            .fromContractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .type(ContractCreateParams.Transition.Type.SUPERSEDE)
                            .futureInvoiceBehavior(
                                ContractCreateParams.Transition.FutureInvoiceBehavior.builder()
                                    .trueup(
                                        ContractCreateParams.Transition.FutureInvoiceBehavior.Trueup
                                            .REMOVE
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .uniquenessKey("x")
                    .usageFilter(
                        BaseUsageFilter.builder()
                            .groupKey("group_key")
                            .groupValues(listOf("string"))
                            .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .usageStatementSchedule(
                        ContractCreateParams.UsageStatementSchedule.builder()
                            .frequency(
                                ContractCreateParams.UsageStatementSchedule.Frequency.MONTHLY
                            )
                            .billingAnchorDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .day(ContractCreateParams.UsageStatementSchedule.Day.FIRST_OF_MONTH)
                            .invoiceGenerationStartingAt(
                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                            )
                            .build()
                    )
                    .build()
            )
        println(contractCreateResponse)
        contractCreateResponse.validate()
    }

    @Test
    fun callRetrieve() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractRetrieveResponse =
            contractService.retrieve(
                ContractRetrieveParams.builder()
                    .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .includeBalance(true)
                    .includeLedgers(true)
                    .build()
            )
        println(contractRetrieveResponse)
        contractRetrieveResponse.validate()
    }

    @Test
    fun callList() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractListResponse =
            contractService.list(
                ContractListParams.builder()
                    .customerId("9b85c1c1-5238-4f2a-a409-61412905e1e1")
                    .coveringDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .includeArchived(true)
                    .includeBalance(true)
                    .includeLedgers(true)
                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        println(contractListResponse)
        contractListResponse.validate()
    }

    @Test
    fun callAddManualBalanceEntry() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        contractService.addManualBalanceEntry(
            ContractAddManualBalanceEntryParams.builder()
                .id("6162d87b-e5db-4a33-b7f2-76ce6ead4e85")
                .amount(-1000.0)
                .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                .reason("Reason for entry")
                .segmentId("66368e29-3f97-4d15-a6e9-120897f0070a")
                .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                .timestamp(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()
        )
    }

    @Test
    fun callAmend() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractAmendResponse =
            contractService.amend(
                ContractAmendParams.builder()
                    .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .startingAt(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                    .commits(
                        listOf(
                            ContractAmendParams.Commit.builder()
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .type(ContractAmendParams.Commit.Type.PREPAID)
                                .accessSchedule(
                                    ContractAmendParams.Commit.AccessSchedule.builder()
                                        .scheduleItems(
                                            listOf(
                                                ContractAmendParams.Commit.AccessSchedule
                                                    .ScheduleItem
                                                    .builder()
                                                    .amount(0.0)
                                                    .endingBefore(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .startingAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .build()
                                            )
                                        )
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .amount(0.0)
                                .applicableProductIds(
                                    listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                )
                                .applicableProductTags(listOf("string"))
                                .customFields(
                                    ContractAmendParams.Commit.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .description("description")
                                .invoiceSchedule(
                                    ContractAmendParams.Commit.InvoiceSchedule.builder()
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .recurringSchedule(
                                            ContractAmendParams.Commit.InvoiceSchedule
                                                .RecurringSchedule
                                                .builder()
                                                .amountDistribution(
                                                    ContractAmendParams.Commit.InvoiceSchedule
                                                        .RecurringSchedule
                                                        .AmountDistribution
                                                        .DIVIDED
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .frequency(
                                                    ContractAmendParams.Commit.InvoiceSchedule
                                                        .RecurringSchedule
                                                        .Frequency
                                                        .MONTHLY
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                        .scheduleItems(
                                            listOf(
                                                ContractAmendParams.Commit.InvoiceSchedule
                                                    .ScheduleItem
                                                    .builder()
                                                    .timestamp(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .amount(0.0)
                                                    .quantity(0.0)
                                                    .unitPrice(0.0)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                                .name("x")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .priority(0.0)
                                .rateType(ContractAmendParams.Commit.RateType.COMMIT_RATE)
                                .rolloverFraction(0.0)
                                .temporaryId("temporary_id")
                                .build()
                        )
                    )
                    .credits(
                        listOf(
                            ContractAmendParams.Credit.builder()
                                .accessSchedule(
                                    ContractAmendParams.Credit.AccessSchedule.builder()
                                        .scheduleItems(
                                            listOf(
                                                ContractAmendParams.Credit.AccessSchedule
                                                    .ScheduleItem
                                                    .builder()
                                                    .amount(0.0)
                                                    .endingBefore(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .startingAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .build()
                                            )
                                        )
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .applicableProductIds(
                                    listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                )
                                .applicableProductTags(listOf("string"))
                                .customFields(
                                    ContractAmendParams.Credit.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .description("description")
                                .name("x")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .priority(0.0)
                                .rateType(ContractAmendParams.Credit.RateType.COMMIT_RATE)
                                .build()
                        )
                    )
                    .customFields(
                        ContractAmendParams.CustomFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .discounts(
                        listOf(
                            ContractAmendParams.Discount.builder()
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .schedule(
                                    ContractAmendParams.Discount.Schedule.builder()
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .recurringSchedule(
                                            ContractAmendParams.Discount.Schedule.RecurringSchedule
                                                .builder()
                                                .amountDistribution(
                                                    ContractAmendParams.Discount.Schedule
                                                        .RecurringSchedule
                                                        .AmountDistribution
                                                        .DIVIDED
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .frequency(
                                                    ContractAmendParams.Discount.Schedule
                                                        .RecurringSchedule
                                                        .Frequency
                                                        .MONTHLY
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                        .scheduleItems(
                                            listOf(
                                                ContractAmendParams.Discount.Schedule.ScheduleItem
                                                    .builder()
                                                    .timestamp(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .amount(0.0)
                                                    .quantity(0.0)
                                                    .unitPrice(0.0)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                                .name("x")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .build()
                        )
                    )
                    .netsuiteSalesOrderId("netsuite_sales_order_id")
                    .overrides(
                        listOf(
                            ContractAmendParams.Override.builder()
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .applicableProductTags(listOf("string"))
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .entitled(true)
                                .isCommitSpecific(true)
                                .multiplier(0.0)
                                .overrideSpecifiers(
                                    listOf(
                                        ContractAmendParams.Override.OverrideSpecifier.builder()
                                            .commitIds(listOf("string"))
                                            .presentationGroupValues(
                                                ContractAmendParams.Override.OverrideSpecifier
                                                    .PresentationGroupValues
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string")
                                                    )
                                                    .build()
                                            )
                                            .pricingGroupValues(
                                                ContractAmendParams.Override.OverrideSpecifier
                                                    .PricingGroupValues
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string")
                                                    )
                                                    .build()
                                            )
                                            .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .productTags(listOf("string"))
                                            .build()
                                    )
                                )
                                .overwriteRate(
                                    ContractAmendParams.Override.OverwriteRate.builder()
                                        .rateType(
                                            ContractAmendParams.Override.OverwriteRate.RateType.FLAT
                                        )
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .customRate(
                                            ContractAmendParams.Override.OverwriteRate.CustomRate
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .isProrated(true)
                                        .price(0.0)
                                        .quantity(0.0)
                                        .tiers(listOf(Tier.builder().price(0.0).size(0.0).build()))
                                        .build()
                                )
                                .priority(0.0)
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .target(ContractAmendParams.Override.Target.COMMIT_RATE)
                                .tiers(
                                    listOf(
                                        ContractAmendParams.Override.Tier.builder()
                                            .multiplier(0.0)
                                            .size(0.0)
                                            .build()
                                    )
                                )
                                .type(ContractAmendParams.Override.Type.OVERWRITE)
                                .build()
                        )
                    )
                    .professionalServices(
                        listOf(
                            ContractAmendParams.ProfessionalService.builder()
                                .maxAmount(0.0)
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .quantity(0.0)
                                .unitPrice(0.0)
                                .customFields(
                                    ContractAmendParams.ProfessionalService.CustomFields.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .description("description")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .build()
                        )
                    )
                    .resellerRoyalties(
                        listOf(
                            ContractAmendParams.ResellerRoyalty.builder()
                                .resellerType(ContractAmendParams.ResellerRoyalty.ResellerType.AWS)
                                .applicableProductIds(
                                    listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                )
                                .applicableProductTags(listOf("string"))
                                .awsOptions(
                                    ContractAmendParams.ResellerRoyalty.AwsOptions.builder()
                                        .awsAccountNumber("aws_account_number")
                                        .awsOfferId("aws_offer_id")
                                        .awsPayerReferenceId("aws_payer_reference_id")
                                        .build()
                                )
                                .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .fraction(0.0)
                                .gcpOptions(
                                    ContractAmendParams.ResellerRoyalty.GcpOptions.builder()
                                        .gcpAccountId("gcp_account_id")
                                        .gcpOfferId("gcp_offer_id")
                                        .build()
                                )
                                .netsuiteResellerId("netsuite_reseller_id")
                                .resellerContractValue(0.0)
                                .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                    )
                    .salesforceOpportunityId("salesforce_opportunity_id")
                    .scheduledCharges(
                        listOf(
                            ContractAmendParams.ScheduledCharge.builder()
                                .productId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .schedule(
                                    ContractAmendParams.ScheduledCharge.Schedule.builder()
                                        .creditTypeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .recurringSchedule(
                                            ContractAmendParams.ScheduledCharge.Schedule
                                                .RecurringSchedule
                                                .builder()
                                                .amountDistribution(
                                                    ContractAmendParams.ScheduledCharge.Schedule
                                                        .RecurringSchedule
                                                        .AmountDistribution
                                                        .DIVIDED
                                                )
                                                .endingBefore(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .frequency(
                                                    ContractAmendParams.ScheduledCharge.Schedule
                                                        .RecurringSchedule
                                                        .Frequency
                                                        .MONTHLY
                                                )
                                                .startingAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .amount(0.0)
                                                .quantity(0.0)
                                                .unitPrice(0.0)
                                                .build()
                                        )
                                        .scheduleItems(
                                            listOf(
                                                ContractAmendParams.ScheduledCharge.Schedule
                                                    .ScheduleItem
                                                    .builder()
                                                    .timestamp(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .amount(0.0)
                                                    .quantity(0.0)
                                                    .unitPrice(0.0)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                                .name("x")
                                .netsuiteSalesOrderId("netsuite_sales_order_id")
                                .build()
                        )
                    )
                    .totalContractValue(0.0)
                    .build()
            )
        println(contractAmendResponse)
        contractAmendResponse.validate()
    }

    @Test
    fun callArchive() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractArchiveResponse =
            contractService.archive(
                ContractArchiveParams.builder()
                    .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .voidInvoices(true)
                    .build()
            )
        println(contractArchiveResponse)
        contractArchiveResponse.validate()
    }

    @Test
    fun callCreateHistoricalInvoices() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractCreateHistoricalInvoicesResponse =
            contractService.createHistoricalInvoices(
                ContractCreateHistoricalInvoicesParams.builder()
                    .invoices(
                        listOf(
                            ContractCreateHistoricalInvoicesParams.Invoice.builder()
                                .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                                .creditTypeId("2714e483-4ff1-48e4-9e25-ac732e8f24f2")
                                .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                                .exclusiveEndDate(OffsetDateTime.parse("2020-02-01T00:00:00.000Z"))
                                .inclusiveStartDate(
                                    OffsetDateTime.parse("2020-01-01T00:00:00.000Z")
                                )
                                .issueDate(OffsetDateTime.parse("2020-02-01T00:00:00.000Z"))
                                .usageLineItems(
                                    listOf(
                                        ContractCreateHistoricalInvoicesParams.Invoice.UsageLineItem
                                            .builder()
                                            .exclusiveEndDate(
                                                OffsetDateTime.parse("2020-02-01T00:00:00.000Z")
                                            )
                                            .inclusiveStartDate(
                                                OffsetDateTime.parse("2020-01-01T00:00:00.000Z")
                                            )
                                            .productId("f14d6729-6a44-4b13-9908-9387f1918790")
                                            .presentationGroupValues(
                                                ContractCreateHistoricalInvoicesParams.Invoice
                                                    .UsageLineItem
                                                    .PresentationGroupValues
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string")
                                                    )
                                                    .build()
                                            )
                                            .pricingGroupValues(
                                                ContractCreateHistoricalInvoicesParams.Invoice
                                                    .UsageLineItem
                                                    .PricingGroupValues
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string")
                                                    )
                                                    .build()
                                            )
                                            .quantity(100.0)
                                            .subtotalsWithQuantity(
                                                listOf(
                                                    ContractCreateHistoricalInvoicesParams.Invoice
                                                        .UsageLineItem
                                                        .SubtotalsWithQuantity
                                                        .builder()
                                                        .exclusiveEndDate(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .inclusiveStartDate(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .quantity(0.0)
                                                        .build()
                                                )
                                            )
                                            .build()
                                    )
                                )
                                .billableStatus(
                                    ContractCreateHistoricalInvoicesParams.Invoice.BillableStatus
                                        .BILLABLE
                                )
                                .breakdownGranularity(
                                    ContractCreateHistoricalInvoicesParams.Invoice
                                        .BreakdownGranularity
                                        .HOUR
                                )
                                .customFields(
                                    ContractCreateHistoricalInvoicesParams.Invoice.CustomFields
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                    )
                    .preview(false)
                    .build()
            )
        println(contractCreateHistoricalInvoicesResponse)
        contractCreateHistoricalInvoicesResponse.validate()
    }

    @Test
    fun callListBalances() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractListBalancesResponse =
            contractService.listBalances(
                ContractListBalancesParams.builder()
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .id("6162d87b-e5db-4a33-b7f2-76ce6ead4e85")
                    .coveringDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .effectiveBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .includeArchived(true)
                    .includeBalance(true)
                    .includeContractBalances(true)
                    .includeLedgers(true)
                    .nextPage("next_page")
                    .startingAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        println(contractListBalancesResponse)
        contractListBalancesResponse.validate()
    }

    @Test
    fun callRetrieveRateSchedule() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractRetrieveRateScheduleResponse =
            contractService.retrieveRateSchedule(
                ContractRetrieveRateScheduleParams.builder()
                    .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .limit(1L)
                    .nextPage("next_page")
                    .at(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                    .selectors(
                        listOf(
                            ContractRetrieveRateScheduleParams.Selector.builder()
                                .partialPricingGroupValues(
                                    ContractRetrieveRateScheduleParams.Selector
                                        .PartialPricingGroupValues
                                        .builder()
                                        .putAdditionalProperty(
                                            "region",
                                            JsonValue.from("us-west-2")
                                        )
                                        .putAdditionalProperty("cloud", JsonValue.from("aws"))
                                        .build()
                                )
                                .pricingGroupValues(
                                    ContractRetrieveRateScheduleParams.Selector.PricingGroupValues
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .productId("d6300dbb-882e-4d2d-8dec-5125d16b65d0")
                                .productTags(listOf("string"))
                                .build()
                        )
                    )
                    .build()
            )
        println(contractRetrieveRateScheduleResponse)
        contractRetrieveRateScheduleResponse.validate()
    }

    @Test
    fun callScheduleProServicesInvoice() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractScheduleProServicesInvoiceResponse =
            contractService.scheduleProServicesInvoice(
                ContractScheduleProServicesInvoiceParams.builder()
                    .contractId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .customerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .lineItems(
                        listOf(
                            ContractScheduleProServicesInvoiceParams.LineItem.builder()
                                .professionalServiceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .amendmentId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .amount(0.0)
                                .metadata("metadata")
                                .netsuiteInvoiceBillingEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .netsuiteInvoiceBillingStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .quantity(0.0)
                                .unitPrice(0.0)
                                .build()
                        )
                    )
                    .netsuiteInvoiceHeaderEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .netsuiteInvoiceHeaderStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        println(contractScheduleProServicesInvoiceResponse)
        contractScheduleProServicesInvoiceResponse.validate()
    }

    @Test
    fun callSetUsageFilter() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        contractService.setUsageFilter(
            ContractSetUsageFilterParams.builder()
                .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                .groupKey("business_subscription_id")
                .groupValues(listOf("ID-1", "ID-2"))
                .startingAt(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                .build()
        )
    }

    @Test
    fun callUpdateEndDate() {
        val client =
            MetronomeOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .bearerToken("My Bearer Token")
                .build()
        val contractService = client.contracts()
        val contractUpdateEndDateResponse =
            contractService.updateEndDate(
                ContractUpdateEndDateParams.builder()
                    .contractId("d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc")
                    .customerId("13117714-3f05-48e5-a6e9-a66093f13b4d")
                    .allowEndingBeforeFinalizedInvoice(true)
                    .endingBefore(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                    .build()
            )
        println(contractUpdateEndDateResponse)
        contractUpdateEndDateResponse.validate()
    }
}
